#include "attr.h"
SUBROUTINE ACADVEC (KIDIA, KFDIA, KLON, KTDIA, KLEV, PDELP, PAPHI, PVAR, PVARW, PFVAR, &
                  & KSTACK, PSTACK, KPSTSZ, KKSTSZ, KPSTPT, KKSTPT)

! ========================================================

!   Compute vertical flux of a variable with vertical speed PVARW

! ========================================================

!   Auteur: Yves Bouteloup, CNRM/GMAP

!   Date: 2010-12   

!     Modifications.
!     --------------
!         2012-06-22, J.M. Piriou: if LADVLIM=.TRUE. minimise p2 to the value such that 
!                     the transport scheme cannot transport beyond a distance of w*deltat, in a time-step.

! ========================================================

! ---------------
! INPUT VARIABLES
! ---------------

! KIDIA, : START OF HORIZONTAL LOOP 
! KFDIA  : END OF HORIZONTAL LOOP     
! KLON   : HORIZONTAL DIMENSION
! KTDIA : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL).
! KLEV  : VERTICAL DIMENSION
! PDELP  : LAYER THICKNESS IN PRESSURE UNITS.
! PAPHI  : GEOPOTENTIAL ON HALF-LEVELS.
! PVAR   : INPUT VARIABLE ON FULL LEVEL
! PVARW  : VERTICAL SPEED OF VARIABLE PVAR ON FULL LEVEL (positive from top to bottom)


! ---------------
! OUTPUT VARIABLE
! ---------------

! PFVAR  : FLUX OF VARIABLE PVAR ON HALF LEVEL (Positive from top to bottom)

! ========================================================

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMPHY0   , ONLY : YRPHY0
USE YOMPHY2   , ONLY : YRPHY2
USE YOMCST    , ONLY : RG


IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)     :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)     :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)     :: KLON 
INTEGER(KIND=JPIM), INTENT(IN)    :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN)     :: KLEV 
REAL(KIND=JPRB)   ,INTENT(IN)     :: PVAR (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)     :: PVARW(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)     :: PDELP(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)     :: PAPHI(KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)    :: PFVAR(KLON,0:KLEV)
REAL(KIND=JPRB),   INTENT(OUT)   :: PSTACK (KLON, KPSTSZ)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSTACK (KLON, KKSTSZ)
INTEGER(KIND=JPIM),INTENT(IN)    :: KPSTSZ, KKSTSZ, KPSTPT, KKSTPT
 

REAL(KIND=JPRB) :: ZP1, ZEPS

#include "abor1.intfb.h"



INTEGER(KIND=JPIM) :: JLEV, JLON
REAL(KIND=JPRB) :: ZLN_NEGLIG,ZUSCFL
INTEGER(KIND=JPIM) :: IPSTPT_ZDPSG

INTEGER(KIND=JPIM) :: IPSTPT_ZALTIH

INTEGER(KIND=JPIM) :: IPSTPT_ZFDN

INTEGER(KIND=JPIM) :: IPSTPT_ZFUP

INTEGER(KIND=JPIM) :: IPSTPT_ZDZL

INTEGER(KIND=JPIM) :: IPSTPT_ZDZV

INTEGER(KIND=JPIM) :: IPSTPT_ZP2

INTEGER(KIND=JPIM) :: IPSTPT, IKSTPT


! --------------------------------------------------------

!     CHECK RELIABILITY OF INPUT ARGUMENTS.



! --------------------------------------------------------


IPSTPT = KPSTPT

IKSTPT = KKSTPT

IPSTPT_ZP2 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDZV = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDZL = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZFUP = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZFDN = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZALTIH = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZDPSG = IPSTPT

IPSTPT = IPSTPT + KLEV

IF (IPSTPT > KPSTSZ) CALL ABOR1 

IF (IKSTPT > KKSTSZ) CALL ABOR1 
DO JLEV = 0, KLEV
  DO JLON = KIDIA, KFDIA
    PSTACK (JLON, IPSTPT_ZFDN+JLEV-(0)) = 0.0_JPRB
    PSTACK (JLON, IPSTPT_ZFUP+JLEV-(0)) = 0.0_JPRB
  ENDDO
ENDDO

!- - - - - - - - - - - - - - -
IF (YRPHY2%TSPHY > 0.0_JPRB) THEN
!- - - - - - - - - - - - - - -

! Some intialisation
  DO JLEV = KTDIA, KLEV
    DO JLON = KIDIA, KFDIA
      PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1)) = PDELP(JLON,JLEV) / RG
    ENDDO        
  ENDDO  
  DO JLEV = KTDIA-1, KLEV
    DO JLON = KIDIA, KFDIA
      PSTACK (JLON, IPSTPT_ZALTIH+JLEV-(0)) = PAPHI(JLON,JLEV) / RG 
    ENDDO
  ENDDO
  ZEPS = 1.E-20_JPRB
  ZLN_NEGLIG=LOG(1.0E-2_JPRB)


! First loop : From top to bottom

  DO JLEV = KTDIA, KLEV-1
    DO JLON = KIDIA, KFDIA
      PSTACK (JLON, IPSTPT_ZDZV) = MAX(0._JPRB,-PVARW(JLON,JLEV))*YRPHY2%TSPHY
      PSTACK (JLON, IPSTPT_ZDZL) = PSTACK (JLON, IPSTPT_ZALTIH+JLEV-1-(0)) -&
      &  PSTACK (JLON, IPSTPT_ZALTIH+JLEV-(0))
    ENDDO
    IF(YRPHY0%LADVLIM) THEN
      DO JLON = KIDIA, KFDIA
        ZUSCFL=PSTACK (JLON, IPSTPT_ZDZL)/MAX(ZEPS,PSTACK (JLON, IPSTPT_ZDZV))
        PSTACK (JLON, IPSTPT_ZP2)  = MAX(0._JPRB,MIN(EXP(ZLN_NEGLIG*ZUSCFL),1._JPRB&
        &  - ZUSCFL))
      ENDDO
    ELSE
      DO JLON = KIDIA, KFDIA
        PSTACK (JLON, IPSTPT_ZP2)  = MAX(0._JPRB,1._JPRB - &
        &  PSTACK (JLON, IPSTPT_ZDZL)/MAX(ZEPS,PSTACK (JLON, IPSTPT_ZDZV)))
      ENDDO
    ENDIF
    DO JLON = KIDIA, KFDIA
      ZP1  = MIN(1._JPRB , PSTACK (JLON, IPSTPT_ZDZV)/PSTACK (JLON, IPSTPT_ZDZL)&
      &  )
      PSTACK (JLON, IPSTPT_ZFDN+JLEV-(0)) = ZP1*                             &
      &  PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))*PVAR(JLON,JLEV)/YRPHY2%TSPHY + &
      &  PSTACK (JLON, IPSTPT_ZP2)*PSTACK (JLON, IPSTPT_ZFDN+JLEV-1-(0))
    ENDDO
  ENDDO    

! Second loop : From bottom to top

  DO JLEV = KLEV, KTDIA+1, -1
    DO JLON = KIDIA, KFDIA
      PSTACK (JLON, IPSTPT_ZDZV) = MAX(0._JPRB,PVARW(JLON,JLEV))*YRPHY2%TSPHY
      PSTACK (JLON, IPSTPT_ZDZL) = PSTACK (JLON, IPSTPT_ZALTIH+JLEV-1-(0)) -&
      &  PSTACK (JLON, IPSTPT_ZALTIH+JLEV-(0))
    ENDDO
    IF(YRPHY0%LADVLIM) THEN
      DO JLON = KIDIA, KFDIA
        ZUSCFL=PSTACK (JLON, IPSTPT_ZDZL)/MAX(ZEPS,PSTACK (JLON, IPSTPT_ZDZV))
        PSTACK (JLON, IPSTPT_ZP2)  = MAX(0._JPRB,MIN(EXP(ZLN_NEGLIG*ZUSCFL),1._JPRB&
        &  - ZUSCFL))
      ENDDO
    ELSE
      DO JLON = KIDIA, KFDIA
        PSTACK (JLON, IPSTPT_ZP2)  = MAX(0._JPRB,1._JPRB - &
        &  PSTACK (JLON, IPSTPT_ZDZL)/MAX(ZEPS,PSTACK (JLON, IPSTPT_ZDZV)))
      ENDDO
    ENDIF
    DO JLON = KIDIA, KFDIA
      ZP1 = MIN(1._JPRB , PSTACK (JLON, IPSTPT_ZDZV)/PSTACK (JLON, IPSTPT_ZDZL))
      PSTACK (JLON, IPSTPT_ZFUP+JLEV-1-(0)) = ZP1*                           &
      &  PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))*PVAR(JLON,JLEV)/YRPHY2%TSPHY + &
      &  PSTACK (JLON, IPSTPT_ZP2)*PSTACK (JLON, IPSTPT_ZFUP+JLEV-(0))
    ENDDO
  ENDDO    


!- - - - - - - - - - - - - - - - - - - - - - -
ENDIF  ! End of test on TSPHY > 0.0_JPRB
!- - - - - - - - - - - - - - - - - - - - - - -

!  Final loop construction of net flux

DO JLEV = KTDIA, KLEV-1
  DO JLON = KIDIA, KFDIA
    PFVAR(JLON,JLEV) = PSTACK (JLON, IPSTPT_ZFDN+JLEV-(0)) -&
    &  PSTACK (JLON, IPSTPT_ZFUP+JLEV-(0)) 
  ENDDO
ENDDO   

! --------------------------------------------------------


END SUBROUTINE ACADVEC
