INTERFACE

SUBROUTINE ACMICRO( KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV,&
 
 
 & PNEBST, PT  , PQL , PQI , PTS , PNEIJ , PLSM,&
 
 & PAUTOL, PAUTOI )

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMPHY0   , ONLY : YRPHY0
USE YOMPHY1   , ONLY : YRPHY1
USE YOMPHY2   , ONLY : YRPHY2
USE YOMCST    , ONLY : RTT

INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KGPBLKS,KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KTDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNEBST(KLON,KLEV,KGPBLKS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT    (KLON,KLEV,KGPBLKS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQL   (KLON,KLEV,KGPBLKS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQI   (KLON,KLEV,KGPBLKS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTS   (KLON,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNEIJ (KLON,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLSM  (KLON,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PAUTOL(KLON,KLEV,KGPBLKS) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PAUTOI(KLON,KLEV,KGPBLKS) 

END SUBROUTINE ACMICRO

END INTERFACE
