INTERFACE
SUBROUTINE ACMTENTR ( KIDIA,KFDIA,KGPBLKS,KLON,KTDIA,KLEV,&

&PDELP,PPSIC,PPSIR,PUDAL,PDDAL,PENTR_U,PENTR_D,PDETR_U,PDETR_D,&

&PFCED)

USE PARKIND1, ONLY: JPIM, JPRB

USE YOMCST   , ONLY : RG
USE YOMPHY2  , ONLY : YRPHY2

INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLKS,KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA

REAL(KIND=JPRB), INTENT(IN)    :: PDELP(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PPSIC(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PPSIR(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PUDAL(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PDDAL(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PENTR_U(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PENTR_D(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PDETR_U(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PDETR_D(KLON,KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(OUT)   :: PFCED(KLON,0:KLEV,KGPBLKS)

END SUBROUTINE ACMTENTR

END INTERFACE
