#include "attr.h"
SUBROUTINE ACMTUD ( KIDIA,KFDIA,KLON,KTDIA,KLEV,KTRA,&
!-----------------------------------------------------------------------
! - INPUT  2D .
& PALPH,PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PLH,PR,&
& PDELP,PLNPR,&
& PQ,PQI,PQL,PQLIS,PQSAT,PQW,&
& PRDELP,PCVGQ,PT,PTW,PU,PV,PTKE,PTRA,PEVAPO,&
! - INPUT 1D .
& PGM, PTS, PQS,&
! - OUTPUT 2D .
& PDIFCQ,PDIFCQL,PDIFCQI,PDIFCS,PDIFCTH,&
& PFCCQL,PFCCQI,PSTRCU,PSTRCV,PSTRCTRA,&
& PFHMLTS,PFHEVPP,PFPEVPCL,PFPEVPCN,&
& PFPLCL,PFPLCN,PMF_UP,&
& PNEBC,PQLIC,PTU,PQU,PSU,KNLAB,PENTR_U,PDETR_U,PENTR_D,PDETR_D,&
! - OUTPUT 1D .
& KNND,PCAPE,PALF,PALF_CAPE,PALF_CVGQ,&
! - INPUT/OUTPUT 2D .
& PUDAL,PUDOM,PDDAL,PDDOM, KSTACK, PSTACK, KPSTSZ, KKSTSZ, KPSTPT, KKSTPT)

!**** *ACMTUD * - MASS FLUX PROGNOSTIC UPDRAFT OF THE PCMT CONVECTION SCHEME.

! SUJET.
!     ------

!**   INTERFACE.
!     ----------
!        *CALL* *ACMTUD*
!-----------------------------------------------------------------------
! -   INPUT ARGUMENTS.
!     ----------------

! - PHYSICS DIMENSIONNING PARAMETERS

! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
! KTDIA      : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL).
! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".
! KTRA       : NUMBER OF TRACERS (PASSIVE VARIABLES)

! - PHYSICS VARIABLES (ALPHABETICALLY IN EACH CATEGORY)

! - 2D (0:KLEV) .

! PAPHI      : HALF LEVEL GEOPOTENTIAL
! PAPRS      : HALF LEVEL PRESSURE

! - 2D (1:KLEV) .

! PALPH      : LOG(PAPRS(JLEV)/PAPRSF(JLEV)) (FOR HYDROSTATIC MODEL).
! PAPHIF     : FULL LEVEL GEOPOTENTIAL
! PAPRSF     : FULL LEVEL PRESSURE
! PCP        : CHALEUR MASSIQUE A PRESSION CONSTANTE DE L'AIR.
! PR         : CONSTANTE DE L'AIR HUMIDE.
! PDELP      : PRESSURE DIFFERENCE OVER THE LAYER
! PLNPR      : LOG(PAPRS(JLEV)/PAPRS(JLEV-1)) (POUR L'HYDROSTATIQUE).
! PQ         : MICROPHYSICAL WATER VAPOUR SPECIFIC HUMIDITY
! PQI        : MICROPHYSICAL RESOLVED CLOUD ICE SPECIFIC CONTENTS
! PQL        : MICROPHYSICAL RESOLVED CLOUD LIQUID SPECIFIC CONTENTS
! PQLIS      : MICROPHYSICAL RESOLVED CLOUD WATER SPECIFIC CONTENTSIN THE TIME-STEP
! PQW        : WET BULB SPECIFIC MOISTURE
! PQSAT      : SATURATION SPECIFIC MOISTURE
! PRDELP     : INVERSE DE L'EPAISSEUR EN PRESSION DE LA COUCHE.
! PCVGQ      : CONVERGENCE D'HUMIDITE.
! PT         : TEMPERATURE.
! PTW        : WET BULB TEMPERATURE.
! PU         : U WIND COMPONENT
! PV         : V WIND COMPONENT
! PTRA       : TRACER CONCENTRATION
! PTKE       : TKE
! PEVAPO     : evaporation from previous time step

! - 2D (0:KLEV) .

! - 1D .

! PGM        : FACTEUR D'ECHELLE.
! PTS        : temperature de surface.
! PQS        : vapeur d'eau de surface.

!-----------------------------------------------------------------------

! -   OUTPUT ARGUMENTS
!     ----------------

! - 2D (0:KLEV) .

! PDIFCQ     : WATER VAPOUR CONVECTIVE SPECIFIC MOISTURE FLUX
! PDIFCQI    : ICE WATER CONVECTIVE SPECIFIC MOISTURE FLUX
! PDIFCQL    : LIQUID WATER CONVECTIVE SPECIFIC MOISTURE FLUX
! PDIFCS     : DRY STATIC ENERGY CONVECTIVE FLUX
! PDIFCTH    : THETA CONVECTIVE FLUX
! PFCCQL     : LIQUID CONDENSATION FLUX FROM THE CONVECTIVE UPDRAFT
! PFCCQI     : SOLID CONDENSATION FLUX FROM THE CONVECTIVE UPDRAFT
! PSTRCU     : U-MOMENTUM CONVECTIVE SPECIFIC MOISTURE FLUX
! PSTRCV     : V-MOMENTUM CONVECTIVE SPECIFIC MOISTURE FLUX
! PSTRCTRA   : TRACER CONVECTIVE FLUX
! PFHMLTS    : FLUX DE CHALEUR DU A LA FONTE/GEL.
! PFHEVPP    : FLUX DE CHALEUR DU A L'EVAPORATION DES PRECIPITATIONS.
! PFPEVPCL    : EVAPORATION DES PRECIPITATIONS LIQUIDES.
! PFPEVPCN    : EVAPORATION DES PRECIPITATIONS NEIGEUSES.
! PFPLCL     : PRECIPITATIONS CONVECTIVES SOUS FORME LIQUIDE.
! PFPLCN     : PRECIPITATIONS CONVECTIVES SOUS FORME NEIGE.

! - 2D (1:KLEV) .

! KNLAB  : CONVECTIVE ACTIVITY INDEX (ACTIVE IF EQUAL TO ONE).
! PTU    : TEMPERATURE OF THE CLOUDY ASCENT.
! PQU    : WATER VAPOUR SPECIFIC HUMIDITY OF THE CLOUDY ASCENT.
! PSU    : DRY STATIC ENERGY OF THE CLOUDY ASCENT.
! PNEBC  : CONVECTIVE CLOUDINESS.
! PQLIC  : CONVECTIVE CONDENSATE.
! PENTR_U    : ENTRAINMENT IN UPDRAFT (IN S**-1).
! PDETR_U    : DETRAINMENT FROM UPDRAFT (IN S**-1).
! PENTR_D    : ENTRAINMENT IN DOWNDRAFT (IN S**-1).
! PDETR_D    : DETRAINMENT FROM DOWNDRAFT (IN S**-1).

! - 1D (DIAGNOSTIQUE) .

! KNND   : ZERO WHENEVER A NON PHYSICAL SITUATION OCCURS, ONE OTHERWISE
! PCAPE  : CAPE (CONDITIONAL AVAILABLE POTENTIAL ENERGY).

!-----------------------------------------------------------------------

! -   INPUT/OUTPUT ARGUMENTS
!     ----------------------

! - 2D (0:KLEV) .

! - 2D (1:KLEV) .

! PUDAL    : PROGNOSTIC UPDRAFT MESH FRACTION
! PUDOM    : PROGNOSTIC UPDRAFT RELATIVE VELOCITY

!-----------------------------------------------------------------------

! METHOD.
!     --------

! AUTHOR.
!     -------
! 2011-04-14, J.F. GUEREMY AND J.M. PIRIOU.

! MODIFICATIONS.
!     --------------
! 2013-02-08, J.M. Piriou: protect the LOG in computing ZSIGMA.
! 2013-06-17, J.M. Piriou: LCVNHD NH effects of downdraft on updraft and conversely.
! 2013-06-17, J.M. Piriou: prognostic closure on PALF.
! 2013-07 - G. Bellon  Modifications for MUSC 
! 2014-04-01, J.M. Piriou: LLSINH: SImple NH effect.
! 2014-05   , J.F. Gueremy:
!             * resolution function for closure condition.
!             * CIN threshold for triggering condition.
! 2014-05   , J.F. Gueremy: use ZDQCA instead of ZBCC to compute condensation,
!             to apply the same "ZAUX" reduction in condensation and in transport.
! 2014-05 - D. Saint-Martin : Transport of tracers
! 2014-06 - J.F. Gueremy condensation flux using the same massflux
!             as for the transport flux
! 2014-07-29, Ryad El Khatib: optimize computation time: replace scalars by arrays, etc.
! 2014-09 - J.F. Gueremy new formulation of the resolution function for closure
!             condition and no more smoothing of dw/dp (ZALFAVEC=1.)
! 2015-02 -  I. Beau: Bugfix + some cleanings consistent with cy38 (NCVENTR options)
! 2015-09- J.M Piriou: Phasing of NWP and Climate versions
! 2015-11 - J.F. Gueremy: bugfix concerning the "mass flux" for implicit formulation
! 2015-11 - J.F. Gueremy: explicit transport flux for the dry air potential temperature
!             smoothing of mass flux for the transport fluxes
! 2015-12 - J.M. Piriou: GCVUV factor for momentum transport.
! 2016-06 - J.F. Gueremy et J.M. Piriou: debug sign when using ZFORD for ZAUX.
! 2017-04-21 - J.M. Piriou: use RNEBCX as a maximum value for convective cloudiness.
! 2017-05 - P. Marquet : NCAPEMOD WCAPEMOD RENTRMOD (YOMPHY0) "model-SBCAPE"

!-----------------------------------------------------------------------


USE PARKIND1, ONLY : JPIM, JPRB

USE YOMPHY   , ONLY : YRPHY
USE YOMCST   , ONLY : RATM       ,RG       ,RKAPPA   ,&
  & RD       ,RV       ,RCPD     ,&
  & RCPV     ,RETV     ,RCW      ,RCS      ,RLVTT    ,&
  & RLSTT    ,RTT      ,RALPW    ,RBETW    ,RGAMW    ,&
  & RALPS    ,RBETS    ,RGAMS    ,RALPD    ,RBETD    ,&
  & RGAMD    ,RPI      ,RA       ,&
  & RDT
USE YOMPHY0  , ONLY : YRPHY0
USE YOMPHY2  , ONLY : YRPHY2

USE YOMCT0   , ONLY : LELAM
USE YOMDIM   , ONLY : YRDIM
USE YEMGEO   , ONLY : YREGEO
USE YOMCT3   , ONLY : NSTEP
USE YOMSCM   , ONLY : NFRSCM
USE YOMRIP   , ONLY : YRRIP
USE YOMGEM   , ONLY : YRGEM

IMPLICIT NONE

!     DUMMY ARGUMENTS.

INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTRA

REAL(KIND=JPRB), INTENT(IN)    :: PALPH(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PCP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PLH(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PR(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PLNPR(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQ(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQI(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQLIS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQW(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PCVGQ(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PTW(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PTRA(KLON,KLEV,KTRA)
REAL(KIND=JPRB), INTENT(IN)    :: PTKE(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PEVAPO(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PGM(KLON)
REAL(KIND=JPRB), INTENT(IN)    :: PTS(KLON)
REAL(KIND=JPRB), INTENT(IN)    :: PQS(KLON)

INTEGER(KIND=JPIM), INTENT(INOUT) :: KNLAB(KLON,KLEV)
INTEGER(KIND=JPIM), INTENT(INOUT) :: KNND(KLON)
REAL(KIND=JPRB)   , INTENT(INOUT) :: PALF(KLON)

REAL(KIND=JPRB), INTENT(OUT)   :: PCAPE(KLON)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQ(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCTH(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCU(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCV(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCTRA(KLON,0:KLEV,KTRA)
REAL(KIND=JPRB), INTENT(OUT)   :: PMF_UP(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PTU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PSU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PNEBC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQLIC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFHMLTS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PENTR_U(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PDETR_U(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PENTR_D(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PDETR_D(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCN(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCN(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFHEVPP(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CAPE(KLON)
REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CVGQ(KLON)

REAL(KIND=JPRB), INTENT(INOUT) :: PUDAL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PUDOM(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDAL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDOM(KLON,KLEV)
REAL(KIND=JPRB),   INTENT(OUT)   :: PSTACK (KLON, KPSTSZ)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSTACK (KLON, KKSTSZ)
INTEGER(KIND=JPIM),INTENT(IN)    :: KPSTSZ, KKSTSZ, KPSTPT, KKSTPT

! LOCALS.

INTEGER(KIND=JPIM) :: JTRA
INTEGER(KIND=JPIM) :: ISUM, ITOP, JIT, JLEV, JLON

REAL(KIND=JPRB) :: ZARLII,ZBAS, &
  &ZCPSMD, ZCPVMD, &
  &ZCPVMS, ZCPVMW, ZCPWMD, ZDCP, ZDELQ, &
  &ZDELT, ZDELTA, ZDPSGDT, ZDQW, &
  &ZFER, ZEPS16, &
  &ZESP, ZEW, ZEXP, &
  &ZAUX, ZGDT, ZGDTI, &
  &ZLIQ, ZMIX, ZNBA, ZQW, &
  &ZRVMD, ZZ, ZZVAL, &
  &ZB, ZLHTBW, &
  &ZIDT, ZTPHY, &
  &ZINCRQ,ZCPBW, &
  &ZEPSW,ZWEIGHT,ZEPS_BCCS
INTEGER(KIND=JPIM) :: ILEV
REAL(KIND=JPRB) :: ZBETA1RIO,ZA1RIO,ZBRIO,ZCRIO

REAL(KIND=JPRB) :: ZCPH,ZTNSEC,ZTVNL,ZTVEL

REAL(KIND=JPRB) :: ZFLO_OMEGA,ZDELPF,ZENTR_TUR,ZKDL,ZVVERDEN

REAL(KIND=JPRB) :: ZDELTAP,ZVVERN,ZEPS_TURL,ZKDX,ZPPS,ZMOD_MIN,ZMOD_MAX
REAL(KIND=JPRB) :: ZENTRO,ZEPS_ORG0,ZTLN,ZTLE,ZQSTLE,ZQSTLN,ZSN,ZSE,ZCHIS
REAL(KIND=JPRB) :: ZTVLN,ZTVLE,ZNCHI0,ZDCHI0,ZEPS0,ZEPSVVER,ZCHI0,ZCHI02,ZDLOGM,ZFMDQN
REAL(KIND=JPRB) :: ZFMDSN,ZDPLAB
REAL(KIND=JPRB) :: ZDLON,ZDLONL,ZFORMV
REAL(KIND=JPRB) :: ZTD
REAL(KIND=JPRB) :: ZDIVERG,ZBIN,ZTKLEV
INTEGER(KIND=JPIM) :: ISDELTAP
INTEGER(KIND=JPIM) :: IVVER,IDOMDP,IVVN,IVVX,INUA,ICHIS,IENTR
INTEGER(KIND=JPIM) :: IE0,ICIN
REAL(KIND=JPRB) :: ZEPS3
REAL(KIND=JPRB) :: ZE,ZR,ZTCOND
REAL(KIND=JPRB) :: ZCCHSL,ZCCHSN
REAL(KIND=JPRB) :: ZEPS1,ZEPS4

 ! Reduce Entrainment factor, total.
 ! Reduce Entrainment factor, due to saturation deficit.

REAL(KIND=JPRB) :: ZRT,ZIWGREAT
REAL(KIND=JPRB) :: ZBINTKE,ZBINDEPTH,ZHEIGHT

 ! geopotential at full levels within updraft, under the equipressure hypothesis.
 ! geopotential at full levels within updraft.

REAL(KIND=JPRB) :: ZA,ZA2
REAL(KIND=JPRB) :: ZC
REAL(KIND=JPRB) :: ZD
REAL(KIND=JPRB) :: ZWNEW
REAL(KIND=JPRB) :: ZENTR
REAL(KIND=JPRB) :: ZENTRX
REAL(KIND=JPRB) :: ZRESOL
REAL(KIND=JPRB) :: ZNEBCX
! Dummy setup for CALL FPCINCAPE

#include "abor1.intfb.h"


LOGICAL :: LLTEXC,LLNHACC,LLCOND1,LLCAPECIN
INTEGER(KIND=JPIM) :: IKSTPT_INLABD

INTEGER(KIND=JPIM) :: IKSTPT_IEL

INTEGER(KIND=JPIM) :: IKSTPT_IFCL

INTEGER(KIND=JPIM) :: IKSTPT_ILCL

INTEGER(KIND=JPIM) :: IPSTPT_ZALFX

INTEGER(KIND=JPIM) :: IPSTPT_ZT

INTEGER(KIND=JPIM) :: IPSTPT_ZPREVIOUST

INTEGER(KIND=JPIM) :: IPSTPT_ZALF_CVGQ

INTEGER(KIND=JPIM) :: IPSTPT_ZIBCCS

INTEGER(KIND=JPIM) :: IPSTPT_ZCVGQ

INTEGER(KIND=JPIM) :: IPSTPT_ZDELTA_ARR

INTEGER(KIND=JPIM) :: IPSTPT_ZLOGSIGMA

INTEGER(KIND=JPIM) :: IPSTPT_ZEW_TLN

INTEGER(KIND=JPIM) :: IPSTPT_ZEW_TLE

INTEGER(KIND=JPIM) :: IPSTPT_ZTLN_ARR

INTEGER(KIND=JPIM) :: IPSTPT_ZTLE_ARR

INTEGER(KIND=JPIM) :: IPSTPT_ZALFAVEC

INTEGER(KIND=JPIM) :: IPSTPT_ZLOGRATIO

INTEGER(KIND=JPIM) :: IPSTPT_ZRHOH

INTEGER(KIND=JPIM) :: IPSTPT_ZLISS

INTEGER(KIND=JPIM) :: IPSTPT_ZTMPVAR

INTEGER(KIND=JPIM) :: IPSTPT_ZEVAPO

INTEGER(KIND=JPIM) :: IPSTPT_ZPHIF_U

INTEGER(KIND=JPIM) :: IPSTPT_ZPHIF_U_EQUIP

INTEGER(KIND=JPIM) :: IPSTPT_ZSTRCVD

INTEGER(KIND=JPIM) :: IPSTPT_ZSTRCUD

INTEGER(KIND=JPIM) :: IPSTPT_ZNND

INTEGER(KIND=JPIM) :: IPSTPT_ZI1

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCSD

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCQD

INTEGER(KIND=JPIM) :: IPSTPT_ZBINBUO

INTEGER(KIND=JPIM) :: IPSTPT_ZBINID2

INTEGER(KIND=JPIM) :: IPSTPT_ZBINID

INTEGER(KIND=JPIM) :: IPSTPT_ZRH

INTEGER(KIND=JPIM) :: IPSTPT_ZINTE

INTEGER(KIND=JPIM) :: IPSTPT_ZDENO

INTEGER(KIND=JPIM) :: IPSTPT_ZSATDEF

INTEGER(KIND=JPIM) :: IPSTPT_ZRE_KEDD

INTEGER(KIND=JPIM) :: IPSTPT_ZRE_HEIGHT

INTEGER(KIND=JPIM) :: IPSTPT_ZRE_SATDEF

INTEGER(KIND=JPIM) :: IPSTPT_ZRE

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCS_DD_NOCORR_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCS_UD_NOCORR_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCS_DD_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZRME

INTEGER(KIND=JPIM) :: IPSTPT_ZPLH

INTEGER(KIND=JPIM) :: IPSTPT_ZTARGET_WD

INTEGER(KIND=JPIM) :: IPSTPT_ZINTEG

INTEGER(KIND=JPIM) :: IPSTPT_ZMEAN_D

INTEGER(KIND=JPIM) :: IPSTPT_ZMEAN_U

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_STAU

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_TOT

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_TOT_RAW

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_FRI

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_NHD

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_DYP

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_BUO

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_ADV

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_STAU

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_TOT

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_TOT_RAW

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_FRI

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_NHD

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_DYP

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_BUO

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_ADV

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFF_Z_UD

INTEGER(KIND=JPIM) :: IPSTPT_ZT_DOWN

INTEGER(KIND=JPIM) :: IPSTPT_ZRHO

INTEGER(KIND=JPIM) :: IPSTPT_ZBCC

INTEGER(KIND=JPIM) :: IPSTPT_ZBCC_CD_FULL

INTEGER(KIND=JPIM) :: IPSTPT_ZBCC_C_FULL

INTEGER(KIND=JPIM) :: IPSTPT_ZVMD

INTEGER(KIND=JPIM) :: IPSTPT_ZUMD

INTEGER(KIND=JPIM) :: IPSTPT_ZBCC_C_HALF

INTEGER(KIND=JPIM) :: IPSTPT_ZQDND

INTEGER(KIND=JPIM) :: IPSTPT_ZFORD

INTEGER(KIND=JPIM) :: IPSTPT_ZFORU

INTEGER(KIND=JPIM) :: IPSTPT_ZTN2D

INTEGER(KIND=JPIM) :: IPSTPT_ZSN2D

INTEGER(KIND=JPIM) :: IPSTPT_ZSDND

INTEGER(KIND=JPIM) :: IPSTPT_ZQN2D

INTEGER(KIND=JPIM) :: IPSTPT_ZEPS_ORGD

INTEGER(KIND=JPIM) :: IPSTPT_ZDEL_ORGD

INTEGER(KIND=JPIM) :: IPSTPT_ZBETD

INTEGER(KIND=JPIM) :: IPSTPT_ZTEN

INTEGER(KIND=JPIM) :: IPSTPT_ZTEL

INTEGER(KIND=JPIM) :: IPSTPT_ZS5

INTEGER(KIND=JPIM) :: IPSTPT_ZQU

INTEGER(KIND=JPIM) :: IPSTPT_ZTU

INTEGER(KIND=JPIM) :: IPSTPT_ZSU

INTEGER(KIND=JPIM) :: IKSTPT_ILFC

INTEGER(KIND=JPIM) :: IKSTPT_INLFC

INTEGER(KIND=JPIM) :: IKSTPT_ILEVTEN

INTEGER(KIND=JPIM) :: IKSTPT_IKUO5

INTEGER(KIND=JPIM) :: IKSTPT_IQLIC

INTEGER(KIND=JPIM) :: IKSTPT_IKUO6

INTEGER(KIND=JPIM) :: IKSTPT_IBAC

INTEGER(KIND=JPIM) :: IKSTPT_INIVBAC

INTEGER(KIND=JPIM) :: IKSTPT_INCDN

INTEGER(KIND=JPIM) :: IKSTPT_ICDN

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_KNLAB

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_TUDAL

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_WMAX

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_EPS_TUR

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_EPS_ORG

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAGTRANSP

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAGFRICTION

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_ECART_T

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_ECART_TV

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAGFLO

INTEGER(KIND=JPIM) :: IPSTPT_ZASCENT_BASE

INTEGER(KIND=JPIM) :: IPSTPT_ZVACC

INTEGER(KIND=JPIM) :: IPSTPT_ZDEPTH

INTEGER(KIND=JPIM) :: IPSTPT_ZDELTA_U

INTEGER(KIND=JPIM) :: IPSTPT_ZEPSILON_U

INTEGER(KIND=JPIM) :: IPSTPT_ZEMD_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZENTR_T_LOC

INTEGER(KIND=JPIM) :: IPSTPT_ZFLUXDIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZQBASE

INTEGER(KIND=JPIM) :: IPSTPT_ZTBASE

INTEGER(KIND=JPIM) :: IPSTPT_ZBUOY

INTEGER(KIND=JPIM) :: IPSTPT_ZQDN

INTEGER(KIND=JPIM) :: IPSTPT_ZTAU_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZFDXTAUX

INTEGER(KIND=JPIM) :: IPSTPT_ZTAU

INTEGER(KIND=JPIM) :: IPSTPT_ZS11

INTEGER(KIND=JPIM) :: IPSTPT_ZS12

INTEGER(KIND=JPIM) :: IPSTPT_ZFMDQ

INTEGER(KIND=JPIM) :: IPSTPT_ZFMDS

INTEGER(KIND=JPIM) :: IPSTPT_ZMOD

INTEGER(KIND=JPIM) :: IPSTPT_ZBUO_W_POS

INTEGER(KIND=JPIM) :: IPSTPT_ZVVERDM

INTEGER(KIND=JPIM) :: IPSTPT_ZBUO_W

INTEGER(KIND=JPIM) :: IPSTPT_ZCINL

INTEGER(KIND=JPIM) :: IPSTPT_ZCIN

INTEGER(KIND=JPIM) :: IPSTPT_ZCAPEL

INTEGER(KIND=JPIM) :: IPSTPT_ZRBHS

INTEGER(KIND=JPIM) :: IPSTPT_ZRBBS

INTEGER(KIND=JPIM) :: IPSTPT_ZQBH

INTEGER(KIND=JPIM) :: IPSTPT_ZTBH

INTEGER(KIND=JPIM) :: IPSTPT_ZSIGMA

INTEGER(KIND=JPIM) :: IPSTPT_ZKD

INTEGER(KIND=JPIM) :: IPSTPT_ZDEL_ORG

INTEGER(KIND=JPIM) :: IPSTPT_ZEPS_ORG

INTEGER(KIND=JPIM) :: IPSTPT_ZEPS_TUR

INTEGER(KIND=JPIM) :: IPSTPT_ZCAPE

INTEGER(KIND=JPIM) :: IPSTPT_ZDWNDP

INTEGER(KIND=JPIM) :: IPSTPT_ZVVER

INTEGER(KIND=JPIM) :: IPSTPT_ZQNH

INTEGER(KIND=JPIM) :: IPSTPT_ZTNH

INTEGER(KIND=JPIM) :: IPSTPT_ZLN

INTEGER(KIND=JPIM) :: IPSTPT_ZTB

INTEGER(KIND=JPIM) :: IPSTPT_ZS16

INTEGER(KIND=JPIM) :: IPSTPT_ZS15

INTEGER(KIND=JPIM) :: IPSTPT_ZRVH

INTEGER(KIND=JPIM) :: IPSTPT_ZRBH

INTEGER(KIND=JPIM) :: IPSTPT_ZRBB

INTEGER(KIND=JPIM) :: IPSTPT_ZQB

INTEGER(KIND=JPIM) :: IPSTPT_ZLH

INTEGER(KIND=JPIM) :: IPSTPT_ZLB

INTEGER(KIND=JPIM) :: IPSTPT_ZCP

INTEGER(KIND=JPIM) :: IKSTPT_INBAS

INTEGER(KIND=JPIM) :: IPSTPT_ZSTRCTRAD

INTEGER(KIND=JPIM) :: IPSTPT_ZTRAMD

INTEGER(KIND=JPIM) :: IPSTPT_ZTRAM

INTEGER(KIND=JPIM) :: IPSTPT_ZA15

INTEGER(KIND=JPIM) :: IPSTPT_ZDQCA

INTEGER(KIND=JPIM) :: IPSTPT_ZFORM

INTEGER(KIND=JPIM) :: IPSTPT_ZTBW

INTEGER(KIND=JPIM) :: IPSTPT_ZQBW

INTEGER(KIND=JPIM) :: IPSTPT_ZVM

INTEGER(KIND=JPIM) :: IPSTPT_ZUM

INTEGER(KIND=JPIM) :: IPSTPT_ZTVN

INTEGER(KIND=JPIM) :: IPSTPT_ZTVE

INTEGER(KIND=JPIM) :: IPSTPT_ZSDN

INTEGER(KIND=JPIM) :: IPSTPT_ZRMIX

INTEGER(KIND=JPIM) :: IPSTPT_ZPOID

INTEGER(KIND=JPIM) :: IPSTPT_ZLDN

INTEGER(KIND=JPIM) :: IPSTPT_ZIFRAC

INTEGER(KIND=JPIM) :: IPSTPT_ZDSE

INTEGER(KIND=JPIM) :: IPSTPT_ZBET

INTEGER(KIND=JPIM) :: IPSTPT_ZA14

INTEGER(KIND=JPIM) :: IPSTPT_ZA13

INTEGER(KIND=JPIM) :: IPSTPT_ZTALF_SIN

INTEGER(KIND=JPIM) :: IPSTPT_ZTALF_SCE

INTEGER(KIND=JPIM) :: IPSTPT_ZWD_PLUS_BUO

INTEGER(KIND=JPIM) :: IPSTPT_ZKEDD

INTEGER(KIND=JPIM) :: IPSTPT_ZWD

INTEGER(KIND=JPIM) :: IPSTPT_ZWU

INTEGER(KIND=JPIM) :: IPSTPT, IKSTPT


!-----------------------------------------------------------------------

#include "fcttrm.func.h"
#include "fctdoi.func.h"




IPSTPT = KPSTPT

IKSTPT = KKSTPT

IPSTPT_ZWU = IPSTPT

IPSTPT = IPSTPT + KLEV+1

IPSTPT_ZWD = IPSTPT

IPSTPT = IPSTPT + KLEV+1

IPSTPT_ZKEDD = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZWD_PLUS_BUO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTALF_SCE = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTALF_SIN = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZA13 = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZA14 = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBET = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDSE = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZIFRAC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZLDN = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZPOID = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZRMIX = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZSDN = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTVE = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTVN = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZUM = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZVM = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQBW = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTBW = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZFORM = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZDQCA = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZA15 = IPSTPT

IPSTPT = IPSTPT + (KLEV) * (KTRA)

IPSTPT_ZTRAM = IPSTPT

IPSTPT = IPSTPT + (KLEV) * (KTRA)

IPSTPT_ZTRAMD = IPSTPT

IPSTPT = IPSTPT + (KLEV) * (KTRA)

IPSTPT_ZSTRCTRAD = IPSTPT

IPSTPT = IPSTPT + (KLEV-0+1) * (KTRA)

IKSTPT_INBAS = IKSTPT

IKSTPT = IKSTPT + KLEV

IPSTPT_ZCP = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZLB = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZLH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQB = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRBB = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRBH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRVH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZS15 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZS16 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTB = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZLN = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTNH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQNH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZVVER = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZDWNDP = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZCAPE = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZEPS_TUR = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZEPS_ORG = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDEL_ORG = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZKD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZSIGMA = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZTBH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQBH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRBBS = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRBHS = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZCAPEL = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZCIN = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZCINL = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZBUO_W = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZVVERDM = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBUO_W_POS = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZMOD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZFMDS = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZFMDQ = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZS12 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZS11 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTAU = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZFDXTAUX = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTAU_DIAG = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQDN = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBUOY = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTBASE = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQBASE = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZFLUXDIAG = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZENTR_T_LOC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZEMD_DIAG = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZEPSILON_U = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDELTA_U = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDEPTH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZVACC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZASCENT_BASE = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDIAGFLO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIAG_ECART_TV = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIAG_ECART_T = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIAGFRICTION = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIAGTRANSP = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIAG_EPS_ORG = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIAG_EPS_TUR = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIAG_WMAX = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDIAG_TUDAL = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIAG_KNLAB = IPSTPT

IPSTPT = IPSTPT + KLEV

IKSTPT_ICDN = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_INCDN = IKSTPT

IKSTPT = IKSTPT + KLEV

IKSTPT_INIVBAC = IKSTPT

IKSTPT = IKSTPT + KLEV

IKSTPT_IBAC = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_IKUO6 = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_IQLIC = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_IKUO5 = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_ILEVTEN = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_INLFC = IKSTPT

IKSTPT = IKSTPT + KLEV

IKSTPT_ILFC = IKSTPT

IKSTPT = IKSTPT + 1

IPSTPT_ZSU = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTU = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQU = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZS5 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTEL = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTEN = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZBETD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDEL_ORGD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZEPS_ORGD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQN2D = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZSDND = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZSN2D = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTN2D = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZFORU = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZFORD = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZQDND = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBCC_C_HALF = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZUMD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZVMD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBCC_C_FULL = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBCC_CD_FULL = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBCC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZRHO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZT_DOWN = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIFF_Z_UD = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZTWU_ADV = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWU_BUO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWU_DYP = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWU_NHD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWU_FRI = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWU_TOT_RAW = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWU_TOT = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWU_STAU = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWD_ADV = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWD_BUO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWD_DYP = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWD_NHD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWD_FRI = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWD_TOT_RAW = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWD_TOT = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTWD_STAU = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZMEAN_U = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZMEAN_D = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZINTEG = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTARGET_WD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZPLH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRME = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDIFCS_DD_DIAG = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZDIFCS_UD_NOCORR_DIAG = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZDIFCS_DD_NOCORR_DIAG = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZRE = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZRE_SATDEF = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZRE_HEIGHT = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZRE_KEDD = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZSATDEF = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDENO = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZINTE = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZBINID = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBINID2 = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZBINBUO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDIFCQD = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZDIFCSD = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZI1 = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZNND = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZSTRCUD = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZSTRCVD = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZPHIF_U_EQUIP = IPSTPT

IPSTPT = IPSTPT + KLEV+1

IPSTPT_ZPHIF_U = IPSTPT

IPSTPT = IPSTPT + KLEV+1

IPSTPT_ZEVAPO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTMPVAR = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZLISS = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZRHOH = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZLOGRATIO = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZALFAVEC = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTLE_ARR = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTLN_ARR = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZEW_TLE = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZEW_TLN = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZLOGSIGMA = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDELTA_ARR = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZCVGQ = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZIBCCS = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZALF_CVGQ = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZPREVIOUST = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZT = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZALFX = IPSTPT

IPSTPT = IPSTPT + 1

IKSTPT_ILCL = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_IFCL = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_IEL = IKSTPT

IKSTPT = IKSTPT + 1

IKSTPT_INLABD = IKSTPT

IKSTPT = IKSTPT + KLEV

IF (IPSTPT > KPSTSZ) CALL ABOR1 

IF (IKSTPT > KKSTSZ) CALL ABOR1 
DO JLEV = 1, KLEV+1
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZWU+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV+1
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZWD+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO


LLCAPECIN=.FALSE.
DO JLON=KIDIA,KFDIA
  PSTACK (JLON, IPSTPT_ZPREVIOUST)=PT(JLON,KTDIA)
ENDDO
DO JLEV=KTDIA,KLEV
  DO JLON=KIDIA,KFDIA

    ! Limit T value, so that no instability can be greater than GINSTX Kelvin per level.
    ! This is done in order to prevent temporal instabilities generated by too large time
    ! steps versus vertical resolution, close to orography.
    PSTACK (JLON, IPSTPT_ZT+JLEV-(1))=MIN(PT(JLON,JLEV),&
    &  PSTACK (JLON, IPSTPT_ZPREVIOUST)+YRPHY0%GINSTX)
    PSTACK (JLON, IPSTPT_ZPREVIOUST)=PSTACK (JLON, IPSTPT_ZT+JLEV-(1))

    ! VERTICAL VELOCITY IN M/S COMPUTED FROM VERTICAL VELOCITY IN PA/S.
    PSTACK (JLON, IPSTPT_ZWU+JLEV-(1))=-PUDOM(JLON,JLEV)*PR(JLON,JLEV)*&
    &  PSTACK (JLON, IPSTPT_ZT+JLEV-(1))/(PAPRSF(JLON,JLEV)*RG)
    PSTACK (JLON, IPSTPT_ZWD+JLEV-(1))=-PDDOM(JLON,JLEV)*PR(JLON,JLEV)*&
    &  PSTACK (JLON, IPSTPT_ZT+JLEV-(1))/(PAPRSF(JLON,JLEV)*RG)
  ENDDO
ENDDO

DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZKEDD) = 0._JPRB
ENDDO

DO JLEV=KTDIA,KLEV
  DO JLON=KIDIA,KFDIA
    ! Kinetic energy of the downdraft.
    PSTACK (JLON, IPSTPT_ZKEDD)=PSTACK (JLON, IPSTPT_ZKEDD)+0.5_JPRB*         &
    &  PSTACK (JLON, IPSTPT_ZWD+JLEV-(1))*PSTACK (JLON, IPSTPT_ZWD+JLEV-(1))* &
    & PDELP(JLON,JLEV)/RG
  ENDDO
ENDDO

!     -------------------
! // INITIALISATIONS

IF(YRPHY0%NCVCLOS == 4) THEN
  !
  !-------------------------------------------------
  ! Surface fraction PALF is prognostic.
  ! In input, PUDAL is the result of 3D advection applied to the uniform in the
  ! vertical PALF field from previous time step.
  ! PUDAL is set in output to ZSIGMA*PALF.
  ! PALF is set in output to the new prognostic value of PALF, and will be set
  ! by the caller of present routine ACMTUD in the array PUDAL, in order to be
  ! advected in 3D.
  ! Here PALF is set to the value of the 3D field PUDAL above PBL.
  ! In 1D, as there is no advection, PUDAL is nothing but the uniform value of PALF from previous time
  ! step.
  !-------------------------------------------------
  !
  ILEV=MAX(KTDIA,INT(YRPHY0%GSIGA*REAL(KLEV)))
  DO JLON=KIDIA,KFDIA
    PALF(JLON)=PUDAL(JLON,ILEV)
  ENDDO
ELSE
  !-------------------------------------------------
  ! Surface fraction PALF is diagnostic.
  !-------------------------------------------------
  DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PUDAL(JLON,JLEV) = 0._JPRB
ENDDO
ENDDO

ENDIF
DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PDDAL(JLON,JLEV) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZEPS_TUR+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZEPS_ORG+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZEMD_DIAG+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIFCQD+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIFCSD+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZSTRCUD+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZSTRCVD+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZVACC+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

ZENTR=YRPHY0%GCVRE*YRPHY0%TENTR
ZENTRX=YRPHY0%GCVRE*YRPHY0%TENTRX
DO JTRA = 1, KTRA
DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZSTRCTRAD+JLEV-(0)+(KLEV-0+1)*(JTRA-(1))) = 0._JPRB
ENDDO
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZEPSILON_U+JLEV-(1)) = ZENTRX*RG
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDELTA_U+JLEV-(1)) = ZENTRX*RG
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PENTR_U(JLON,JLEV) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PDETR_U(JLON,JLEV) = YRPHY0%GCVENTR_MIN
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PENTR_D(JLON,JLEV) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PDETR_D(JLON,JLEV) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBUOY+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZENTR_T_LOC+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZFLUXDIAG+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV+1
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZPHIF_U+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV+1
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZPHIF_U_EQUIP+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIFF_Z_UD+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZMOD+JLEV-(1)) = YRPHY0%GCVEZ
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZSIGMA+JLEV-(0)) = 1._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZRE+JLEV-(1)) = 1._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZRE_SATDEF+JLEV-(1)) = 1._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZRE_HEIGHT+JLEV-(1)) = 1._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZRE_KEDD+JLEV-(1)) = 1._JPRB
ENDDO
ENDDO

ZTPHY=YRPHY2%TSPHY
DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZLISS+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PMF_UP(JLON,JLEV) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZRHOH+JLEV-(0)) = 1.0_JPRB
ENDDO
ENDDO


! Compute convective response time as a function of nominal resolution.
! REFLCAPE should in this case be independant of resolution.

IF(YRPHY0%REFLCAPE > 0._JPRB) THEN
  ! Climate tunings.
  IF (LELAM) THEN
    ZDLON=(2.0_JPRB*RPI*RA)/MIN(YREGEO%EDELX, YREGEO%EDELY)
  ELSE
    ZDLON=REAL(YRDIM%NDLON)
  ENDIF
  DO JLON=KIDIA,KFDIA
    ZDLONL=MIN(ZDLON*PGM(JLON),950._JPRB)
    PSTACK (JLON, IPSTPT_ZFDXTAUX)=YRPHY0%TEQC*1.E3_JPRB*(2.234E-4_JPRB*ZDLONL**&
    & 2 -0.425_JPRB*ZDLONL+252.5_JPRB)
    PSTACK (JLON, IPSTPT_ZALFX)=YRPHY0%ALFX
  ENDDO
ELSE
  ! NWP tunings.
  DO JLON=KIDIA,KFDIA
    PSTACK (JLON, IPSTPT_ZFDXTAUX)=ABS(YRPHY0%REFLCAPE)*PGM(JLON)
    ! REDLXN is the mean model mesh in meter.
    ! ZRESOL is the local model resolution in 1/meter.
    ZRESOL=PGM(JLON)/YRGEM%RDELXN
    ! ZALFX varies from ALFX_LR to ALFX_HR, as resolution goes from GCVRESN to GCVRESX.
    PSTACK (JLON, IPSTPT_ZALFX)=MAX(YRPHY0%ALFX_LR,MIN(YRPHY0%ALFX_HR,YRPHY0%  &
    & ALFX_LR+(ZRESOL-YRPHY0%GCVRESN) /(YRPHY0%GCVRESX-YRPHY0%GCVRESN)*(YRPHY0%&
    & ALFX_HR-YRPHY0%ALFX_LR)))
  ENDDO
ENDIF

!--------------------------------------------------

!     SETTING ALL FLUXES TO ZERO (FOR THE CASE WITHOUT CONVECTION)
! THIS IS DONE NOW BY INITAPLPAR

!     ---------------------------
! // AUXILIARY CONSTANTS.

ZEPS0=1.E-12_JPRB
ZEPS3=1.E-01_JPRB
ZEPSVVER=1._JPRB
ZEPS16=1.E-06_JPRB
ZEPS1=1.E-10_JPRB
ZEPS4=1.E-05_JPRB
ZEPSW=0.01_JPRB
ZEPS_BCCS=2.8E-05_JPRB ! Drizzle threshold in mm/s.
ZNEBCX=MIN(1._JPRB-ZEPS0,YRPHY0%RNEBCX)


! UPDRAFT INIT
DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZFORM+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZFORU+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDQCA+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZVVERDM+JLEV-(1)) = PUDOM(JLON,JLEV)
ENDDO
ENDDO


! DOWNDRAFT INIT
DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZFORD+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBETD+JLEV-(1)) = 1._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDEL_ORGD+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZEPS_ORGD+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZQDND+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZQN2D+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZSN2D+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZTN2D+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZSDND+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZUMD+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZVMD+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JTRA = 1, KTRA
DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZTRAMD+JLEV-(1)+(KLEV)*(JTRA-(1))) = 0._JPRB
ENDDO
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
KSTACK (JLON, IKSTPT_INLABD+JLEV-(1)) = 0
ENDDO
ENDDO


ZARLII=0.004_JPRB
ZRVMD=RV-RD
ZCPVMD=RCPV-RCPD
ZCPVMW=RCPV-RCW
ZCPVMS=RCPV-RCS
ZCPWMD=RCW-RCPD
ZCPSMD=RCS-RCPD

ZIDT=1.0_JPRB/ZTPHY
ZGDT=RG*ZTPHY
ZGDTI=1.0_JPRB/ZGDT

ZCCHSL=RCW-RCPD
ZCCHSN=RCS-RCPD

ZKDX=YRPHY0%RKDN*ZENTRX/ZENTR
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDEPTH) = 0._JPRB
ENDDO

DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZASCENT_BASE) = 100000._JPRB
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAGFLO+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAG_ECART_TV+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAG_ECART_T+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAGFRICTION+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAGTRANSP+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAG_EPS_ORG+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAG_EPS_TUR+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAG_WMAX) = 0._JPRB
ENDDO

PSTACK (1, IPSTPT_ZDIAG_TUDAL)=0._JPRB
DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIAG_KNLAB+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBCC+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBCC_C_HALF+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBCC_C_FULL+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBCC_CD_FULL+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO


DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PFHMLTS(JLON,JLEV) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PFHEVPP(JLON,JLEV) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIFCS_DD_DIAG+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIFCS_UD_NOCORR_DIAG+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 0, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDIFCS_DD_NOCORR_DIAG+JLEV-(0)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBUO_W+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBUO_W_POS+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

LLTEXC=YRPHY0%GCVTEXC /= 0._JPRB
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZSATDEF) = 0._JPRB
ENDDO

DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZRH) = 0._JPRB
ENDDO

DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZDENO) = 0._JPRB
ENDDO

DO JLEV = 1, KLEV
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBINBUO+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO


ZMOD_MIN=YRPHY0%GCVEZ
ZMOD_MAX=1.0_JPRB
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZCVGQ) = 0._JPRB
ENDDO

DO JLEV=KTDIA,KLEV
!DEC$ VECTOR ALWAYS
  DO JLON=KIDIA,KFDIA

    ! DIAGNOSTIC OF MAXIMUM VERTICAL VELOCITY IN THE COLUMN.
    PSTACK (JLON, IPSTPT_ZDIAG_WMAX)=MAX(PSTACK (JLON, IPSTPT_ZDIAG_WMAX), &
    & PSTACK (JLON, IPSTPT_ZWU+JLEV-(1)))

    ! CONVECTIVE CLOUD DEPTH:
    ! CUMULATE DEPTH OF LAYERS WHERE VERTICAL VELOCITY IS GREATER THAN A GIVEN THRESHOLD.
    PSTACK (JLON, IPSTPT_ZBINID+JLEV-(1))=MAX(0._JPRB,SIGN(1._JPRB,&
    &  PSTACK (JLON, IPSTPT_ZWU+JLEV-(1))-YRPHY0%GTDCL))
    PSTACK (JLON, IPSTPT_ZDEPTH)=PSTACK (JLON, IPSTPT_ZDEPTH)+(PAPHI(JLON,JLEV-1&
    &  )-PAPHI(JLON,JLEV))/RG*PSTACK (JLON, IPSTPT_ZBINID+JLEV-(1))

    ! ZASCENT_BASE: height (in m above sea level) of the lowest level where w_updraft > 10 m/s.
    ZIWGREAT=MAX(0._JPRB,SIGN(1._JPRB,PSTACK (JLON, IPSTPT_ZWU+JLEV-(1))-10.0_JPRB&
    & ))
    PSTACK (JLON, IPSTPT_ZASCENT_BASE)=PSTACK (JLON, IPSTPT_ZASCENT_BASE)*(1._JPRB&
    &  -ZIWGREAT)+PAPHI(JLON,JLEV)/RG*ZIWGREAT

    ! ZMOD: MODULATES ENTRAINMENT WITH Z.
    ZPPS=PAPRS(JLON,JLEV)/PAPRS(JLON,KLEV)
    PSTACK (JLON, IPSTPT_ZMOD+JLEV-(1))=MAX(ZMOD_MIN,MIN(ZMOD_MAX,ZMOD_MIN+(           &
    & ZMOD_MAX-ZMOD_MIN) *MAX(0._JPRB,MIN(1._JPRB,(ZPPS-0.35_JPRB)/(0.85_JPRB-0.35_JPRB&
    & )))))

    ! DENSITY.
    PSTACK (JLON, IPSTPT_ZRHO+JLEV-(1))=PAPRSF(JLON,JLEV)/(PR(JLON,JLEV)*&
    &  PSTACK (JLON, IPSTPT_ZT+JLEV-(1)))
    PSTACK (JLON, IPSTPT_ZRHOH+JLEV-1-(0)) = 0.5_JPRB*(                         &
    &  PSTACK (JLON, IPSTPT_ZRHO+JLEV-1-(1))+PSTACK (JLON, IPSTPT_ZRHO+JLEV-(1))&
    &  )

    ! SATURATION DEFICIT.
    PSTACK (JLON, IPSTPT_ZINTE)=PDELP(JLON,JLEV)/RG *MAX(0._JPRB,SIGN(1._JPRB,-(&
    & PAPHIF(JLON,JLEV)-PAPHI(JLON,KLEV)-2500._JPRB*RG) *(PAPHIF(JLON,JLEV)-    &
    & PAPHI(JLON,KLEV)-4500._JPRB*RG)))
    PSTACK (JLON, IPSTPT_ZSATDEF)=PSTACK (JLON, IPSTPT_ZSATDEF)+(PQSAT(JLON,JLEV&
    &  )-PQ(JLON,JLEV))*PSTACK (JLON, IPSTPT_ZINTE)
    PSTACK (JLON, IPSTPT_ZRH)=PSTACK (JLON, IPSTPT_ZRH)+PQ(JLON,JLEV)/PQSAT(JLON, &
    & JLEV)*PSTACK (JLON, IPSTPT_ZINTE)
    PSTACK (JLON, IPSTPT_ZDENO)=PSTACK (JLON, IPSTPT_ZDENO)+&
    &  PSTACK (JLON, IPSTPT_ZINTE)

    ! HUMIDITY CONVERGENCE INTEGRATED VERTICALLY OVER CONVECTIVE LEVELS.
    PSTACK (JLON, IPSTPT_ZCVGQ)=PSTACK (JLON, IPSTPT_ZCVGQ)+MIN(YRPHY0%GCVGQX,  &
    & PCVGQ(JLON,JLEV)) *PSTACK (JLON, IPSTPT_ZBINID+JLEV-(1))*PDELP(JLON,JLEV)/&
    &  RG

    PQLIC (JLON,JLEV) = PSTACK (JLON, IPSTPT_ZCVGQ)

  ENDDO
ENDDO


END SUBROUTINE
