INTERFACE

SUBROUTINE ACMTDDD( KIDIA,KFDIA,KGPBLKS,KLON,KTDIA,KLEV,KTRA,&

&KNCDN,KNLAB,&
&PALPH,PAPHIF,PAPRS,PAPRSF,&
&PDELP,PLH,PLNPR,PQ,PQLIC,PQLIS,&
&PQSAT,PQW,PR,PT,PTW,&
&PU,PV,PTRA,&

&KLEVTEN,&

&PBET,PDELA,PEPSI,PFORM,PQDN,&
&PQN2,PSDN,PSN2,PTN2,PUM,PVM,PTRAM,&
&PBCC_CD_FULL,&

&KNLABD)

USE PARKIND1, ONLY : JPIM, JPRB

USE YOMPHY   , ONLY : YRPHY
USE YOMCST   , ONLY : RG       ,RD       ,RV       ,RCPD     ,&
            &RCPV     ,RETV     ,RCW      ,RCS      ,RLVTT    ,&
            &RLSTT    ,RTT      ,RALPW    ,RBETW    ,RGAMW    ,&
            &RALPS    ,RBETS    ,RGAMS    ,RALPD    ,RBETD    ,&
            &RGAMD
USE YOMPHY0  , ONLY : YRPHY0

INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLKS,KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTRA

INTEGER(KIND=JPIM), INTENT(IN) :: KNCDN(KLON,KLEV,KGPBLKS)
INTEGER(KIND=JPIM), INTENT(IN) :: KNLAB(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PALPH(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PAPHIF(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PAPRS(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PAPRSF(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PDELP(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PLH(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PLNPR(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PQ(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PQLIC(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PQLIS(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PQSAT(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PQW(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PR(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PT(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PTW(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PU(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PV(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN) :: PTRA(KLON,KLEV,KTRA,KGPBLKS)
INTEGER(KIND=JPIM), INTENT(IN) :: KLEVTEN(KLON,KGPBLKS)

REAL(KIND=JPRB), INTENT(OUT) :: PBET(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PDELA(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PEPSI(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PFORM(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PQDN(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PQN2(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PSDN(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PSN2(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PTN2(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PUM(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PVM(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT) :: PTRAM(KLON,KLEV,KTRA,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT) :: PBCC_CD_FULL(KLON,KLEV,KGPBLKS)
INTEGER(KIND=JPIM), INTENT(OUT) :: KNLABD(KLON,KLEV,KGPBLKS)

END SUBROUTINE ACMTDDD

END INTERFACE
