#include "attr.h"
SUBROUTINE ACMTUD ( KIDIA,KFDIA,KLON,KTDIA,KLEV,KTRA,&
!-----------------------------------------------------------------------
! - INPUT  2D .
& PAPRSF,&
& PR,&
& PT,&
& PQLIC,&
& PUDOM,&
& KSTACK, &
& PSTACK, &
& KPSTSZ, &
& KKSTSZ, &
& KPSTPT, &
& KKSTPT)

USE PARKIND1, ONLY : JPIM, JPRB

USE YOMCST   , ONLY : RG    
USE YOMPHY0  , ONLY : YRPHY0


IMPLICIT NONE

!     DUMMY ARGUMENTS.

INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTRA

REAL(KIND=JPRB), INTENT(IN)    :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PR(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQLIC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PUDOM(KLON,KLEV)
REAL(KIND=JPRB),   INTENT(OUT)   :: PSTACK (KLON, KPSTSZ)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSTACK (KLON, KKSTSZ)
INTEGER(KIND=JPIM),INTENT(IN)    :: KPSTSZ, KKSTSZ, KPSTPT, KKSTPT

! LOCALS.

INTEGER(KIND=JPIM) :: JLEV, JLON


INTEGER(KIND=JPIM) :: IKSTPT_INLABD

INTEGER(KIND=JPIM) :: IKSTPT_IEL

INTEGER(KIND=JPIM) :: IKSTPT_IFCL

INTEGER(KIND=JPIM) :: IKSTPT_ILCL

INTEGER(KIND=JPIM) :: IPSTPT_ZALFX

INTEGER(KIND=JPIM) :: IPSTPT_ZT

INTEGER(KIND=JPIM) :: IPSTPT_ZPREVIOUST

INTEGER(KIND=JPIM) :: IPSTPT_ZALF_CVGQ

INTEGER(KIND=JPIM) :: IPSTPT_ZIBCCS

INTEGER(KIND=JPIM) :: IPSTPT_ZCVGQ

INTEGER(KIND=JPIM) :: IPSTPT_ZDELTA_ARR

INTEGER(KIND=JPIM) :: IPSTPT_ZLOGSIGMA

INTEGER(KIND=JPIM) :: IPSTPT_ZEW_TLN

INTEGER(KIND=JPIM) :: IPSTPT_ZEW_TLE

INTEGER(KIND=JPIM) :: IPSTPT_ZTLN_ARR

INTEGER(KIND=JPIM) :: IPSTPT_ZTLE_ARR

INTEGER(KIND=JPIM) :: IPSTPT_ZALFAVEC

INTEGER(KIND=JPIM) :: IPSTPT_ZLOGRATIO

INTEGER(KIND=JPIM) :: IPSTPT_ZRHOH

INTEGER(KIND=JPIM) :: IPSTPT_ZLISS

INTEGER(KIND=JPIM) :: IPSTPT_ZTMPVAR

INTEGER(KIND=JPIM) :: IPSTPT_ZEVAPO

INTEGER(KIND=JPIM) :: IPSTPT_ZPHIF_U

INTEGER(KIND=JPIM) :: IPSTPT_ZPHIF_U_EQUIP

INTEGER(KIND=JPIM) :: IPSTPT_ZSTRCVD

INTEGER(KIND=JPIM) :: IPSTPT_ZSTRCUD

INTEGER(KIND=JPIM) :: IPSTPT_ZNND

INTEGER(KIND=JPIM) :: IPSTPT_ZI1

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCSD

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCQD

INTEGER(KIND=JPIM) :: IPSTPT_ZBINBUO

INTEGER(KIND=JPIM) :: IPSTPT_ZBINID2

INTEGER(KIND=JPIM) :: IPSTPT_ZBINID

INTEGER(KIND=JPIM) :: IPSTPT_ZRH

INTEGER(KIND=JPIM) :: IPSTPT_ZINTE

INTEGER(KIND=JPIM) :: IPSTPT_ZDENO

INTEGER(KIND=JPIM) :: IPSTPT_ZSATDEF

INTEGER(KIND=JPIM) :: IPSTPT_ZRE_KEDD

INTEGER(KIND=JPIM) :: IPSTPT_ZRE_HEIGHT

INTEGER(KIND=JPIM) :: IPSTPT_ZRE_SATDEF

INTEGER(KIND=JPIM) :: IPSTPT_ZRE

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCS_DD_NOCORR_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCS_UD_NOCORR_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFCS_DD_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZRME

INTEGER(KIND=JPIM) :: IPSTPT_ZPLH

INTEGER(KIND=JPIM) :: IPSTPT_ZTARGET_WD

INTEGER(KIND=JPIM) :: IPSTPT_ZINTEG

INTEGER(KIND=JPIM) :: IPSTPT_ZMEAN_D

INTEGER(KIND=JPIM) :: IPSTPT_ZMEAN_U

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_STAU

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_TOT

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_TOT_RAW

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_FRI

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_NHD

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_DYP

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_BUO

INTEGER(KIND=JPIM) :: IPSTPT_ZTWD_ADV

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_STAU

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_TOT

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_TOT_RAW

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_FRI

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_NHD

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_DYP

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_BUO

INTEGER(KIND=JPIM) :: IPSTPT_ZTWU_ADV

INTEGER(KIND=JPIM) :: IPSTPT_ZDIFF_Z_UD

INTEGER(KIND=JPIM) :: IPSTPT_ZT_DOWN

INTEGER(KIND=JPIM) :: IPSTPT_ZRHO

INTEGER(KIND=JPIM) :: IPSTPT_ZBCC

INTEGER(KIND=JPIM) :: IPSTPT_ZBCC_CD_FULL

INTEGER(KIND=JPIM) :: IPSTPT_ZBCC_C_FULL

INTEGER(KIND=JPIM) :: IPSTPT_ZVMD

INTEGER(KIND=JPIM) :: IPSTPT_ZUMD

INTEGER(KIND=JPIM) :: IPSTPT_ZBCC_C_HALF

INTEGER(KIND=JPIM) :: IPSTPT_ZQDND

INTEGER(KIND=JPIM) :: IPSTPT_ZFORD

INTEGER(KIND=JPIM) :: IPSTPT_ZFORU

INTEGER(KIND=JPIM) :: IPSTPT_ZTN2D

INTEGER(KIND=JPIM) :: IPSTPT_ZSN2D

INTEGER(KIND=JPIM) :: IPSTPT_ZSDND

INTEGER(KIND=JPIM) :: IPSTPT_ZQN2D

INTEGER(KIND=JPIM) :: IPSTPT_ZEPS_ORGD

INTEGER(KIND=JPIM) :: IPSTPT_ZDEL_ORGD

INTEGER(KIND=JPIM) :: IPSTPT_ZBETD

INTEGER(KIND=JPIM) :: IPSTPT_ZTEN

INTEGER(KIND=JPIM) :: IPSTPT_ZTEL

INTEGER(KIND=JPIM) :: IPSTPT_ZS5

INTEGER(KIND=JPIM) :: IPSTPT_ZQU

INTEGER(KIND=JPIM) :: IPSTPT_ZTU

INTEGER(KIND=JPIM) :: IPSTPT_ZSU

INTEGER(KIND=JPIM) :: IKSTPT_ILFC

INTEGER(KIND=JPIM) :: IKSTPT_INLFC

INTEGER(KIND=JPIM) :: IKSTPT_ILEVTEN

INTEGER(KIND=JPIM) :: IKSTPT_IKUO5

INTEGER(KIND=JPIM) :: IKSTPT_IQLIC

INTEGER(KIND=JPIM) :: IKSTPT_IKUO6

INTEGER(KIND=JPIM) :: IKSTPT_IBAC

INTEGER(KIND=JPIM) :: IKSTPT_INIVBAC

INTEGER(KIND=JPIM) :: IKSTPT_INCDN

INTEGER(KIND=JPIM) :: IKSTPT_ICDN

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_KNLAB

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_TUDAL

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_WMAX

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_EPS_TUR

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_EPS_ORG

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAGTRANSP

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAGFRICTION

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_ECART_T

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAG_ECART_TV

INTEGER(KIND=JPIM) :: IPSTPT_ZDIAGFLO

INTEGER(KIND=JPIM) :: IPSTPT_ZASCENT_BASE

INTEGER(KIND=JPIM) :: IPSTPT_ZVACC

INTEGER(KIND=JPIM) :: IPSTPT_ZDEPTH

INTEGER(KIND=JPIM) :: IPSTPT_ZDELTA_U

INTEGER(KIND=JPIM) :: IPSTPT_ZEPSILON_U

INTEGER(KIND=JPIM) :: IPSTPT_ZEMD_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZENTR_T_LOC

INTEGER(KIND=JPIM) :: IPSTPT_ZFLUXDIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZQBASE

INTEGER(KIND=JPIM) :: IPSTPT_ZTBASE

INTEGER(KIND=JPIM) :: IPSTPT_ZBUOY

INTEGER(KIND=JPIM) :: IPSTPT_ZQDN

INTEGER(KIND=JPIM) :: IPSTPT_ZTAU_DIAG

INTEGER(KIND=JPIM) :: IPSTPT_ZFDXTAUX

INTEGER(KIND=JPIM) :: IPSTPT_ZTAU

INTEGER(KIND=JPIM) :: IPSTPT_ZS11

INTEGER(KIND=JPIM) :: IPSTPT_ZS12

INTEGER(KIND=JPIM) :: IPSTPT_ZFMDQ

INTEGER(KIND=JPIM) :: IPSTPT_ZFMDS

INTEGER(KIND=JPIM) :: IPSTPT_ZMOD

INTEGER(KIND=JPIM) :: IPSTPT_ZBUO_W_POS

INTEGER(KIND=JPIM) :: IPSTPT_ZVVERDM

INTEGER(KIND=JPIM) :: IPSTPT_ZBUO_W

INTEGER(KIND=JPIM) :: IPSTPT_ZCINL

INTEGER(KIND=JPIM) :: IPSTPT_ZCIN

INTEGER(KIND=JPIM) :: IPSTPT_ZCAPEL

INTEGER(KIND=JPIM) :: IPSTPT_ZRBHS

INTEGER(KIND=JPIM) :: IPSTPT_ZRBBS

INTEGER(KIND=JPIM) :: IPSTPT_ZQBH

INTEGER(KIND=JPIM) :: IPSTPT_ZTBH

INTEGER(KIND=JPIM) :: IPSTPT_ZSIGMA

INTEGER(KIND=JPIM) :: IPSTPT_ZKD

INTEGER(KIND=JPIM) :: IPSTPT_ZDEL_ORG

INTEGER(KIND=JPIM) :: IPSTPT_ZEPS_ORG

INTEGER(KIND=JPIM) :: IPSTPT_ZEPS_TUR

INTEGER(KIND=JPIM) :: IPSTPT_ZCAPE

INTEGER(KIND=JPIM) :: IPSTPT_ZDWNDP

INTEGER(KIND=JPIM) :: IPSTPT_ZVVER

INTEGER(KIND=JPIM) :: IPSTPT_ZQNH

INTEGER(KIND=JPIM) :: IPSTPT_ZTNH

INTEGER(KIND=JPIM) :: IPSTPT_ZLN

INTEGER(KIND=JPIM) :: IPSTPT_ZTB

INTEGER(KIND=JPIM) :: IPSTPT_ZS16

INTEGER(KIND=JPIM) :: IPSTPT_ZS15

INTEGER(KIND=JPIM) :: IPSTPT_ZRVH

INTEGER(KIND=JPIM) :: IPSTPT_ZRBH

INTEGER(KIND=JPIM) :: IPSTPT_ZRBB

INTEGER(KIND=JPIM) :: IPSTPT_ZQB

INTEGER(KIND=JPIM) :: IPSTPT_ZLH

INTEGER(KIND=JPIM) :: IPSTPT_ZLB

INTEGER(KIND=JPIM) :: IPSTPT_ZCP

INTEGER(KIND=JPIM) :: IKSTPT_INBAS

INTEGER(KIND=JPIM) :: IPSTPT_ZSTRCTRAD

INTEGER(KIND=JPIM) :: IPSTPT_ZTRAMD

INTEGER(KIND=JPIM) :: IPSTPT_ZTRAM

INTEGER(KIND=JPIM) :: IPSTPT_ZA15

INTEGER(KIND=JPIM) :: IPSTPT_ZDQCA

INTEGER(KIND=JPIM) :: IPSTPT_ZFORM

INTEGER(KIND=JPIM) :: IPSTPT_ZTBW

INTEGER(KIND=JPIM) :: IPSTPT_ZQBW

INTEGER(KIND=JPIM) :: IPSTPT_ZVM

INTEGER(KIND=JPIM) :: IPSTPT_ZUM

INTEGER(KIND=JPIM) :: IPSTPT_ZTVN

INTEGER(KIND=JPIM) :: IPSTPT_ZTVE

INTEGER(KIND=JPIM) :: IPSTPT_ZSDN

INTEGER(KIND=JPIM) :: IPSTPT_ZRMIX

INTEGER(KIND=JPIM) :: IPSTPT_ZPOID

INTEGER(KIND=JPIM) :: IPSTPT_ZLDN

INTEGER(KIND=JPIM) :: IPSTPT_ZIFRAC

INTEGER(KIND=JPIM) :: IPSTPT_ZDSE

INTEGER(KIND=JPIM) :: IPSTPT_ZBET

INTEGER(KIND=JPIM) :: IPSTPT_ZA14

INTEGER(KIND=JPIM) :: IPSTPT_ZA13

INTEGER(KIND=JPIM) :: IPSTPT_ZTALF_SIN

INTEGER(KIND=JPIM) :: IPSTPT_ZTALF_SCE

INTEGER(KIND=JPIM) :: IPSTPT_ZWD_PLUS_BUO

INTEGER(KIND=JPIM) :: IPSTPT_ZKEDD

INTEGER(KIND=JPIM) :: IPSTPT_ZWD

INTEGER(KIND=JPIM) :: IPSTPT_ZWU

INTEGER(KIND=JPIM) :: IPSTPT, IKSTPT


IPSTPT = KPSTPT

IKSTPT = KKSTPT

IPSTPT_ZWU = IPSTPT

IPSTPT = IPSTPT + KLEV+1

IPSTPT_ZDIAG_WMAX = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZPREVIOUST = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZT = IPSTPT

IPSTPT = IPSTPT + KLEV

DO JLEV = 1, KLEV+1
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZWU+JLEV-(1)) = 0._JPRB
ENDDO
ENDDO

DO JLON=KIDIA,KFDIA
  PSTACK (JLON, IPSTPT_ZPREVIOUST)=PT(JLON,KTDIA)
ENDDO

DO JLEV=KTDIA,KLEV
  DO JLON=KIDIA,KFDIA
    PSTACK (JLON, IPSTPT_ZT+JLEV-(1))=MIN(PT(JLON,JLEV),&
    &  PSTACK (JLON, IPSTPT_ZPREVIOUST)+YRPHY0%GINSTX)
    PSTACK (JLON, IPSTPT_ZPREVIOUST)=PSTACK (JLON, IPSTPT_ZT+JLEV-(1))

    PSTACK (JLON, IPSTPT_ZWU+JLEV-(1))=-PUDOM(JLON,JLEV)*PR(JLON,JLEV)*&
    &  PSTACK (JLON, IPSTPT_ZT+JLEV-(1))/(PAPRSF(JLON,JLEV)*RG)

  ENDDO
ENDDO

DO JLEV=KTDIA,KLEV
  DO JLON=KIDIA,KFDIA

    PSTACK (JLON, IPSTPT_ZDIAG_WMAX)=MAX(PSTACK (JLON, IPSTPT_ZDIAG_WMAX), &
    & PSTACK (JLON, IPSTPT_ZWU+JLEV-(1)))
    PQLIC (JLON,JLEV) = PSTACK (JLON, IPSTPT_ZDIAG_WMAX)

  ENDDO
ENDDO

END SUBROUTINE
