INTERFACE

SUBROUTINE ACNEBXRS ( KIDIA,KFDIA,KGPBLKS,KLON,KTDIA,KLEV,&
 
 
 & PQ,PQC,PQSAT,&
 
 & PNEB)  

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMPHY   , ONLY : YRPHY
USE YOMPHY0  , ONLY : YRPHY0

INTEGER(KIND=JPIM),INTENT(IN)    :: KGPBLKS,KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KTDIA 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQ(KLON,KLEV,KGPBLKS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQC(KLON,KLEV,KGPBLKS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQSAT(KLON,KLEV,KGPBLKS) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PNEB(KLON,KLEV,KGPBLKS) 

END SUBROUTINE ACNEBXRS

END INTERFACE
