!OPTIONS XOPT(NOEVAL)
SUBROUTINE ACPCMT ( KIDIA,KFDIA,KGPBLKS,KLON,KTDIA,KLEV,KTRA,&
  !-----------------------------------------------------------------------
  ! - INPUT  2D .
  & PALPH,PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PLH,PR,&
  & PDELP,PLNPR,&
  & PQ,PQI,PQL,PRR,PS,PQLIS,PQSAT,PQW,&
  & PRDELP,PCVGQ,PT,PTW,PU,PV,PTKE,PTRA,&
  & PQLCONV, PQICONV , PQRCONV, PQSCONV, &
  ! - INPUT 1D .
  & PGM, PTS, PQS, PNEIJ, PLSM, PVETAF, &
  ! - OUTPUT 2D .
  & PDIFCQ,PDIFCQL,PDIFCQI,PDIFCQLC,PDIFCQIC,PDIFCS,PDIFCTH,&
  & PFCCQL,PFCCQN,PSTRCU,PSTRCV,PSTRCTRA,&
  & PFIMCC,PFPEVPCL,PFPEVPCN,&
  & PFPLCL,PFPLCN,PMF_UP,&
  & PFPFPCL,PFPFPCN,&
  & PFEDQLC, PFEDQIC, PFEDQRC, PFEDQSC,&
  & PFCNEGQLC,PFCNEGQIC,PFCNEGQRC,PFCNEGQSC, &
  & KNLAB,&
  & PNEBC,PQLIC,PTU,PQU,PQC_DET_PCMT,PCSGC, &
  ! - OUTPUT 1D .
  & KNND, PCAPE,PAIPCMT,PALF_CAPE,PALF_CVGQ,&
  ! - INPUT/OUTPUT 2D .
  & PUDAL,PUDOM,PDDAL,PDDOM)

!**** *ACPCMT * - PCMT CONVECTION SCHEME.

! SUJET.
!     ------

!**   INTERFACE.
!     ----------
!        *CALL* *ACPCMT*
!-----------------------------------------------------------------------
! -   INPUT ARGUMENTS.
!     ----------------

! - PHYSICS DIMENSIONNING PARAMETERS

! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
! KTDIA      : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL).
! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".
! KTRA       : NUMBER OF TRACERS (PASSIVE VARIABLES)

! - PHYSICS VARIABLES (ALPHABETICALLY IN EACH CATEGORY)

! - 2D (0:KLEV) .

! PAPHI      : HALF LEVEL GEOPOTENTIAL
! PAPRS      : HALF LEVEL PRESSURE

! - 2D (1:KLEV) .

! PALPH      : LOG(PAPRS(JLEV)/PAPRSF(JLEV)) (FOR HYDROSTATIC MODEL).
! PAPHIF     : FULL LEVEL GEOPOTENTIAL
! PAPRSF     : FULL LEVEL PRESSURE
! PCP        : CHALEUR MASSIQUE A PRESSION CONSTANTE DE L'AIR.
! PR         : CONSTANTE DE L'AIR HUMIDE.
! PDELP      : PRESSURE DIFFERENCE OVER THE LAYER
! PLNPR      : LOG(PAPRS(JLEV)/PAPRS(JLEV-1)) (POUR L'HYDROSTATIQUE).
! PQ         : MICROPHYSICAL WATER VAPOUR SPECIFIC HUMIDITY
! PQI        : MICROPHYSICAL RESOLVED CLOUD ICE SPECIFIC CONTENT
! PQL        : MICROPHYSICAL RESOLVED CLOUD LIQUID SPECIFIC CONTENT
! PRR        : MICROPHYSICAL RESOLVED RAIN LIQUID SPECIFIC CONTENT
! PS         : MICROPHYSICAL RESOLVED RAIN ICE SPECIFIC CONTENT
! PQLIS      : MICROPHYSICAL RESOLVED CLOUD WATER SPECIFIC CONTENT IN THE TIME-STEP
! PQSAT      : SATURATION SPECIFIC MOISTURE
! PQW        : WET BULB SPECIFIC MOISTURE
! PRDELP     : INVERSE DE L'EPAISSEUR EN PRESSION DE LA COUCHE.
! PCVGQ      : CONVERGENCE D'HUMIDITE.
! PT         : TEMPERATURE.
! PTW        : WET BULB TEMPERATURE.
! PU         : U WIND COMPONENT
! PV         : V WIND COMPONENT
! PTKE       : TKE
! PTRA       : TRACER CONCENTRATION

! - 2D (0:KLEV) .

! - 1D .

! PGM        : FACTEUR D'ECHELLE.
! PTS        : SURFACE LAYER TEMPERATURE.
! PQS        : SURFACE LAYER WATER VAPOUR.
! PNEIJ      : FRACTION OF SOIL COVERED BY SNOW.
! PLSM       : LAND/SEA MASK.
! PVETAF     : VERTICAL COORDINATE.

!-----------------------------------------------------------------------

! -   OUTPUT ARGUMENTS
!     ----------------

! - 2D (0:KLEV) .

! PQLCONV    : LIQUID WATER (CONVECTIVE).
! PQICONV    : ICE    WATER (CONVECTIVE).
! PQRCONV    : RAIN   WATER (CONVECTIVE).
! PQSCONV    : SNOW   WATER (CONVECTIVE).
! PDIFCQ     : FLUX CONVECTIF D'HUMIDITE SPECIFIQUE (HORS PLUIE/NEIGE).
! PDIFCQ     : CONVECTIVE FLUX OF SPECIFIC HUMIDITY (NOT RAIN/SNOW).
! PDIFCQI    : FLUX CONVECTIF D'EAU SOLIDE (HORS PLUIE/NEIGE).
! PDIFCQI    : CONVECTIVE FLUX OF SOLID WATER (NOT RAIN/SNOW).
! PDIFCQL    : FLUX CONVECTIF D'EAU LIQUIDE (HORS PLUIE/NEIGE).
! PDIFCQL    : CONVECTIVE FLUX OF LIQUID WATER (NOT RAIN/SNOW).
! PDIFCQLC   : CONVECTIVE TRANSPORT FLUX OF QLC (LIQUID CONVECTIVE).
! PDIFCQIC   : CONVECTIVE TRANSPORT FLUX OF QIC (ICE CONVECTIVE).
! PDIFCS     : DRY STATIC ENERGY CONVECTIVE FLUX
! PDIFCTH    : THETA CONVECTIVE FLUX
! PFCCQL     : LIQUID CONDENSATION FLUX FROM THE CONVECTIVE UPDRAFT
! PFCCQN     : SOLID CONDENSATION FLUX FROM THE CONVECTIVE UPDRAFT
! PSTRCU     : U-MOMENTUM CONVECTIVE SPECIFIC MOISTURE FLUX
! PSTRCV     : V-MOMENTUM CONVECTIVE SPECIFIC MOISTURE FLUX
! PSTRCTRA   : TRACER CONVECTIVE FLUX
! PFHMLTS    : FLUX DE CHALEUR DU A LA FONTE/GEL.
! PFPEVPCL    : EVAPORATION DES PRECIPITATIONS LIQUIDES.
! PFPEVPCN    : EVAPORATION DES PRECIPITATIONS NEIGEUSES.
! PFPLCL     : PRECIPITATIONS CONVECTIVES SOUS FORME LIQUIDE.
! PFPLCN     : PRECIPITATIONS CONVECTIVES SOUS FORME NEIGE.
! PFPFPCL    : FLUX OF CONVECTIVE PRECIPITATION : THE GENERATION TERM.
! PFPFPCN    : FLUX OF CONVECTIVE PRECIPITATION : THE GENERATION TERM.

! - 2D (1:KLEV) .

! PNEBC  : CONVECTIVE CLOUDINESS.
! PQLIC  : CONVECTIVE CONDENSATE.
! PTU    : TEMPERATURE OF THE CLOUDY ASCENT.
! PQU    : WATER VAPOUR SPECIFIC HUMIDITY OF THE CLOUDY ASCENT.
! PQC_DET_PCMT : CLOUD CONDENSATE (QL+QI) DETRAINED BY PCMT CONVECTION.
! KNLAB  : CONVECTIVE ACTIVITY INDEX (ACTIVE IF EQUAL TO ONE).

! - 1D (DIAGNOSTIQUE) .

! KNND   : ZERO WHENEVER A NON PHYSICAL SITUATION OCCURS, ONE OTHERWISE
! PCAPE  : CAPE (CONDITIONAL AVAILABLE POTENTIAL ENERGY).
! PAIPCMT  : ACTIVITY INDEX OF PCMT: 1. IF PCMT IS ACTIVE, 0. ELSE CASE.

!-----------------------------------------------------------------------

! -   INPUT/OUTPUT ARGUMENTS
!     ----------------------

! - 2D (0:KLEV) .

! - 2D (1:KLEV) .

! PUDAL    : PROGNOSTIC UPDRAFT MESH FRACTION
! PUDOM    : PROGNOSTIC UPDRAFT RELATIVE VELOCITY
! PDDAL    : PROGNOSTIC DOWNDRAFT MESH FRACTION
! PDDOM    : PROGNOSTIC DOWNDRAFT RELATIVE VELOCITY

!-----------------------------------------------------------------------

! METHOD.
!     --------

! AUTHOR.
!     -------
! 2011-12-12, J.M. PIRIOU AND J.F. GUEREMY.

! MODIFICATIONS.
!     --------------
! 2014-04---, D. SAINT-MARTIN : tracer transport.
! 2015-02---, I. BEAU: bugfix (argument PDDOM)
! 2015-09---, J.M PIRIOU: phasing of NWP and CLimate versions
! 2015-11---, J.F. Gueremy: explicit transport flux for the dry air potential temperature
! 2017-06---, J.M. Piriou: replace NTPLUI by KTDIA.

!-----------------------------------------------------------------------


USE PARKIND1, ONLY : JPIM, JPRB

USE YOMCST   , ONLY : RG, RCPD, RCS, RCW, RALPD, RALPS,RALPW,RBETD,RBETS, &
  & RBETW,RCPV,RDT,RETV,RGAMD,RGAMS,RGAMW,RLSTT,RLVTT,RTT,RV
USE YOMPHY0  , ONLY : YRPHY0
USE YOMPHY2  , ONLY : YRPHY2

USE YOMPHY   , ONLY : YRPHY
USE YOMSCM   , ONLY : NFRSCM
USE YOMCT3   , ONLY : NSTEP

IMPLICIT NONE

!     DUMMY ARGUMENTS.

INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLKS,KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTRA

REAL(KIND=JPRB), INTENT(IN)    :: PALPH(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHI(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHIF(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRS(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRSF(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PCP(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PLH(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PR(KLON,KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PDELP(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PLNPR(KLON,KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PQ(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQI(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQL(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PS(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PRR(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQLIS(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQSAT(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQW(KLON,KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PRDELP(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PCVGQ(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PT(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PTW(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PU(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PV(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PTKE(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PTRA(KLON, KLEV, KTRA,KGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PQLCONV(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQICONV(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQRCONV(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQSCONV(KLON,KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PGM(KLON,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PTS(KLON,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQS(KLON,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PNEIJ(KLON,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PLSM(KLON,KGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PVETAF(KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQ(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQL(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQI(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQLC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQIC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCS(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCTH(KLON,0:KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQL(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQN(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCU(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCV(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PMF_UP(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCTRA(KLON, 0:KLEV, KTRA,KGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFIMCC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCL(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCN(KLON,0:KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCL(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCN(KLON,0:KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFPFPCL(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPFPCN(KLON,0:KLEV,KGPBLKS)

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQLC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQIC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQRC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQSC(KLON,0:KLEV,KGPBLKS)

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQLC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQIC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQRC(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQSC(KLON,0:KLEV,KGPBLKS)

INTEGER(KIND=JPIM), INTENT(INOUT) :: KNLAB(KLON,KLEV,KGPBLKS)
INTEGER(KIND=JPIM), INTENT(INOUT) :: KNND(KLON,KGPBLKS)

REAL(KIND=JPRB), INTENT(OUT)   :: PNEBC(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PQLIC(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PTU(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PQU(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PQC_DET_PCMT(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PCSGC(KLON,KLEV,KGPBLKS)

REAL(KIND=JPRB), INTENT(OUT)   :: PCAPE(KLON,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PAIPCMT(KLON,KGPBLKS)

REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CAPE(KLON,KGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CVGQ(KLON,KGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT) :: PUDAL(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT) :: PUDOM(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDAL(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDOM(KLON,KLEV,KGPBLKS)

! LOCALS.
REAL(KIND=JPRB) :: ZEROV(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB)   :: ZTCVIM
REAL(KIND=JPRB)   :: ZICE
REAL(KIND=JPRB)   :: ZQRC   (KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB)   :: ZDDW(KLON,KLEV,KGPBLKS)     ! downdraft vertical velocity
REAL(KIND=JPRB)   :: ZUDQC  (KLON,KLEV,KGPBLKS)
! ZENTR_U    : ENTRAINEMENT DANS L'UPDRAFT.
! ZDETR_U    : DETRAINEMENT DE L'UPDRAFT.
! ZENTR_D    : ENTRAINEMENT DANS LE DOWNDRAFT.
! ZDETR_D    : DETRAINEMENT DU DOWNDRAFT.
REAL(KIND=JPRB) :: ZENTR_U(KLON,KLEV,KGPBLKS),ZDETR_U(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB) :: ZDETR_U_RS(KLON,KLEV,KGPBLKS),ZDETR_D_RS(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB) :: ZENTR_D(KLON,KLEV,KGPBLKS),ZDETR_D(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB) :: ZFCCQLTMP(KLON,0:KLEV,KGPBLKS)
REAL(KIND=JPRB)   :: ZQSC   (KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB)   :: ZQIC   (KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB)   :: ZQLCONVPREC
REAL(KIND=JPRB)   :: ZUDW(KLON,KLEV,KGPBLKS)     ! updraft vertical velocity
REAL(KIND=JPRB)   :: ZQLC   (KLON,KLEV,KGPBLKS)
INTEGER(KIND=JPIM) :: JLEV,JBLK,JLON,INEBC,IQLIC,IQLIC_MICRO,JTRA
REAL(KIND=JPRB)   :: ZW_COMPENS(KLON,KLEV,KGPBLKS)     ! compensating vertical velocity due to the updraft and downdraft
REAL(KIND=JPRB)   :: ZW_CONV(KLON,KLEV,KGPBLKS)     ! vertical velocity for cloud transport
REAL(KIND=JPRB) :: ZFCCQNTMP(KLON,0:KLEV,KGPBLKS)
! ZFHEVPPC   : FLUX DE CHALEUR DU A L'EVAPORATION DES PREC. CONVECTIVES.
! ZFHMLTSC   : FLUX DE CHALEUR DU A LA FONTE/GEL DES PREC. CONVECTIVES.
REAL(KIND=JPRB) :: ZFHEVPPC(KLON,0:KLEV,KGPBLKS),ZFHMLTSC(KLON,0:KLEV,KGPBLKS)
! ZQLIC_MICRO: convective condensate, to be used in microphysics (evaporation, etc).
! ZNEBC_MICRO: convective cloudiness, to be used in microphysics (evaporation, etc).
REAL(KIND=JPRB) :: ZQLIC_MICRO(KLON,KLEV,KGPBLKS),ZNEBC_MICRO(KLON,KLEV,KGPBLKS),ZDAL(KLON,KGPBLKS)
REAL(KIND=JPRB) :: ZQLCED(KLON,KLEV,KGPBLKS),ZQICED(KLON,KLEV,KGPBLKS)
REAL(KIND=JPRB) :: ZQ_COND_XR96(KLON,KLEV,KGPBLKS) ! QLC+QIC+QRC+QSC, FOR USE IN THE XU-RANDALL CLOUDINESS.
REAL(KIND=JPRB) :: ZCCHSL,ZCCHSN,ZEPS
!REAL(KIND=JPRB) :: ZMAX(KLON)
REAL(KIND=JPRB) :: ZDEPTH(KLON,KGPBLKS)
REAL(KIND=JPRB) :: ZTMPVAR(KLON,KLEV,KGPBLKS)

REAL(KIND=JPRB) :: ZTMIC(KLON,KLEV,KGPBLKS) ! Temperature for microphysics
REAL(KIND=JPRB) :: ZQMIC(KLON,KLEV,KGPBLKS) ! Specific moisture for microphysics
REAL(KIND=JPRB) :: ZEVAPO(KLON,KLEV,KGPBLKS) ! Evaporation from previous time step.
REAL(KIND=JPRB) :: ZSU(KLON,KLEV,KGPBLKS) ! Energie statique seche de l'updraft.
REAL(KIND=JPRB) :: ZALF(KLON,KGPBLKS) ! Prognostic active surface fraction.
REAL(KIND=JPRB) :: ZFRACP,ZTH

LOGICAL         :: LLADJCLD

#include "acadvec.intfb.h"
#include "acmtentr.intfb.h"
#include "acmtud.intfb.h"
#include "acpluiz.intfb.h"
#include "acnebxrs.intfb.h"
#include "fcttrm.func.h"
#include "fctdoi.func.h"



ZEPS=1.E-12_JPRB
ZCCHSL=RCW-RCPD
ZCCHSN=RCS-RCPD
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 0, KLEV

PFIMCC(JLON,JLEV,JBLK)= 0._JPRB

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA

ZDAL(JLON,JBLK)= 0._JPRB

ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

PQC_DET_PCMT(JLON,JLEV,JBLK)= 0._JPRB

ENDDO
ENDDO
ENDDO



!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

ZEVAPO(JLON,JLEV,JBLK)= 0._JPRB

ENDDO
ENDDO
ENDDO


IF(YRPHY0%LCVNHD) THEN
  ! Evaporation from previous time step is got from the PDDAL buffer.
  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  DO JLEV = KTDIA, KLEV
  
  ZEVAPO(JLON,JLEV,JBLK)=PDDAL(JLON,JLEV,JBLK)
  
  ENDDO
  ENDDO
  ENDDO

ENDIF

! UDPDRAFT.
CALL ACMTUD ( KIDIA,KFDIA,KGPBLKS,KLON,KTDIA,KLEV,KTRA,&
  & PALPH, PAPHI, PAPHIF, PAPRS, PAPRSF, PCP,PLH, PR,&
  & PDELP, PLNPR,&
  & PQ, PQI, PQL, PQLIS, PQSAT, PQW,&
  & PRDELP, PCVGQ,PT, PTW, PU, PV, PTKE, PTRA,ZEVAPO, &
  & PGM,PTS,PQS,&
  & PDIFCQ, PDIFCQL, PDIFCQI, PDIFCS, PDIFCTH,&
  & PFCCQL, PFCCQN, PSTRCU, PSTRCV, PSTRCTRA,&
  & ZFHMLTSC,ZFHEVPPC,PFPEVPCL,PFPEVPCN,&
  & PFPLCL,PFPLCN,PMF_UP,&
  & PNEBC,PQLIC,PTU,PQU,ZSU,KNLAB,ZENTR_U,ZDETR_U,ZENTR_D,ZDETR_D,&
  & KNND,PCAPE, ZALF, PALF_CAPE, PALF_CVGQ,&
  & PUDAL,PUDOM,PDDAL,PDDOM)

IF(YRPHY0%NCVQLI == 2) THEN
  ! Radiative condensates and cloudiness, due to convection, computed as ql+qi+qr+qs.
  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  DO JLEV = KTDIA, KLEV
    
      PQLIC(JLON,JLEV,JBLK)=PQLCONV(JLON,JLEV,JBLK)+PQICONV(JLON,JLEV,JBLK) &
        & +PQRCONV(JLON,JLEV,JBLK)+PQSCONV(JLON,JLEV,JBLK)
      PNEBC(JLON,JLEV,JBLK)=PUDAL(JLON,JLEV,JBLK)*YRPHY0%FNEBC
    
  ENDDO
  ENDDO
  ENDDO

ENDIF

! INITIALIZE CONVECTIVE PROFILES: INTRA-TIME-STEP EVOLUTION.
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

ZQLC(JLON,JLEV,JBLK)= PQLCONV(JLON,JLEV,JBLK)

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

ZQIC(JLON,JLEV,JBLK)= PQICONV(JLON,JLEV,JBLK)

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

ZQRC(JLON,JLEV,JBLK)= PQRCONV(JLON,JLEV,JBLK)

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

ZQSC(JLON,JLEV,JBLK)= PQSCONV(JLON,JLEV,JBLK)

ENDDO
ENDDO
ENDDO



!-------------------------------------------------
! ENTRAINMENT AND DETRAINMENT.
!-------------------------------------------------

CALL ACMTENTR(KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV, PDELP, ZQLC, PQL, PUDAL, PDDAL, &
  & ZENTR_U, ZENTR_D, ZDETR_U, ZDETR_D, PFEDQLC)
CALL ACMTENTR(KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV, PDELP, ZQIC, PQI, PUDAL, PDDAL, &
  & ZENTR_U, ZENTR_D, ZDETR_U, ZDETR_D, PFEDQIC)
! Detrainment of rain and snow is smaller from that of lagrangian species (liquid and ice).
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA-1, KLEV
  
    ZDETR_U_RS(JLON,JLEV,JBLK)=YRPHY0%GREDDRS*ZDETR_U(JLON,JLEV,JBLK)
    ZDETR_D_RS(JLON,JLEV,JBLK)=YRPHY0%GREDDRS*ZDETR_D(JLON,JLEV,JBLK)
  
ENDDO
ENDDO
ENDDO

CALL ACMTENTR(KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV, PDELP, ZQRC, PRR, PUDAL, PDDAL, &
  & ZENTR_U, ZENTR_D, ZDETR_U_RS, ZDETR_D_RS, PFEDQRC)
CALL ACMTENTR(KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV, PDELP, ZQSC, PS,  PUDAL, PDDAL, &
  & ZENTR_U, ZENTR_D, ZDETR_U_RS, ZDETR_D_RS, PFEDQSC)

!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV
  
    ! UPDATE INTRA-TIME-STEP VALUES FROM ENTRAINMENT/DETRAINMENT FLUXES.
    ZQLC(JLON,JLEV,JBLK)=MAX(0._JPRB,ZQLC(JLON,JLEV,JBLK)-RG*(&
      &+PFEDQLC(JLON,JLEV,JBLK)-PFEDQLC(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY)
    ZQIC(JLON,JLEV,JBLK)=MAX(0._JPRB,ZQIC(JLON,JLEV,JBLK)-RG*(&
      &+PFEDQIC(JLON,JLEV,JBLK)-PFEDQIC(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY)
    ZQRC(JLON,JLEV,JBLK)=MAX(0._JPRB,ZQRC(JLON,JLEV,JBLK)-RG*(&
      &+PFEDQRC(JLON,JLEV,JBLK)-PFEDQRC(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY)
    ZQSC(JLON,JLEV,JBLK)=MAX(0._JPRB,ZQSC(JLON,JLEV,JBLK)-RG*(&
      &+PFEDQSC(JLON,JLEV,JBLK)-PFEDQSC(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY)
    ! DIAGNOSE CONDENSATE DETRAINED BY PCMT CONVECTION.
    PQC_DET_PCMT(JLON,JLEV,JBLK)=MAX(0._JPRB,RG*(&
      &+PFEDQLC(JLON,JLEV,JBLK)-PFEDQLC(JLON,JLEV-1,JBLK) &
      &+PFEDQIC(JLON,JLEV,JBLK)-PFEDQIC(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY)
  
ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

ZQLCED(JLON,JLEV,JBLK)= ZQLC(JLON,JLEV,JBLK)

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

ZQICED(JLON,JLEV,JBLK)= ZQIC(JLON,JLEV,JBLK)

ENDDO
ENDDO
ENDDO


! UPDATE INTRA-TIME-STEP CONVECTIVE VALUES FROM CONDENSATION FLUXES.
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV
  
    ZQLC(JLON,JLEV,JBLK)=ZQLC(JLON,JLEV,JBLK)-RG*(&
      &-PFCCQL(JLON,JLEV,JBLK)+PFCCQL(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY
    ZQIC(JLON,JLEV,JBLK)=ZQIC(JLON,JLEV,JBLK)-RG*(&
      &-PFCCQN(JLON,JLEV,JBLK)+PFCCQN(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY
  
ENDDO
ENDDO
ENDDO


!-------------------------------------------------
! "LOPEZ" MICROPHYSICS: AUTOCONVERSION / COLLECTION / SEDIMENTATION OF PRECIPITATION / EVAPORATION OF PRECIPITATION.
!-------------------------------------------------

! QCCONV = QLCONV + QICONV.
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV
  
    ZQLIC_MICRO(JLON,JLEV,JBLK)=ZQLC(JLON,JLEV,JBLK)+ZQIC(JLON,JLEV,JBLK)
    ZQ_COND_XR96(JLON,JLEV,JBLK)=ZQLC(JLON,JLEV,JBLK)+ZQIC(JLON,JLEV,JBLK) &
     & +ZQRC(JLON,JLEV,JBLK)+ZQSC(JLON,JLEV,JBLK)
  
ENDDO
ENDDO
ENDDO

!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 0, KLEV

ZFCCQLTMP(JLON,JLEV,JBLK)= 0._JPRB

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 0, KLEV

ZFCCQNTMP(JLON,JLEV,JBLK)= 0._JPRB

ENDDO
ENDDO
ENDDO


IF(YRPHY%LNEBNXR) THEN
  ! XU-RANDALL 1996 CLOUDINESS.
  CALL ACNEBXRS ( KIDIA,KFDIA,KGPBLKS,KLON,KTDIA,KLEV,&
    & PQ,ZQ_COND_XR96,PQSAT,&
    & ZNEBC_MICRO)
  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  DO JLEV = KTDIA, KLEV
    
      PQLIC(JLON,JLEV,JBLK)=ZQ_COND_XR96(JLON,JLEV,JBLK)
      PNEBC(JLON,JLEV,JBLK)=ZNEBC_MICRO(JLON,JLEV,JBLK)*YRPHY0%FNEBC
    
  ENDDO
  ENDDO
  ENDDO

ELSE
  IF(YRPHY0%LCVMICC) THEN
    !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
    DO JBLK = 1, KGPBLKS
    DO JLON = KIDIA, KFDIA
    DO JLEV = KTDIA, KLEV
      
        ZDAL(JLON,JBLK)=MAX(ZDAL(JLON,JBLK),PUDAL(JLON,JLEV,JBLK)+PDDAL(JLON,JLEV,JBLK))
      
    ENDDO
    ENDDO
    ENDDO

  ENDIF
  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (INEBC, IQLIC, IQLIC_MICRO, JBLK, JLEV, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  DO JLEV = KTDIA, KLEV
    
      ! CONSISTENCY BETWEEN CLOUDINESS AND CLOUD CONDENSATE:
      ! ZNEBC_MICRO=PUDAL+PDDAL WHERE >0, ZQLIC_MICRO/3.E-3 OTHERWISE
      IQLIC_MICRO=NINT(MAX(0.0_JPRB,-SIGN(1.0_JPRB,-ZQLIC_MICRO(JLON,JLEV,JBLK)+0.0_JPRB)))
      IQLIC=NINT(MAX(0.0_JPRB,-SIGN(1.0_JPRB,-PQLIC(JLON,JLEV,JBLK)+0.0_JPRB)))
      INEBC=NINT(MAX(0.0_JPRB,-SIGN(1.0_JPRB,-(PUDAL(JLON,JLEV,JBLK)*IQLIC)+0.0_JPRB)))
      IF(YRPHY0%LCVMICC) THEN
        ZNEBC_MICRO(JLON,JLEV,JBLK)=(1-IQLIC_MICRO)*ZEPS &
         &+IQLIC_MICRO*(INEBC*MAX(ZEPS,(PUDAL(JLON,JLEV,JBLK)+PDDAL(JLON,JLEV,JBLK))) &
         &+(1-INEBC)*MAX(ZEPS,MIN(ZDAL(JLON,JBLK),ZQLIC_MICRO(JLON,JLEV,JBLK)/1.E-2_JPRB)))
      ELSE
        ZNEBC_MICRO(JLON,JLEV,JBLK)=(1-IQLIC_MICRO)*ZEPS &
         &+IQLIC_MICRO*(INEBC*MAX(ZEPS,(PUDAL(JLON,JLEV,JBLK)+PDDAL(JLON,JLEV,JBLK))) &
         &+(1-INEBC)*MAX(ZEPS,MIN(0.9999_JPRB,ZQLIC_MICRO(JLON,JLEV,JBLK)/3.E-3_JPRB)))
      ENDIF
    
  ENDDO
  ENDDO
  ENDDO

ENDIF
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

ZEROV(JLON,JLEV,JBLK)= 0._JPRB

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 0, KLEV

PFCCQL(JLON,JLEV,JBLK)= 0._JPRB

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 0, KLEV

PFCCQN(JLON,JLEV,JBLK)= 0._JPRB

ENDDO
ENDDO
ENDDO



! Microphysics occurs in a shell between updraft and its resolved environment.
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV

ZTMIC(JLON,JLEV,JBLK)=(1._JPRB-YRPHY0%GSHELL)*PTU(JLON,JLEV,JBLK) &
  & +YRPHY0%GSHELL*PT(JLON,JLEV,JBLK)

ENDDO
ENDDO
ENDDO

!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV

ZQMIC(JLON,JLEV,JBLK)=(1._JPRB-YRPHY0%GSHELL)*PQU(JLON,JLEV,JBLK) &
  & +YRPHY0%GSHELL*PQ(JLON,JLEV,JBLK)

ENDDO
ENDDO
ENDDO


! Call microphysics.
LLADJCLD=.FALSE.
CALL ACPLUIZ ( KIDIA,KFDIA,KGPBLKS,KLON,KTDIA,KLEV,&
  & ZTMIC, ZQMIC, ZQLCED, ZQICED, ZQRC, ZQSC,&
  & PDELP, PAPRSF, PCP, PR, ZNEBC_MICRO, ZQLIC_MICRO,ZEROV,ZEROV,ZEROV,&
  & ZEROV, ZEROV, LLADJCLD, PAPHI,&
  & PTS, PNEIJ, PLSM, PGM, PVETAF, &
  & PFCCQL,PFCCQN, PFPLCL, PFPLCN,&
  & PFPEVPCL, PFPEVPCN, PFPFPCL, PFPFPCN, PDIFCQLC, PDIFCQIC )

! UPDATE INTRA-TIME-STEP CONVECTIVE VALUES FROM MICROPHYSICAL FLUXES.
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV
  
    ZQLC(JLON,JLEV,JBLK)=ZQLC(JLON,JLEV,JBLK)-RG*(&
      &+PFPFPCL(JLON,JLEV,JBLK)-PFPFPCL(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY
    ZQIC(JLON,JLEV,JBLK)=ZQIC(JLON,JLEV,JBLK)-RG*(&
      &+PFPFPCN(JLON,JLEV,JBLK)-PFPFPCN(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY
    ZQRC(JLON,JLEV,JBLK)=ZQRC(JLON,JLEV,JBLK)-RG*(&
      &+PFPLCL(JLON,JLEV,JBLK)-PFPLCL(JLON,JLEV-1,JBLK) &
      &-PFPFPCL(JLON,JLEV,JBLK)+PFPFPCL(JLON,JLEV-1,JBLK) &
      &+PFPEVPCL(JLON,JLEV,JBLK)-PFPEVPCL(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY
    ZQSC(JLON,JLEV,JBLK)=ZQSC(JLON,JLEV,JBLK)-RG*(&
      &+PFPLCN(JLON,JLEV,JBLK)-PFPLCN(JLON,JLEV-1,JBLK) &
      &-PFPFPCN(JLON,JLEV,JBLK)+PFPFPCN(JLON,JLEV-1,JBLK) &
      &+PFPEVPCN(JLON,JLEV,JBLK)-PFPEVPCN(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY
  
ENDDO
ENDDO
ENDDO


!-------------------------------------------------
! VERTICAL TRANSPORT OF QLCONV AND QICONV.
!-------------------------------------------------

!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV
  
    ZUDW(JLON,JLEV,JBLK)=-PUDOM(JLON,JLEV,JBLK)*PR(JLON,JLEV,JBLK)*PT(JLON,JLEV,JBLK)/(PAPRSF(JLON,JLEV,JBLK)*RG)
    ZDDW(JLON,JLEV,JBLK)=-PDDOM(JLON,JLEV,JBLK)*PR(JLON,JLEV,JBLK)*PT(JLON,JLEV,JBLK)/(PAPRSF(JLON,JLEV,JBLK)*RG)
    ZW_COMPENS(JLON,JLEV,JBLK)=-(PUDAL(JLON,JLEV,JBLK)*ZUDW(JLON,JLEV,JBLK)+PDDAL(JLON,JLEV,JBLK)*ZDDW(JLON,JLEV,JBLK)) &
      &/MAX(1.E-4_JPRB,1._JPRB-PUDAL(JLON,JLEV,JBLK)-PDDAL(JLON,JLEV,JBLK))
    ZW_CONV(JLON,JLEV,JBLK)=(PUDAL(JLON,JLEV,JBLK)*ZUDW(JLON,JLEV,JBLK)+PDDAL(JLON,JLEV,JBLK)*ZDDW(JLON,JLEV,JBLK)) &
      &/MAX(1.E-4_JPRB,PUDAL(JLON,JLEV,JBLK)+PDDAL(JLON,JLEV,JBLK))
  
ENDDO
ENDDO
ENDDO


! CONVECTIVE TRANSPORT OF CONVECTIVE CONDENSATES IN THE UPDRAFT.
CALL ACADVEC (KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV, PDELP, PAPHI, ZQLC, ZW_CONV, PDIFCQLC)
CALL ACADVEC (KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV, PDELP, PAPHI, ZQIC, ZW_CONV, PDIFCQIC)

! CONVECTIVE TRANSPORT OF RESOLVED CONDENSATES IN THE ENVIRONMENT.
CALL ACADVEC (KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV, PDELP, PAPHI, PQL, ZW_COMPENS, PDIFCQL)
CALL ACADVEC (KIDIA, KFDIA, KGPBLKS,KLON, KTDIA, KLEV, PDELP, PAPHI, PQI, ZW_COMPENS, PDIFCQI)

! UPDATE PROFILES FROM TRANSPORT FLUXES.
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV
  
    ZQLC(JLON,JLEV,JBLK)=ZQLC(JLON,JLEV,JBLK)-RG*(&
      &+PDIFCQLC(JLON,JLEV,JBLK)-PDIFCQLC(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY
    ZQIC(JLON,JLEV,JBLK)=ZQIC(JLON,JLEV,JBLK)-RG*(&
      &+PDIFCQIC(JLON,JLEV,JBLK)-PDIFCQIC(JLON,JLEV-1,JBLK) &
      &)*PRDELP(JLON,JLEV,JBLK)*YRPHY2%TSPHY
  
ENDDO
ENDDO
ENDDO


!-------------------------------------------------
! PRODUCE ICING OF CONVECTIVE LIQUID WATER TRANSPORTED BY THE UPDRAFT.
!-------------------------------------------------

!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON, ZICE, ZQLCONVPREC, ZTCVIM) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = KTDIA, KLEV
  
    ZQLCONVPREC=ZQLC(JLON,JLEV,JBLK)
    ZUDQC(JLON,JLEV,JBLK)=ZQLC(JLON,JLEV,JBLK)+ZQIC(JLON,JLEV,JBLK)
    ZICE=FONICE(PTU(JLON,JLEV,JBLK))
    ZQLC(JLON,JLEV,JBLK)=ZUDQC(JLON,JLEV,JBLK)*(1.0_JPRB-ZICE)
    ZQIC(JLON,JLEV,JBLK)=ZUDQC(JLON,JLEV,JBLK)*ZICE
    ZTCVIM=(ZQLC(JLON,JLEV,JBLK)-ZQLCONVPREC)/YRPHY2%TSPHY
    PFIMCC(JLON,JLEV,JBLK)=PFIMCC(JLON,JLEV-1,JBLK)-PDELP(JLON,JLEV,JBLK)/RG*ZTCVIM
  
ENDDO
ENDDO
ENDDO

!
! CUMULATE DEPTH OF LAYERS WHERE VERTICAL VELOCITY IS GREATER THAN A GIVEN THRESHOLD.
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
ZDEPTH(JLON,JBLK)= 0._JPRB
ENDDO
ENDDO

!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV=KTDIA,KLEV
   
      ! CONVECTIVE CLOUD DEPTH:
      ! CUMULATE DEPTH OF LAYERS WHERE VERTICAL VELOCITY IS GREATER THAN A GIVEN THRESHOLD.
      ZDEPTH(JLON,JBLK)=ZDEPTH(JLON,JBLK)+(PAPHI(JLON,JLEV-1,JBLK)-PAPHI(JLON,JLEV,JBLK))/RG &
        &*MAX(0._JPRB,SIGN(1._JPRB,ZUDW(JLON,JLEV,JBLK)-1.0_JPRB))
   
ENDDO
ENDDO
ENDDO


!-------------------------------------------------
! The PCMT call above has computed both non-precipitating and precipitating convection fluxes.
! If a separate shallow convection scheme is activated in the current physics,
! one suppresses PCMT fluxes where PCMT convection is non-precipitating.
!-------------------------------------------------
IF(YRPHY%LCVPPKF.OR.YRPHY%LEDKF) THEN
  ! PAIPCMT: Activity Index of PCMT: 1. if PCMT is active, 0. else case.
  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  
    PAIPCMT(JLON,JBLK)=MAX(0._JPRB,SIGN(1._JPRB,ZDEPTH(JLON,JBLK)-YRPHY0%THPCMT))
  
  ENDDO
  ENDDO

!  ! Is PCMT convection precipitating?
!  ZMAX(:)=0._JPRB
!  DO JLEV=KTDIA,KLEV
!    DO JLON=KIDIA,KFDIA
!      ZMAX(JLON)=MAX(ZMAX(JLON),PQRCONV(JLON,JLEV)+PQSCONV(JLON,JLEV))
!    ENDDO
!  ENDDO
!  ! PAIPCMT: Activity Index of PCMT: 1. if PCMT is active, 0. else case.
!  DO JLON=KIDIA,KFDIA
!    PAIPCMT(JLON)=MAX(0._JPRB,SIGN(1._JPRB,ZMAX(JLON)-THPCMT))
!  ENDDO
  ! One applies the PAIPCMT activity index to the PCMT fluxes.
  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  DO JLEV=KTDIA-1,KLEV
    
      PDIFCQ(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PDIFCQ(JLON,JLEV,JBLK)
      PDIFCQL(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PDIFCQL(JLON,JLEV,JBLK)
      PDIFCQI(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PDIFCQI(JLON,JLEV,JBLK)
      PDIFCQLC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PDIFCQLC(JLON,JLEV,JBLK)
      PDIFCQIC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PDIFCQIC(JLON,JLEV,JBLK)
      PDIFCS(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PDIFCS(JLON,JLEV,JBLK)
      PDIFCTH(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PDIFCTH(JLON,JLEV,JBLK)
      PFCCQL(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFCCQL(JLON,JLEV,JBLK)
      PFCCQN(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFCCQN(JLON,JLEV,JBLK)
      PSTRCU(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PSTRCU(JLON,JLEV,JBLK)
      PSTRCV(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PSTRCV(JLON,JLEV,JBLK)
      PFIMCC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFIMCC(JLON,JLEV,JBLK)
      PFPEVPCL(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFPEVPCL(JLON,JLEV,JBLK)
      PFPEVPCN(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFPEVPCN(JLON,JLEV,JBLK)
      PFPLCL(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFPLCL(JLON,JLEV,JBLK)
      PFPLCN(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFPLCN(JLON,JLEV,JBLK)
      PFPFPCL(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFPFPCL(JLON,JLEV,JBLK)
      PFPFPCN(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFPFPCN(JLON,JLEV,JBLK)
      PFEDQLC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFEDQLC(JLON,JLEV,JBLK)
      PFEDQIC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFEDQIC(JLON,JLEV,JBLK)
      PFEDQRC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFEDQRC(JLON,JLEV,JBLK)
      PFEDQSC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFEDQSC(JLON,JLEV,JBLK)
      PFCNEGQLC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFCNEGQLC(JLON,JLEV,JBLK)
      PFCNEGQIC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFCNEGQIC(JLON,JLEV,JBLK)
      PFCNEGQRC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFCNEGQRC(JLON,JLEV,JBLK)
      PFCNEGQSC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PFCNEGQSC(JLON,JLEV,JBLK)
    
  ENDDO
  ENDDO
  ENDDO

  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON, JTRA) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  DO JTRA = 1, KTRA
    DO JLEV=KTDIA,KLEV
      
          PSTRCTRA(JLON,JLEV,JTRA,JBLK)=PAIPCMT(JLON,JBLK)*PSTRCTRA(JLON,JLEV,JTRA,JBLK)
      
    ENDDO
  ENDDO
  ENDDO
  ENDDO

  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  DO JLEV=KTDIA,KLEV
    
      PNEBC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PNEBC(JLON,JLEV,JBLK)
      PQLIC(JLON,JLEV,JBLK)=PAIPCMT(JLON,JBLK)*PQLIC(JLON,JLEV,JBLK)
    
  ENDDO
  ENDDO
  ENDDO

ELSE
  ! One has called the PCMT scheme, and no external shallow convection
  ! is activated. In this case, PCMT is expected to produce both
  ! precipitating and non-precipitating convection fluxes,
  ! the activity index PAIPCMT is set to 1..
  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  
    ZDEPTH(JLON,JBLK)= 0._JPRB

  ENDDO
  ENDDO


  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  
    PAIPCMT(JLON,JBLK)= 1._JPRB

  ENDDO
  ENDDO


ENDIF

IF(YRPHY0%NCVCLOS == 4) THEN
  !
  !-------------------------------------------------
  ! In case of prognostic surface active fraction, one uses the PUDAL array
  ! to advect ZALF surface active fraction in 3D from one step to the next.
  !-------------------------------------------------
  !
  !$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
  DO JBLK = 1, KGPBLKS
  DO JLON = KIDIA, KFDIA
  DO JLEV = KTDIA, KLEV
    
      PUDAL(JLON,JLEV,JBLK) = ZALF(JLON,JBLK)
    
  ENDDO
  ENDDO
  ENDDO

ENDIF

!
!-------------------------------------------------
! PCSGC: resolved condensates located Close to SubGrid Convection: 1. if close, 0. if "far".
!-------------------------------------------------
!
!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV = 1, KLEV

PCSGC(JLON,JLEV,JBLK)= 1._JPRB

ENDDO
ENDDO
ENDDO


!$acc parallel loop gang vector collapse (2) vector_length (KLON) private (JBLK, JLEV, JLON, ZFRACP, ZTH) 
DO JBLK = 1, KGPBLKS
DO JLON = KIDIA, KFDIA
DO JLEV=KTDIA,KLEV
  
    ZFRACP=EXP((PAPRSF(JLON,JLEV,JBLK)-YRPHY0%GCVFNEP1)/YRPHY0%GCVFNEP2)
    ZTH=(ZFRACP*ZFRACP-1._JPRB)/(ZFRACP*ZFRACP+1._JPRB)
    PCSGC(JLON,JLEV,JBLK)=YRPHY0%GCVFNER*MAX(0._JPRB,SIGN(1._JPRB,ZDEPTH(JLON,JBLK)-YRPHY0%GCVFNEO)) &
      & *0.5_JPRB*(1._JPRB-ZTH)
  
ENDDO
ENDDO
ENDDO



END SUBROUTINE ACPCMT

