!OPTIONS XOPT(NOEVAL)
!$acc routine (ACPCMT) seq
SUBROUTINE ACPCMT ( KIDIA,KFDIA,KLON,KTDIA,KLEV,KTRA,&
  !-----------------------------------------------------------------------
  ! - INPUT  2D .
  & PALPH,PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PLH,PR,&
  & PDELP,PLNPR,&
  & PQ,PQI,PQL,PRR,PS,PQLIS,PQSAT,PQW,&
  & PRDELP,PCVGQ,PT,PTW,PU,PV,PTKE,PTRA,&
  & PQLCONV, PQICONV , PQRCONV, PQSCONV, &
  ! - INPUT 1D .
  & PGM, PTS, PQS, PNEIJ, PLSM, PVETAF, &
  ! - OUTPUT 2D .
  & PDIFCQ,PDIFCQL,PDIFCQI,PDIFCQLC,PDIFCQIC,PDIFCS,PDIFCTH,&
  & PFCCQL,PFCCQN,PSTRCU,PSTRCV,PSTRCTRA,&
  & PFIMCC,PFPEVPCL,PFPEVPCN,&
  & PFPLCL,PFPLCN,PMF_UP,&
  & PFPFPCL,PFPFPCN,&
  & PFEDQLC, PFEDQIC, PFEDQRC, PFEDQSC,&
  & PFCNEGQLC,PFCNEGQIC,PFCNEGQRC,PFCNEGQSC, &
  & KNLAB,&
  & PNEBC,PQLIC,PTU,PQU,PQC_DET_PCMT,PCSGC, &
  ! - OUTPUT 1D .
  & KNND, PCAPE,PAIPCMT,PALF_CAPE,PALF_CVGQ,&
  ! - INPUT/OUTPUT 2D .
  & PUDAL,PUDOM,PDDAL,PDDOM,KSTPT,KSTSZ,PSTACK)


#include "temp.h"

!**** *ACPCMT * - PCMT CONVECTION SCHEME.

! SUJET.
!     ------

!**   INTERFACE.
!     ----------
!        *CALL* *ACPCMT*
!-----------------------------------------------------------------------
! -   INPUT ARGUMENTS.
!     ----------------

! - PHYSICS DIMENSIONNING PARAMETERS

! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
! KTDIA      : INDICE DE DEPART DES BOUCLES VERTICALES (1 EN GENERAL).
! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".
! KTRA       : NUMBER OF TRACERS (PASSIVE VARIABLES)

! - PHYSICS VARIABLES (ALPHABETICALLY IN EACH CATEGORY)

! - 2D (0:KLEV) .

! PAPHI      : HALF LEVEL GEOPOTENTIAL
! PAPRS      : HALF LEVEL PRESSURE

! - 2D (1:KLEV) .

! PALPH      : LOG(PAPRS(JLEV)/PAPRSF(JLEV)) (FOR HYDROSTATIC MODEL).
! PAPHIF     : FULL LEVEL GEOPOTENTIAL
! PAPRSF     : FULL LEVEL PRESSURE
! PCP        : CHALEUR MASSIQUE A PRESSION CONSTANTE DE L'AIR.
! PR         : CONSTANTE DE L'AIR HUMIDE.
! PDELP      : PRESSURE DIFFERENCE OVER THE LAYER
! PLNPR      : LOG(PAPRS(JLEV)/PAPRS(JLEV-1)) (POUR L'HYDROSTATIQUE).
! PQ         : MICROPHYSICAL WATER VAPOUR SPECIFIC HUMIDITY
! PQI        : MICROPHYSICAL RESOLVED CLOUD ICE SPECIFIC CONTENT
! PQL        : MICROPHYSICAL RESOLVED CLOUD LIQUID SPECIFIC CONTENT
! PRR        : MICROPHYSICAL RESOLVED RAIN LIQUID SPECIFIC CONTENT
! PS         : MICROPHYSICAL RESOLVED RAIN ICE SPECIFIC CONTENT
! PQLIS      : MICROPHYSICAL RESOLVED CLOUD WATER SPECIFIC CONTENT IN THE TIME-STEP
! PQSAT      : SATURATION SPECIFIC MOISTURE
! PQW        : WET BULB SPECIFIC MOISTURE
! PRDELP     : INVERSE DE L'EPAISSEUR EN PRESSION DE LA COUCHE.
! PCVGQ      : CONVERGENCE D'HUMIDITE.
! PT         : TEMPERATURE.
! PTW        : WET BULB TEMPERATURE.
! PU         : U WIND COMPONENT
! PV         : V WIND COMPONENT
! PTKE       : TKE
! PTRA       : TRACER CONCENTRATION

! - 2D (0:KLEV) .

! - 1D .

! PGM        : FACTEUR D'ECHELLE.
! PTS        : SURFACE LAYER TEMPERATURE.
! PQS        : SURFACE LAYER WATER VAPOUR.
! PNEIJ      : FRACTION OF SOIL COVERED BY SNOW.
! PLSM       : LAND/SEA MASK.
! PVETAF     : VERTICAL COORDINATE.

!-----------------------------------------------------------------------

! -   OUTPUT ARGUMENTS
!     ----------------

! - 2D (0:KLEV) .

! PQLCONV    : LIQUID WATER (CONVECTIVE).
! PQICONV    : ICE    WATER (CONVECTIVE).
! PQRCONV    : RAIN   WATER (CONVECTIVE).
! PQSCONV    : SNOW   WATER (CONVECTIVE).
! PDIFCQ     : FLUX CONVECTIF D'HUMIDITE SPECIFIQUE (HORS PLUIE/NEIGE).
! PDIFCQ     : CONVECTIVE FLUX OF SPECIFIC HUMIDITY (NOT RAIN/SNOW).
! PDIFCQI    : FLUX CONVECTIF D'EAU SOLIDE (HORS PLUIE/NEIGE).
! PDIFCQI    : CONVECTIVE FLUX OF SOLID WATER (NOT RAIN/SNOW).
! PDIFCQL    : FLUX CONVECTIF D'EAU LIQUIDE (HORS PLUIE/NEIGE).
! PDIFCQL    : CONVECTIVE FLUX OF LIQUID WATER (NOT RAIN/SNOW).
! PDIFCQLC   : CONVECTIVE TRANSPORT FLUX OF QLC (LIQUID CONVECTIVE).
! PDIFCQIC   : CONVECTIVE TRANSPORT FLUX OF QIC (ICE CONVECTIVE).
! PDIFCS     : DRY STATIC ENERGY CONVECTIVE FLUX
! PDIFCTH    : THETA CONVECTIVE FLUX
! PFCCQL     : LIQUID CONDENSATION FLUX FROM THE CONVECTIVE UPDRAFT
! PFCCQN     : SOLID CONDENSATION FLUX FROM THE CONVECTIVE UPDRAFT
! PSTRCU     : U-MOMENTUM CONVECTIVE SPECIFIC MOISTURE FLUX
! PSTRCV     : V-MOMENTUM CONVECTIVE SPECIFIC MOISTURE FLUX
! PSTRCTRA   : TRACER CONVECTIVE FLUX
! PFHMLTS    : FLUX DE CHALEUR DU A LA FONTE/GEL.
! PFPEVPCL    : EVAPORATION DES PRECIPITATIONS LIQUIDES.
! PFPEVPCN    : EVAPORATION DES PRECIPITATIONS NEIGEUSES.
! PFPLCL     : PRECIPITATIONS CONVECTIVES SOUS FORME LIQUIDE.
! PFPLCN     : PRECIPITATIONS CONVECTIVES SOUS FORME NEIGE.
! PFPFPCL    : FLUX OF CONVECTIVE PRECIPITATION : THE GENERATION TERM.
! PFPFPCN    : FLUX OF CONVECTIVE PRECIPITATION : THE GENERATION TERM.

! - 2D (1:KLEV) .

! PNEBC  : CONVECTIVE CLOUDINESS.
! PQLIC  : CONVECTIVE CONDENSATE.
! PTU    : TEMPERATURE OF THE CLOUDY ASCENT.
! PQU    : WATER VAPOUR SPECIFIC HUMIDITY OF THE CLOUDY ASCENT.
! PQC_DET_PCMT : CLOUD CONDENSATE (QL+QI) DETRAINED BY PCMT CONVECTION.
! KNLAB  : CONVECTIVE ACTIVITY INDEX (ACTIVE IF EQUAL TO ONE).

! - 1D (DIAGNOSTIQUE) .

! KNND   : ZERO WHENEVER A NON PHYSICAL SITUATION OCCURS, ONE OTHERWISE
! PCAPE  : CAPE (CONDITIONAL AVAILABLE POTENTIAL ENERGY).
! PAIPCMT  : ACTIVITY INDEX OF PCMT: 1. IF PCMT IS ACTIVE, 0. ELSE CASE.

!-----------------------------------------------------------------------

! -   INPUT/OUTPUT ARGUMENTS
!     ----------------------

! - 2D (0:KLEV) .

! - 2D (1:KLEV) .

! PUDAL    : PROGNOSTIC UPDRAFT MESH FRACTION
! PUDOM    : PROGNOSTIC UPDRAFT RELATIVE VELOCITY
! PDDAL    : PROGNOSTIC DOWNDRAFT MESH FRACTION
! PDDOM    : PROGNOSTIC DOWNDRAFT RELATIVE VELOCITY

!-----------------------------------------------------------------------

! METHOD.
!     --------

! AUTHOR.
!     -------
! 2011-12-12, J.M. PIRIOU AND J.F. GUEREMY.

! MODIFICATIONS.
!     --------------
! 2014-04---, D. SAINT-MARTIN : tracer transport.
! 2015-02---, I. BEAU: bugfix (argument PDDOM)
! 2015-09---, J.M PIRIOU: phasing of NWP and CLimate versions
! 2015-11---, J.F. Gueremy: explicit transport flux for the dry air potential temperature
! 2017-06---, J.M. Piriou: replace NTPLUI by KTDIA.

!-----------------------------------------------------------------------


USE PARKIND1, ONLY : JPIM, JPRB

USE YOMCST   , ONLY : RG, RCPD, RCS, RCW, RALPD, RALPS,RALPW,RBETD,RBETS, &
  & RBETW,RCPV,RDT,RETV,RGAMD,RGAMS,RGAMW,RLSTT,RLVTT,RTT,RV
USE YOMPHY0  , ONLY : YRPHY0
USE YOMPHY2  , ONLY : YRPHY2

USE YOMPHY   , ONLY : YRPHY
USE YOMSCM   , ONLY : NFRSCM
USE YOMCT3   , ONLY : NSTEP
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMCST   , ONLY : RG
USE YOMPHY2  , ONLY : YRPHY2
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMCST   , ONLY : RG
USE YOMPHY2  , ONLY : YRPHY2
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMCST   , ONLY : RG
USE YOMPHY2  , ONLY : YRPHY2
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMCST   , ONLY : RG
USE YOMPHY2  , ONLY : YRPHY2

IMPLICIT NONE

!     DUMMY ARGUMENTS.

INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTRA

REAL(KIND=JPRB), INTENT(IN)    :: PALPH(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PCP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PLH(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PR(KLON,KLEV)

REAL(KIND=JPRB), INTENT(IN)    :: PDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PLNPR(KLON,KLEV)

REAL(KIND=JPRB), INTENT(IN)    :: PQ(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQI(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PRR(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQLIS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQW(KLON,KLEV)

REAL(KIND=JPRB), INTENT(IN)    :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PCVGQ(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PTW(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PTKE(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PTRA(KLON, KLEV, KTRA)

REAL(KIND=JPRB), INTENT(IN)    :: PQLCONV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQICONV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQRCONV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQSCONV(KLON,KLEV)

REAL(KIND=JPRB), INTENT(IN)    :: PGM
REAL(KIND=JPRB), INTENT(IN)    :: PTS
REAL(KIND=JPRB), INTENT(IN)    :: PQS
REAL(KIND=JPRB), INTENT(IN)    :: PNEIJ
REAL(KIND=JPRB), INTENT(IN)    :: PLSM
REAL(KIND=JPRB), INTENT(IN)    :: PVETAF(KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQ(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQLC(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQIC(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCTH(KLON,0:KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQN(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCU(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCV(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PMF_UP(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCTRA(KLON, 0:KLEV, KTRA)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFIMCC(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCN(KLON,0:KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCN(KLON,0:KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFPFPCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPFPCN(KLON,0:KLEV)

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQLC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQIC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQRC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQSC(KLON,0:KLEV)

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQLC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQIC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQRC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQSC(KLON,0:KLEV)

INTEGER(KIND=JPIM), INTENT(INOUT) :: KNLAB(KLON,KLEV)
INTEGER(KIND=JPIM), INTENT(INOUT) :: KNND

REAL(KIND=JPRB), INTENT(OUT)   :: PNEBC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQLIC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PTU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQC_DET_PCMT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PCSGC(KLON,KLEV)

REAL(KIND=JPRB), INTENT(OUT)   :: PCAPE
REAL(KIND=JPRB), INTENT(OUT)   :: PAIPCMT

REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CAPE
REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CVGQ

REAL(KIND=JPRB), INTENT(INOUT) :: PUDAL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PUDOM(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDAL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDOM(KLON,KLEV)

INTEGER(KIND=JPIM), INTENT(IN) :: KSTSZ
INTEGER(KIND=JPIM), INTENT(IN) :: KSTPT
REAL (KIND=JPRB)   , INTENT(INOUT):: PSTACK (KSTSZ)
! LOCALS.

temp (REAL(KIND=JPRB), ZEROV, (KLON,KLEV))
REAL(KIND=JPRB)   :: ZTCVIM
REAL(KIND=JPRB)   :: ZICE

temp (REAL(KIND=JPRB), ZQRC, (KLON,KLEV))
     ! downdraft vertical velocity
temp (REAL(KIND=JPRB), ZDDW, (KLON,KLEV))

temp (REAL(KIND=JPRB), ZUDQC, (KLON,KLEV))
! ZENTR_U    : ENTRAINEMENT DANS L'UPDRAFT.
! ZDETR_U    : DETRAINEMENT DE L'UPDRAFT.
! ZENTR_D    : ENTRAINEMENT DANS LE DOWNDRAFT.
! ZDETR_D    : DETRAINEMENT DU DOWNDRAFT.

temp (REAL(KIND=JPRB), ZDETR_U, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZENTR_U, (KLON,KLEV))

temp (REAL(KIND=JPRB), ZDETR_D, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZENTR_D, (KLON,KLEV))

temp (REAL(KIND=JPRB), ZFCCQLTMP, (KLON,0:KLEV))

temp (REAL(KIND=JPRB), ZQSC, (KLON,KLEV))

temp (REAL(KIND=JPRB), ZQIC, (KLON,KLEV))
REAL(KIND=JPRB)   :: ZQLCONVPREC
     ! updraft vertical velocity
temp (REAL(KIND=JPRB), ZUDW, (KLON,KLEV))

temp (REAL(KIND=JPRB), ZQLC, (KLON,KLEV))
INTEGER(KIND=JPIM) :: JLEV,JLON,INEBC,IQLIC,IQLIC_MICRO,JTRA
     ! compensating vertical velocity due to the updraft and downdraft
temp (REAL(KIND=JPRB), ZW_COMPENS, (KLON,KLEV))
     ! vertical velocity for cloud transport
temp (REAL(KIND=JPRB), ZW_CONV, (KLON,KLEV))

temp (REAL(KIND=JPRB), ZFCCQNTMP, (KLON,0:KLEV))
! ZFHEVPPC   : FLUX DE CHALEUR DU A L'EVAPORATION DES PREC. CONVECTIVES.
! ZFHMLTSC   : FLUX DE CHALEUR DU A LA FONTE/GEL DES PREC. CONVECTIVES.

temp (REAL(KIND=JPRB), ZFHMLTSC, (KLON,0:KLEV))
temp (REAL(KIND=JPRB), ZFHEVPPC, (KLON,0:KLEV))
! ZQLIC_MICRO: convective condensate, to be used in microphysics (evaporation, etc).
! ZNEBC_MICRO: convective cloudiness, to be used in microphysics (evaporation, etc).

REAL(KIND=JPRB) :: ZDAL
temp (REAL(KIND=JPRB), ZNEBC_MICRO, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZQLIC_MICRO, (KLON,KLEV))

temp (REAL(KIND=JPRB), ZQICED, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZQLCED, (KLON,KLEV))
 ! QLC+QIC+QRC+QSC, FOR USE IN THE XU-RANDALL CLOUDINESS.
temp (REAL(KIND=JPRB), ZQ_COND_XR96, (KLON,KLEV))
REAL(KIND=JPRB) :: ZCCHSL,ZCCHSN,ZEPS
!REAL(KIND=JPRB) :: ZMAX(KLON)

REAL(KIND=JPRB) :: ZDEPTH


temp (REAL(KIND=JPRB), ZTMPVAR, (KLON,KLEV))
 ! Temperature for microphysics
temp (REAL(KIND=JPRB), ZTMIC, (KLON,KLEV))
 ! Specific moisture for microphysics
temp (REAL(KIND=JPRB), ZQMIC, (KLON,KLEV))
 ! Evaporation from previous time step.
temp (REAL(KIND=JPRB), ZEVAPO, (KLON,KLEV))
 ! Energie statique seche de l'updraft.
temp (REAL(KIND=JPRB), ZSU, (KLON,KLEV))
 ! Prognostic active surface fraction.
REAL(KIND=JPRB) :: ZALF
REAL(KIND=JPRB) :: ZFRACP,ZTH

LOGICAL         :: LLADJCLD
INTEGER(KIND=JPIM) :: JLEV,JLON
REAL(KIND=JPRB) :: ZINC_LC,ZMINVALUE_ZINC_LC,ZMAXVALUE_ZINC_LC
INTEGER(KIND=JPIM) :: JLEV,JLON
REAL(KIND=JPRB) :: ZINC_IC,ZMINVALUE_ZINC_IC,ZMAXVALUE_ZINC_IC
INTEGER(KIND=JPIM) :: JLEV,JLON
REAL(KIND=JPRB) :: ZINC_RC,ZMINVALUE_ZINC_RC,ZMAXVALUE_ZINC_RC
INTEGER(KIND=JPIM) :: JLEV,JLON
REAL(KIND=JPRB) :: ZINC_SC,ZMINVALUE_ZINC_SC,ZMAXVALUE_ZINC_SC

#include "abor1.intfb.h"
#include "acadvec.intfb.h"
#include "acmtentr.intfb.h"
#include "acmtud.intfb.h"
#include "acpluiz.intfb.h"
#include "acnebxrs.intfb.h"
#include "fcttrm.func.h"
#include "fctdoi.func.h"

init_stack ()

alloc (ZEROV)
alloc (ZQRC)
alloc (ZDDW)
alloc (ZUDQC)
alloc (ZENTR_U)
alloc (ZDETR_U)
alloc (ZENTR_D)
alloc (ZDETR_D)
alloc (ZFCCQLTMP)
alloc (ZQSC)
alloc (ZQIC)
alloc (ZUDW)
alloc (ZQLC)
alloc (ZW_COMPENS)
alloc (ZW_CONV)
alloc (ZFCCQNTMP)
alloc (ZFHEVPPC)
alloc (ZFHMLTSC)
alloc (ZQLIC_MICRO)
alloc (ZNEBC_MICRO)
alloc (ZQLCED)
alloc (ZQICED)
alloc (ZQ_COND_XR96)
alloc (ZTMPVAR)
alloc (ZTMIC)
alloc (ZQMIC)
alloc (ZEVAPO)
alloc (ZSU)





ZEPS=1.E-12_JPRB
ZCCHSL=RCW-RCPD
ZCCHSN=RCS-RCPD

JLON = KIDIA

DO JLEV = 0, KLEV

PFIMCC(JLON,JLEV)= 0._JPRB

ENDDO


ZDAL= 0._JPRB


DO JLEV = 1, KLEV

PQC_DET_PCMT(JLON,JLEV)= 0._JPRB

ENDDO


DO JLEV = 1, KLEV

ZEVAPO(JLON,JLEV)= 0._JPRB

ENDDO

IF(YRPHY0%LCVNHD) THEN
  ! Evaporation from previous time step is got from the PDDAL buffer.
  DO JLEV = KTDIA, KLEV
  
  ZEVAPO(JLON,JLEV)=PDDAL(JLON,JLEV)
  
  ENDDO
ENDIF

! UDPDRAFT.
JLON = KIDIA
CALL ACMTUD ( KIDIA,KFDIA,KLON,KTDIA,KLEV,KTRA,&
  & PALPH, PAPHI, PAPHIF, PAPRS, PAPRSF, PCP,PLH, PR,&
  & PDELP, PLNPR,&
  & PQ, PQI, PQL, PQLIS, PQSAT, PQW,&
  & PRDELP, PCVGQ,PT, PTW, PU, PV, PTKE, PTRA,ZEVAPO, &
  & PGM,PTS,PQS,&
  & PDIFCQ, PDIFCQL, PDIFCQI, PDIFCS, PDIFCTH,&
  & PFCCQL, PFCCQN, PSTRCU, PSTRCV, PSTRCTRA,&
  & ZFHMLTSC,ZFHEVPPC,PFPEVPCL,PFPEVPCN,&
  & PFPLCL,PFPLCN,PMF_UP,&
  & PNEBC,PQLIC,PTU,PQU,ZSU,KNLAB,ZENTR_U,ZDETR_U,ZENTR_D,ZDETR_D,&
  & KNND,PCAPE, ZALF, PALF_CAPE, PALF_CVGQ,&
  & PUDAL,PUDOM,PDDAL,PDDOM,ISTPT,KSTSZ,PSTACK)

IF(YRPHY0%NCVQLI == 2) THEN
  ! Radiative condensates and cloudiness, due to convection, computed as ql+qi+qr+qs.
  DO JLEV = KTDIA, KLEV
    
      PQLIC(JLON,JLEV)=PQLCONV(JLON,JLEV)+PQICONV(JLON,JLEV) &
        & +PQRCONV(JLON,JLEV)+PQSCONV(JLON,JLEV)
      PNEBC(JLON,JLEV)=PUDAL(JLON,JLEV)*YRPHY0%FNEBC
    
  ENDDO
ENDIF

! INITIALIZE CONVECTIVE PROFILES: INTRA-TIME-STEP EVOLUTION.
DO JLEV = 1, KLEV

ZQLC(JLON,JLEV)= PQLCONV(JLON,JLEV)

ENDDO

DO JLEV = 1, KLEV

ZQIC(JLON,JLEV)= PQICONV(JLON,JLEV)

ENDDO

DO JLEV = 1, KLEV

ZQRC(JLON,JLEV)= PQRCONV(JLON,JLEV)

ENDDO

DO JLEV = 1, KLEV

ZQSC(JLON,JLEV)= PQSCONV(JLON,JLEV)

ENDDO


!-------------------------------------------------
! ENTRAINMENT AND DETRAINMENT.
!-------------------------------------------------

PFEDQLC(JLON)=0._JPRB

DO JLEV=KTDIA,KLEV
    
    ! PSIC INCREMENT.
    ZINC_LC=((ZENTR_U(JLON,JLEV)+ZENTR_D(JLON,JLEV)) &
      & *PQL(JLON,JLEV)/MAX(1.E-4_JPRB,1._JPRB-PUDAL(JLON,JLEV)-PDDAL(JLON,JLEV)) &
      & -1._JPRB*(ZDETR_U(JLON,JLEV)+ZDETR_D(JLON,JLEV)) &
      & *ZQLC(JLON,JLEV)/MAX(1.E-4_JPRB,PUDAL(JLON,JLEV)+PDDAL(JLON,JLEV)))*YRPHY2%TSPHY

    ! PROTECTION IN CASE OF LARGE TIME STEPS:
    ! TO AVOID INSTABILITIES
    ! THIS ZINC INCREMENT HAS TO BE SUCH THAT THE FINAL PSIC VALUE
    ! IN THE END OF TIME STEP WILL BE BETWEEN 0 AND (PSIC+PSIR).
    ! THEREFORE, THE INCREMENT HAS TO BE BETWEEN -PSIC AND PSIR.
    ZMINVALUE_ZINC_LC=-ZQLC(JLON,JLEV)
    ZMAXVALUE_ZINC_LC=PQL(JLON,JLEV)
    ZINC_LC=MAX(ZMINVALUE_ZINC_LC,MIN(ZMAXVALUE_ZINC_LC,ZINC_LC))
    PFEDQLC(JLON,JLEV)=PFEDQLC(JLON,JLEV-1)-PDELP(JLON,JLEV)/RG*ZINC_LC/YRPHY2%TSPHY
ENDDO

PFEDQIC(JLON)=0._JPRB

DO JLEV=KTDIA,KLEV
    
    ! PSIC INCREMENT.
    ZINC_IC=((ZENTR_U(JLON,JLEV)+ZENTR_D(JLON,JLEV)) &
      & *PQI(JLON,JLEV)/MAX(1.E-4_JPRB,1._JPRB-PUDAL(JLON,JLEV)-PDDAL(JLON,JLEV)) &
      & -1._JPRB*(ZDETR_U(JLON,JLEV)+ZDETR_D(JLON,JLEV)) &
      & *ZQIC(JLON,JLEV)/MAX(1.E-4_JPRB,PUDAL(JLON,JLEV)+PDDAL(JLON,JLEV)))*YRPHY2%TSPHY

    ZMINVALUE_ZINC_IC=-ZQIC(JLON,JLEV)
    ZMAXVALUE_ZINC_IC=PQI(JLON,JLEV)
    ZINC_IC=MAX(ZMINVALUE_ZINC_IC,MIN(ZMAXVALUE_ZINC_IC,ZINC_IC))
    PFEDQIC(JLON,JLEV)=PFEDQIC(JLON,JLEV-1)-PDELP(JLON,JLEV)/RG*ZINC_IC/YRPHY2%TSPHY
ENDDO


! Detrainment of rain and snow is smaller from that of lagrangian species (liquid and ice).

PFEDQRC(JLON)=0._JPRB

DO JLEV=KTDIA,KLEV
    
    ! PSIC INCREMENT.
    ZINC_RC=((ZENTR_U(JLON,JLEV)+ZENTR_D(JLON,JLEV)) &
      & *PRR(JLON,JLEV)/MAX(1.E-4_JPRB,1._JPRB-PUDAL(JLON,JLEV)-PDDAL(JLON,JLEV)) &
      & -YRPHY0%GREDDRS*(ZDETR_U(JLON,JLEV)+ZDETR_D(JLON,JLEV)) &
      & *ZQRC(JLON,JLEV)/MAX(1.E-4_JPRB,PUDAL(JLON,JLEV)+PDDAL(JLON,JLEV)))*YRPHY2%TSPHY

    ZMINVALUE_ZINC_RC=-ZQRC(JLON,JLEV)
    ZMAXVALUE_ZINC_RC=PRR(JLON,JLEV)
    ZINC_RC=MAX(ZMINVALUE_ZINC_RC,MIN(ZMAXVALUE_ZINC_RC,ZINC_RC))
    PFEDQRC(JLON,JLEV)=PFEDQRC(JLON,JLEV-1)-PDELP(JLON,JLEV)/RG*ZINC_RC/YRPHY2%TSPHY
ENDDO

PFEDQSC(JLON)=0._JPRB

DO JLEV=KTDIA,KLEV
    
    ! PSIC INCREMENT.
    ZINC_SC=((ZENTR_U(JLON,JLEV)+ZENTR_D(JLON,JLEV)) &
      & *PS(JLON,JLEV)/MAX(1.E-4_JPRB,1._JPRB-PUDAL(JLON,JLEV)-PDDAL(JLON,JLEV)) &
      & -YRPHY0%GREDDRS*(ZDETR_U(JLON,JLEV)+ZDETR_D(JLON,JLEV)) &
      & *ZQSC(JLON,JLEV)/MAX(1.E-4_JPRB,PUDAL(JLON,JLEV)+PDDAL(JLON,JLEV)))*YRPHY2%TSPHY

    ZMINVALUE_ZINC_SC=-ZQSC(JLON,JLEV)
    ZMAXVALUE_ZINC_SC=PS(JLON,JLEV)
    ZINC_SC=MAX(ZMINVALUE_ZINC_SC,MIN(ZMAXVALUE_ZINC_SC,ZINC_SC))
    PFEDQSC(JLON,JLEV)=PFEDQSC(JLON,JLEV-1)-PDELP(JLON,JLEV)/RG*ZINC_SC/YRPHY2%TSPHY
ENDDO


DO JLEV = KTDIA, KLEV
  
    ! UPDATE INTRA-TIME-STEP VALUES FROM ENTRAINMENT/DETRAINMENT FLUXES.
    ZQLC(JLON,JLEV)=MAX(0._JPRB,ZQLC(JLON,JLEV)-RG*(&
      &+PFEDQLC(JLON,JLEV)-PFEDQLC(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY)
    ZQIC(JLON,JLEV)=MAX(0._JPRB,ZQIC(JLON,JLEV)-RG*(&
      &+PFEDQIC(JLON,JLEV)-PFEDQIC(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY)
    ZQRC(JLON,JLEV)=MAX(0._JPRB,ZQRC(JLON,JLEV)-RG*(&
      &+PFEDQRC(JLON,JLEV)-PFEDQRC(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY)
    ZQSC(JLON,JLEV)=MAX(0._JPRB,ZQSC(JLON,JLEV)-RG*(&
      &+PFEDQSC(JLON,JLEV)-PFEDQSC(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY)
    ! DIAGNOSE CONDENSATE DETRAINED BY PCMT CONVECTION.
    PQC_DET_PCMT(JLON,JLEV)=MAX(0._JPRB,RG*(&
      &+PFEDQLC(JLON,JLEV)-PFEDQLC(JLON,JLEV-1) &
      &+PFEDQIC(JLON,JLEV)-PFEDQIC(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY)
  
ENDDO

DO JLEV = 1, KLEV

ZQLCED(JLON,JLEV)= ZQLC(JLON,JLEV)

ENDDO

DO JLEV = 1, KLEV

ZQICED(JLON,JLEV)= ZQIC(JLON,JLEV)

ENDDO

! UPDATE INTRA-TIME-STEP CONVECTIVE VALUES FROM CONDENSATION FLUXES.
DO JLEV = KTDIA, KLEV
  
    ZQLC(JLON,JLEV)=ZQLC(JLON,JLEV)-RG*(&
      &-PFCCQL(JLON,JLEV)+PFCCQL(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY
    ZQIC(JLON,JLEV)=ZQIC(JLON,JLEV)-RG*(&
      &-PFCCQN(JLON,JLEV)+PFCCQN(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY
  
ENDDO

!-------------------------------------------------
! "LOPEZ" MICROPHYSICS: AUTOCONVERSION / COLLECTION / SEDIMENTATION OF PRECIPITATION / EVAPORATION OF PRECIPITATION.
!-------------------------------------------------

! QCCONV = QLCONV + QICONV.
DO JLEV = KTDIA, KLEV
  
    ZQLIC_MICRO(JLON,JLEV)=ZQLC(JLON,JLEV)+ZQIC(JLON,JLEV)
    ZQ_COND_XR96(JLON,JLEV)=ZQLC(JLON,JLEV)+ZQIC(JLON,JLEV) &
     & +ZQRC(JLON,JLEV)+ZQSC(JLON,JLEV)
  
ENDDO
DO JLEV = 0, KLEV

ZFCCQLTMP(JLON,JLEV)= 0._JPRB

ENDDO

DO JLEV = 0, KLEV

ZFCCQNTMP(JLON,JLEV)= 0._JPRB

ENDDO

IF(YRPHY%LNEBNXR) THEN
  ! XU-RANDALL 1996 CLOUDINESS.
  CALL ACNEBXRS ( KIDIA,KFDIA,KLON,KTDIA,KLEV,&
    & PQ,ZQ_COND_XR96,PQSAT,&
    & ZNEBC_MICRO,ISTPT,KSTSZ,PSTACK)
  DO JLEV = KTDIA, KLEV
    
      PQLIC(JLON,JLEV)=ZQ_COND_XR96(JLON,JLEV)
      PNEBC(JLON,JLEV)=ZNEBC_MICRO(JLON,JLEV)*YRPHY0%FNEBC
    
  ENDDO
ELSE
  IF(YRPHY0%LCVMICC) THEN
    DO JLEV = KTDIA, KLEV
      
        ZDAL=MAX(ZDAL,PUDAL(JLON,JLEV)+PDDAL(JLON,JLEV))
      
    ENDDO
  ENDIF
  DO JLEV = KTDIA, KLEV
    
      ! CONSISTENCY BETWEEN CLOUDINESS AND CLOUD CONDENSATE:
      ! ZNEBC_MICRO=PUDAL+PDDAL WHERE >0, ZQLIC_MICRO/3.E-3 OTHERWISE
      IQLIC_MICRO=NINT(MAX(0.0_JPRB,-SIGN(1.0_JPRB,-ZQLIC_MICRO(JLON,JLEV)+0.0_JPRB)))
      IQLIC=NINT(MAX(0.0_JPRB,-SIGN(1.0_JPRB,-PQLIC(JLON,JLEV)+0.0_JPRB)))
      INEBC=NINT(MAX(0.0_JPRB,-SIGN(1.0_JPRB,-(PUDAL(JLON,JLEV)*IQLIC)+0.0_JPRB)))
      IF(YRPHY0%LCVMICC) THEN
        ZNEBC_MICRO(JLON,JLEV)=(1-IQLIC_MICRO)*ZEPS &
         &+IQLIC_MICRO*(INEBC*MAX(ZEPS,(PUDAL(JLON,JLEV)+PDDAL(JLON,JLEV))) &
         &+(1-INEBC)*MAX(ZEPS,MIN(ZDAL,ZQLIC_MICRO(JLON,JLEV)/1.E-2_JPRB)))
      ELSE
        ZNEBC_MICRO(JLON,JLEV)=(1-IQLIC_MICRO)*ZEPS &
         &+IQLIC_MICRO*(INEBC*MAX(ZEPS,(PUDAL(JLON,JLEV)+PDDAL(JLON,JLEV))) &
         &+(1-INEBC)*MAX(ZEPS,MIN(0.9999_JPRB,ZQLIC_MICRO(JLON,JLEV)/3.E-3_JPRB)))
      ENDIF
    
  ENDDO
ENDIF
DO JLEV = 1, KLEV

ZEROV(JLON,JLEV)= 0._JPRB

ENDDO

DO JLEV = 0, KLEV

PFCCQL(JLON,JLEV)= 0._JPRB

ENDDO

DO JLEV = 0, KLEV

PFCCQN(JLON,JLEV)= 0._JPRB

ENDDO


! Microphysics occurs in a shell between updraft and its resolved environment.
DO JLEV = KTDIA, KLEV

ZTMIC(JLON,JLEV)=(1._JPRB-YRPHY0%GSHELL)*PTU(JLON,JLEV) &
  & +YRPHY0%GSHELL*PT(JLON,JLEV)

ENDDO
DO JLEV = KTDIA, KLEV

ZQMIC(JLON,JLEV)=(1._JPRB-YRPHY0%GSHELL)*PQU(JLON,JLEV) &
  & +YRPHY0%GSHELL*PQ(JLON,JLEV)

ENDDO

! Call microphysics.
LLADJCLD=.FALSE.
CALL ACPLUIZ ( KIDIA,KFDIA,KLON,KTDIA,KLEV,&
  & ZTMIC, ZQMIC, ZQLCED, ZQICED, ZQRC, ZQSC,&
  & PDELP, PAPRSF, PCP, PR, ZNEBC_MICRO, ZQLIC_MICRO,ZEROV,ZEROV,ZEROV,&
  & ZEROV, ZEROV, LLADJCLD, PAPHI,&
  & PTS, PNEIJ, PLSM, PGM, PVETAF, &
  & PFCCQL,PFCCQN, PFPLCL, PFPLCN,&
  & PFPEVPCL, PFPEVPCN, PFPFPCL, PFPFPCN, PDIFCQLC, PDIFCQIC,ISTPT,KSTSZ,PSTACK )

! UPDATE INTRA-TIME-STEP CONVECTIVE VALUES FROM MICROPHYSICAL FLUXES.
DO JLEV = KTDIA, KLEV
  
    ZQLC(JLON,JLEV)=ZQLC(JLON,JLEV)-RG*(&
      &+PFPFPCL(JLON,JLEV)-PFPFPCL(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY
    ZQIC(JLON,JLEV)=ZQIC(JLON,JLEV)-RG*(&
      &+PFPFPCN(JLON,JLEV)-PFPFPCN(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY
    ZQRC(JLON,JLEV)=ZQRC(JLON,JLEV)-RG*(&
      &+PFPLCL(JLON,JLEV)-PFPLCL(JLON,JLEV-1) &
      &-PFPFPCL(JLON,JLEV)+PFPFPCL(JLON,JLEV-1) &
      &+PFPEVPCL(JLON,JLEV)-PFPEVPCL(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY
    ZQSC(JLON,JLEV)=ZQSC(JLON,JLEV)-RG*(&
      &+PFPLCN(JLON,JLEV)-PFPLCN(JLON,JLEV-1) &
      &-PFPFPCN(JLON,JLEV)+PFPFPCN(JLON,JLEV-1) &
      &+PFPEVPCN(JLON,JLEV)-PFPEVPCN(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY
  
ENDDO

!-------------------------------------------------
! VERTICAL TRANSPORT OF QLCONV AND QICONV.
!-------------------------------------------------

DO JLEV = KTDIA, KLEV
  
    ZUDW(JLON,JLEV)=-PUDOM(JLON,JLEV)*PR(JLON,JLEV)*PT(JLON,JLEV)/(PAPRSF(JLON,JLEV)*RG)
    ZDDW(JLON,JLEV)=-PDDOM(JLON,JLEV)*PR(JLON,JLEV)*PT(JLON,JLEV)/(PAPRSF(JLON,JLEV)*RG)
    ZW_COMPENS(JLON,JLEV)=-(PUDAL(JLON,JLEV)*ZUDW(JLON,JLEV)+PDDAL(JLON,JLEV)*ZDDW(JLON,JLEV)) &
      &/MAX(1.E-4_JPRB,1._JPRB-PUDAL(JLON,JLEV)-PDDAL(JLON,JLEV))
    ZW_CONV(JLON,JLEV)=(PUDAL(JLON,JLEV)*ZUDW(JLON,JLEV)+PDDAL(JLON,JLEV)*ZDDW(JLON,JLEV)) &
      &/MAX(1.E-4_JPRB,PUDAL(JLON,JLEV)+PDDAL(JLON,JLEV))
  
ENDDO

! CONVECTIVE TRANSPORT OF CONVECTIVE CONDENSATES IN THE UPDRAFT.
CALL ACADVEC (KIDIA, KFDIA, KLON, KTDIA, KLEV, PDELP, PAPHI, ZQLC, ZW_CONV, PDIFCQLC,ISTPT,KSTSZ,PSTACK)
CALL ACADVEC (KIDIA, KFDIA, KLON, KTDIA, KLEV, PDELP, PAPHI, ZQIC, ZW_CONV, PDIFCQIC,ISTPT,KSTSZ,PSTACK)

! CONVECTIVE TRANSPORT OF RESOLVED CONDENSATES IN THE ENVIRONMENT.
CALL ACADVEC (KIDIA, KFDIA, KLON, KTDIA, KLEV, PDELP, PAPHI, PQL, ZW_COMPENS, PDIFCQL,ISTPT,KSTSZ,PSTACK)
CALL ACADVEC (KIDIA, KFDIA, KLON, KTDIA, KLEV, PDELP, PAPHI, PQI, ZW_COMPENS, PDIFCQI,ISTPT,KSTSZ,PSTACK)

! UPDATE PROFILES FROM TRANSPORT FLUXES.
DO JLEV = KTDIA, KLEV
  
    ZQLC(JLON,JLEV)=ZQLC(JLON,JLEV)-RG*(&
      &+PDIFCQLC(JLON,JLEV)-PDIFCQLC(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY
    ZQIC(JLON,JLEV)=ZQIC(JLON,JLEV)-RG*(&
      &+PDIFCQIC(JLON,JLEV)-PDIFCQIC(JLON,JLEV-1) &
      &)*PRDELP(JLON,JLEV)*YRPHY2%TSPHY
  
ENDDO

!-------------------------------------------------
! PRODUCE ICING OF CONVECTIVE LIQUID WATER TRANSPORTED BY THE UPDRAFT.
!-------------------------------------------------

DO JLEV = KTDIA, KLEV
  
    ZQLCONVPREC=ZQLC(JLON,JLEV)
    ZUDQC(JLON,JLEV)=ZQLC(JLON,JLEV)+ZQIC(JLON,JLEV)
    ZICE=FONICE(PTU(JLON,JLEV))
    ZQLC(JLON,JLEV)=ZUDQC(JLON,JLEV)*(1.0_JPRB-ZICE)
    ZQIC(JLON,JLEV)=ZUDQC(JLON,JLEV)*ZICE
    ZTCVIM=(ZQLC(JLON,JLEV)-ZQLCONVPREC)/YRPHY2%TSPHY
    PFIMCC(JLON,JLEV)=PFIMCC(JLON,JLEV-1)-PDELP(JLON,JLEV)/RG*ZTCVIM
  
ENDDO
!
! CUMULATE DEPTH OF LAYERS WHERE VERTICAL VELOCITY IS GREATER THAN A GIVEN THRESHOLD.

ZDEPTH= 0._JPRB


DO JLEV=KTDIA,KLEV
   
      ! CONVECTIVE CLOUD DEPTH:
      ! CUMULATE DEPTH OF LAYERS WHERE VERTICAL VELOCITY IS GREATER THAN A GIVEN THRESHOLD.
      ZDEPTH=ZDEPTH+(PAPHI(JLON,JLEV-1)-PAPHI(JLON,JLEV))/RG &
        &*MAX(0._JPRB,SIGN(1._JPRB,ZUDW(JLON,JLEV)-1.0_JPRB))
   
ENDDO

!-------------------------------------------------
! The PCMT call above has computed both non-precipitating and precipitating convection fluxes.
! If a separate shallow convection scheme is activated in the current physics,
! one suppresses PCMT fluxes where PCMT convection is non-precipitating.
!-------------------------------------------------
IF(YRPHY%LCVPPKF.OR.YRPHY%LEDKF) THEN
  ! PAIPCMT: Activity Index of PCMT: 1. if PCMT is active, 0. else case.
  
    PAIPCMT=MAX(0._JPRB,SIGN(1._JPRB,ZDEPTH-YRPHY0%THPCMT))
  
!  ! Is PCMT convection precipitating?
!  ZMAX(:)=0._JPRB
!  DO JLEV=KTDIA,KLEV
!    DO JLON=KIDIA,KFDIA
!      ZMAX(JLON)=MAX(ZMAX(JLON),PQRCONV(JLON,JLEV)+PQSCONV(JLON,JLEV))
!    ENDDO
!  ENDDO
!  ! PAIPCMT: Activity Index of PCMT: 1. if PCMT is active, 0. else case.
!  DO JLON=KIDIA,KFDIA
!    PAIPCMT(JLON)=MAX(0._JPRB,SIGN(1._JPRB,ZMAX(JLON)-THPCMT))
!  ENDDO
  ! One applies the PAIPCMT activity index to the PCMT fluxes.
  DO JLEV=KTDIA-1,KLEV
    
      PDIFCQ(JLON,JLEV)=PAIPCMT*PDIFCQ(JLON,JLEV)
      PDIFCQL(JLON,JLEV)=PAIPCMT*PDIFCQL(JLON,JLEV)
      PDIFCQI(JLON,JLEV)=PAIPCMT*PDIFCQI(JLON,JLEV)
      PDIFCQLC(JLON,JLEV)=PAIPCMT*PDIFCQLC(JLON,JLEV)
      PDIFCQIC(JLON,JLEV)=PAIPCMT*PDIFCQIC(JLON,JLEV)
      PDIFCS(JLON,JLEV)=PAIPCMT*PDIFCS(JLON,JLEV)
      PDIFCTH(JLON,JLEV)=PAIPCMT*PDIFCTH(JLON,JLEV)
      PFCCQL(JLON,JLEV)=PAIPCMT*PFCCQL(JLON,JLEV)
      PFCCQN(JLON,JLEV)=PAIPCMT*PFCCQN(JLON,JLEV)
      PSTRCU(JLON,JLEV)=PAIPCMT*PSTRCU(JLON,JLEV)
      PSTRCV(JLON,JLEV)=PAIPCMT*PSTRCV(JLON,JLEV)
      PFIMCC(JLON,JLEV)=PAIPCMT*PFIMCC(JLON,JLEV)
      PFPEVPCL(JLON,JLEV)=PAIPCMT*PFPEVPCL(JLON,JLEV)
      PFPEVPCN(JLON,JLEV)=PAIPCMT*PFPEVPCN(JLON,JLEV)
      PFPLCL(JLON,JLEV)=PAIPCMT*PFPLCL(JLON,JLEV)
      PFPLCN(JLON,JLEV)=PAIPCMT*PFPLCN(JLON,JLEV)
      PFPFPCL(JLON,JLEV)=PAIPCMT*PFPFPCL(JLON,JLEV)
      PFPFPCN(JLON,JLEV)=PAIPCMT*PFPFPCN(JLON,JLEV)
      PFEDQLC(JLON,JLEV)=PAIPCMT*PFEDQLC(JLON,JLEV)
      PFEDQIC(JLON,JLEV)=PAIPCMT*PFEDQIC(JLON,JLEV)
      PFEDQRC(JLON,JLEV)=PAIPCMT*PFEDQRC(JLON,JLEV)
      PFEDQSC(JLON,JLEV)=PAIPCMT*PFEDQSC(JLON,JLEV)
      PFCNEGQLC(JLON,JLEV)=PAIPCMT*PFCNEGQLC(JLON,JLEV)
      PFCNEGQIC(JLON,JLEV)=PAIPCMT*PFCNEGQIC(JLON,JLEV)
      PFCNEGQRC(JLON,JLEV)=PAIPCMT*PFCNEGQRC(JLON,JLEV)
      PFCNEGQSC(JLON,JLEV)=PAIPCMT*PFCNEGQSC(JLON,JLEV)
    
  ENDDO
  DO JTRA = 1, KTRA
    DO JLEV=KTDIA,KLEV
      
          PSTRCTRA(JLON,JLEV,JTRA)=PAIPCMT*PSTRCTRA(JLON,JLEV,JTRA)
      
    ENDDO
  ENDDO
  DO JLEV=KTDIA,KLEV
    
      PNEBC(JLON,JLEV)=PAIPCMT*PNEBC(JLON,JLEV)
      PQLIC(JLON,JLEV)=PAIPCMT*PQLIC(JLON,JLEV)
    
  ENDDO
ELSE
  ! One has called the PCMT scheme, and no external shallow convection
  ! is activated. In this case, PCMT is expected to produce both
  ! precipitating and non-precipitating convection fluxes,
  ! the activity index PAIPCMT is set to 1..
  
ZDEPTH= 0._JPRB


  
PAIPCMT= 1._JPRB


ENDIF

IF(YRPHY0%NCVCLOS == 4) THEN
  !
  !-------------------------------------------------
  ! In case of prognostic surface active fraction, one uses the PUDAL array
  ! to advect ZALF surface active fraction in 3D from one step to the next.
  !-------------------------------------------------
  !
  DO JLEV = KTDIA, KLEV
    
      PUDAL(JLON,JLEV) = ZALF
    
  ENDDO
ENDIF

!
!-------------------------------------------------
! PCSGC: resolved condensates located Close to SubGrid Convection: 1. if close, 0. if "far".
!-------------------------------------------------
!
DO JLEV = 1, KLEV

PCSGC(JLON,JLEV)= 1._JPRB

ENDDO

DO JLEV=KTDIA,KLEV
  
    ZFRACP=EXP((PAPRSF(JLON,JLEV)-YRPHY0%GCVFNEP1)/YRPHY0%GCVFNEP2)
    ZTH=(ZFRACP*ZFRACP-1._JPRB)/(ZFRACP*ZFRACP+1._JPRB)
    PCSGC(JLON,JLEV)=YRPHY0%GCVFNER*MAX(0._JPRB,SIGN(1._JPRB,ZDEPTH-YRPHY0%GCVFNEO)) &
      & *0.5_JPRB*(1._JPRB-ZTH)
  
ENDDO

END SUBROUTINE ACPCMT

