SUBROUTINE ACPCMT_LOAD_ALL (CDNAME)
USE LOAD_MOD, ONLY : OPEN_LOAD, CLOSE_LOAD, ILUN_IN, LOAD
CHARACTER (LEN=*) :: CDNAME
  CALL OPEN_LOAD (CDNAME)
  CALL LOAD_YEMGEO
  CALL LOAD_YOMCAPE
  CALL LOAD_YOMCST
  CALL LOAD_YOMCT0
  CALL LOAD_YOMCT3
  CALL LOAD_YOMDIM
  CALL LOAD_YOMFPC
  CALL LOAD_YOMGEM
  CALL LOAD_YOMPHY
  CALL LOAD_YOMPHY0
  CALL LOAD_YOMPHY1
  CALL LOAD_YOMPHY2
  CALL LOAD_YOMRIP
  CALL LOAD_YOMSCM
  CALL LOAD_YOMTOPH
  CALL CLOSE_LOAD

CONTAINS
SUBROUTINE LOAD_YEMGEO
USE YEMGEO
  TYPE(TEGEO) :: YLEGEO
  CALL LOAD (ILUN_IN, YLEGEO%EDELX)
  CALL LOAD (ILUN_IN, YLEGEO%EDELY)
  YREGEO = YLEGEO
END SUBROUTINE
SUBROUTINE LOAD_YOMCAPE
USE YOMCAPE
  REAL(KIND=JPRB) :: ZCAPERET
  INTEGER(KIND=JPIM) :: JCAPEITER, JETAPES
  CALL LOAD (ILUN_IN, ZCAPERET)
  CALL LOAD (ILUN_IN, JCAPEITER)
  CALL LOAD (ILUN_IN, JETAPES)
  GCAPERET  = ZCAPERET 
  NCAPEITER = JCAPEITER
  NETAPES   = JETAPES   
END SUBROUTINE
SUBROUTINE LOAD_YOMCST
USE YOMCST
  REAL (KIND=JPRB) :: ZA
  REAL (KIND=JPRB) :: ZALPD
  REAL (KIND=JPRB) :: ZALPS
  REAL (KIND=JPRB) :: ZALPW
  REAL (KIND=JPRB) :: ZATM
  REAL (KIND=JPRB) :: ZBETD
  REAL (KIND=JPRB) :: ZBETS
  REAL (KIND=JPRB) :: ZBETW
  REAL (KIND=JPRB) :: ZCPD
  REAL (KIND=JPRB) :: ZCPV
  REAL (KIND=JPRB) :: ZCS
  REAL (KIND=JPRB) :: ZCW
  REAL (KIND=JPRB) :: ZD
  REAL (KIND=JPRB) :: ZDAY
  REAL (KIND=JPRB) :: ZDT
  REAL (KIND=JPRB) :: ZEA
  REAL (KIND=JPRB) :: ZEPSM
  REAL (KIND=JPRB) :: ZETV
  REAL (KIND=JPRB) :: ZG
  REAL (KIND=JPRB) :: ZGAMD
  REAL (KIND=JPRB) :: ZGAMS
  REAL (KIND=JPRB) :: ZGAMW
  REAL (KIND=JPRB) :: ZKAPPA
  REAL (KIND=JPRB) :: ZLSTT
  REAL (KIND=JPRB) :: ZLVTT
  REAL (KIND=JPRB) :: ZPI
  REAL (KIND=JPRB) :: ZTT
  REAL (KIND=JPRB) :: ZV

  CALL LOAD (ILUN_IN, ZA)
  CALL LOAD (ILUN_IN, ZALPD)
  CALL LOAD (ILUN_IN, ZALPS)
  CALL LOAD (ILUN_IN, ZALPW)
  CALL LOAD (ILUN_IN, ZATM)
  CALL LOAD (ILUN_IN, ZBETD)
  CALL LOAD (ILUN_IN, ZBETS)
  CALL LOAD (ILUN_IN, ZBETW)
  CALL LOAD (ILUN_IN, ZCPD)
  CALL LOAD (ILUN_IN, ZCPV)
  CALL LOAD (ILUN_IN, ZCS)
  CALL LOAD (ILUN_IN, ZCW)
  CALL LOAD (ILUN_IN, ZD)
  CALL LOAD (ILUN_IN, ZDAY)
  CALL LOAD (ILUN_IN, ZDT)
  CALL LOAD (ILUN_IN, ZEA)
  CALL LOAD (ILUN_IN, ZEPSM)
  CALL LOAD (ILUN_IN, ZETV)
  CALL LOAD (ILUN_IN, ZG)
  CALL LOAD (ILUN_IN, ZGAMD)
  CALL LOAD (ILUN_IN, ZGAMS)
  CALL LOAD (ILUN_IN, ZGAMW)
  CALL LOAD (ILUN_IN, ZKAPPA)
  CALL LOAD (ILUN_IN, ZLSTT)
  CALL LOAD (ILUN_IN, ZLVTT)
  CALL LOAD (ILUN_IN, ZPI)
  CALL LOAD (ILUN_IN, ZTT)
  CALL LOAD (ILUN_IN, ZV)

  RA      = ZA    
  RALPD   = ZALPD 
  RALPS   = ZALPS 
  RALPW   = ZALPW 
  RATM    = ZATM  
  RBETD   = ZBETD 
  RBETS   = ZBETS 
  RBETW   = ZBETW 
  RCPD    = ZCPD  
  RCPV    = ZCPV  
  RCS     = ZCS   
  RCW     = ZCW   
  RD      = ZD    
  RDAY    = ZDAY  
  RDT     = ZDT   
  REA     = ZEA   
  REPSM   = ZEPSM 
  RETV    = ZETV  
  RG      = ZG    
  RGAMD   = ZGAMD 
  RGAMS   = ZGAMS 
  RGAMW   = ZGAMW 
  RKAPPA  = ZKAPPA
  RLSTT   = ZLSTT 
  RLVTT   = ZLVTT 
  RPI     = ZPI   
  RTT     = ZTT   
  RV      = ZV    

END SUBROUTINE
SUBROUTINE LOAD_YOMCT0
USE YOMCT0
  LOGICAL :: LLELAM
  CALL LOAD (ILUN_IN, LLELAM)
  LELAM = LLELAM
END SUBROUTINE
SUBROUTINE LOAD_YOMCT3
USE YOMCT3
  INTEGER(KIND=JPIM) :: INSTEP
  CALL LOAD (ILUN_IN, INSTEP)
  NSTEP = INSTEP
END SUBROUTINE
SUBROUTINE LOAD_YOMDIM
USE YOMDIM
  TYPE(TDIM) :: YLDIM
  CALL LOAD (ILUN_IN, YLDIM%NDLON)
  CALL LOAD (ILUN_IN, YLDIM%NSMAX)
  YRDIM = YLDIM
END SUBROUTINE
SUBROUTINE LOAD_YOMFPC
USE YOMFPC
  INTEGER(KIND=JPIM) :: ZRENTRA
  CALL LOAD (ILUN_IN, ZRENTRA)
  RENTRA = ZRENTRA
END SUBROUTINE
SUBROUTINE LOAD_YOMGEM
USE YOMGEM
  TYPE(TGEM) :: YLGEM
  CALL LOAD (ILUN_IN, YLGEM%RDELXN)
  YRGEM = YLGEM
END SUBROUTINE
SUBROUTINE LOAD_YOMPHY
USE YOMPHY
  TYPE (TPHY) :: YLPHY
  CALL LOAD (ILUN_IN, YLPHY%LCOLLEC)
  CALL LOAD (ILUN_IN, YLPHY%LCVPPKF)
  CALL LOAD (ILUN_IN, YLPHY%LEDKF)
  CALL LOAD (ILUN_IN, YLPHY%LEVAPP)
  CALL LOAD (ILUN_IN, YLPHY%LNEBNXR)
  CALL LOAD (ILUN_IN, YLPHY%LNEIGE)
  CALL LOAD (ILUN_IN, YLPHY%LQXRTGH)
  CALL LOAD (ILUN_IN, YLPHY%LSMOOTHMELT)
  CALL LOAD (ILUN_IN, YLPHY%NBITER)
  CALL LOAD (ILUN_IN, YLPHY%NPHYREP)
  YRPHY = YLPHY
END SUBROUTINE
SUBROUTINE LOAD_YOMPHY0
USE YOMPHY0
  TYPE (TPHY0) :: YLPHY0

  CALL LOAD (ILUN_IN, YLPHY0%ADOE)
  CALL LOAD (ILUN_IN, YLPHY0%ALFX)
  CALL LOAD (ILUN_IN, YLPHY0%ALFX_HR)
  CALL LOAD (ILUN_IN, YLPHY0%ALFX_LR)
  CALL LOAD (ILUN_IN, YLPHY0%ECMNP)
  CALL LOAD (ILUN_IN, YLPHY0%FENTRT)
  CALL LOAD (ILUN_IN, YLPHY0%FEVAPC)
  CALL LOAD (ILUN_IN, YLPHY0%FNEBC)
  CALL LOAD (ILUN_IN, YLPHY0%FQLIC)
  CALL LOAD (ILUN_IN, YLPHY0%GALMAX)
  CALL LOAD (ILUN_IN, YLPHY0%GALMIN)
  CALL LOAD (ILUN_IN, YLPHY0%GALTAU)
  CALL LOAD (ILUN_IN, YLPHY0%GAMAP1)
  CALL LOAD (ILUN_IN, YLPHY0%GCHI0)
  CALL LOAD (ILUN_IN, YLPHY0%GCLOEB)
  CALL LOAD (ILUN_IN, YLPHY0%GCVADET)
  CALL LOAD (ILUN_IN, YLPHY0%GCVADS)
  CALL LOAD (ILUN_IN, YLPHY0%GCVCINC)
  CALL LOAD (ILUN_IN, YLPHY0%GCVENTRN)
  CALL LOAD (ILUN_IN, YLPHY0%GCVENTRX)
  CALL LOAD (ILUN_IN, YLPHY0%GCVENTR_MIN)
  CALL LOAD (ILUN_IN, YLPHY0%GCVEZ)
  CALL LOAD (ILUN_IN, YLPHY0%GCVFNEO)
  CALL LOAD (ILUN_IN, YLPHY0%GCVFNEP1)
  CALL LOAD (ILUN_IN, YLPHY0%GCVFNEP2)
  CALL LOAD (ILUN_IN, YLPHY0%GCVFNER)
  CALL LOAD (ILUN_IN, YLPHY0%GCVFRR)
  CALL LOAD (ILUN_IN, YLPHY0%GCVGQX)
  CALL LOAD (ILUN_IN, YLPHY0%GCVRE)
  CALL LOAD (ILUN_IN, YLPHY0%GCVRESN)
  CALL LOAD (ILUN_IN, YLPHY0%GCVRESX)
  CALL LOAD (ILUN_IN, YLPHY0%GCVTEXC)
  CALL LOAD (ILUN_IN, YLPHY0%GCVTRMIN)
  CALL LOAD (ILUN_IN, YLPHY0%GCVUV)
  CALL LOAD (ILUN_IN, YLPHY0%GCVWEXC)
  CALL LOAD (ILUN_IN, YLPHY0%GDDSDE)
  CALL LOAD (ILUN_IN, YLPHY0%GDEPTH)
  CALL LOAD (ILUN_IN, YLPHY0%GEXPKD)
  CALL LOAD (ILUN_IN, YLPHY0%GFRIC)
  CALL LOAD (ILUN_IN, YLPHY0%GFSURF)
  CALL LOAD (ILUN_IN, YLPHY0%GINSTX)
  CALL LOAD (ILUN_IN, YLPHY0%GKEDDRE)
  CALL LOAD (ILUN_IN, YLPHY0%GMUKEDD)
  CALL LOAD (ILUN_IN, YLPHY0%GNHACC)
  CALL LOAD (ILUN_IN, YLPHY0%GNHDEV)
  CALL LOAD (ILUN_IN, YLPHY0%GNHDSMOS)
  CALL LOAD (ILUN_IN, YLPHY0%GNHDSMOW)
  CALL LOAD (ILUN_IN, YLPHY0%GNHDTAU)
  CALL LOAD (ILUN_IN, YLPHY0%GPRONI)
  CALL LOAD (ILUN_IN, YLPHY0%GRBCC)
  CALL LOAD (ILUN_IN, YLPHY0%GREDDRS)
  CALL LOAD (ILUN_IN, YLPHY0%GREMAX)
  CALL LOAD (ILUN_IN, YLPHY0%GREMIN)
  CALL LOAD (ILUN_IN, YLPHY0%GRHCMOD)
  CALL LOAD (ILUN_IN, YLPHY0%GSDAMAX)
  CALL LOAD (ILUN_IN, YLPHY0%GSDAMIN)
  CALL LOAD (ILUN_IN, YLPHY0%GSDMAX)
  CALL LOAD (ILUN_IN, YLPHY0%GSDMIN)
  CALL LOAD (ILUN_IN, YLPHY0%GSHELL)
  CALL LOAD (ILUN_IN, YLPHY0%GSIGA)
  CALL LOAD (ILUN_IN, YLPHY0%GSINHD)
  CALL LOAD (ILUN_IN, YLPHY0%GSINHR)
  CALL LOAD (ILUN_IN, YLPHY0%GTDCL)
  CALL LOAD (ILUN_IN, YLPHY0%GUDDD)
  CALL LOAD (ILUN_IN, YLPHY0%LADVLIM)
  CALL LOAD (ILUN_IN, YLPHY0%LCVCONTAU)
  CALL LOAD (ILUN_IN, YLPHY0%LCVEOD)
  CALL LOAD (ILUN_IN, YLPHY0%LCVIMPT)
  CALL LOAD (ILUN_IN, YLPHY0%LCVMICC)
  CALL LOAD (ILUN_IN, YLPHY0%LCVNAUV)
  CALL LOAD (ILUN_IN, YLPHY0%LCVNHD)
  CALL LOAD (ILUN_IN, YLPHY0%LCVTADV)
  CALL LOAD (ILUN_IN, YLPHY0%LCVUVM)
  CALL LOAD (ILUN_IN, YLPHY0%LGDDD)
  CALL LOAD (ILUN_IN, YLPHY0%LGPRONI1)
  CALL LOAD (ILUN_IN, YLPHY0%LGVVEX)
  CALL LOAD (ILUN_IN, YLPHY0%LSBUO)
  CALL LOAD (ILUN_IN, YLPHY0%NCAPEMOD)
  CALL LOAD (ILUN_IN, YLPHY0%NCVCLOS)
  CALL LOAD (ILUN_IN, YLPHY0%NCVENTR)
  CALL LOAD (ILUN_IN, YLPHY0%NCVQLI)
  CALL LOAD (ILUN_IN, YLPHY0%NCVSIG)
  CALL LOAD (ILUN_IN, YLPHY0%NPRONI)
  CALL LOAD (ILUN_IN, YLPHY0%QXRAL)
  CALL LOAD (ILUN_IN, YLPHY0%QXRDEL)
  CALL LOAD (ILUN_IN, YLPHY0%QXRHX)
  CALL LOAD (ILUN_IN, YLPHY0%QXRR)
  CALL LOAD (ILUN_IN, YLPHY0%QXRTGH)
  CALL LOAD (ILUN_IN, YLPHY0%RACCEF)
  CALL LOAD (ILUN_IN, YLPHY0%RAGGEF)
  CALL LOAD (ILUN_IN, YLPHY0%RAUTEFR)
  CALL LOAD (ILUN_IN, YLPHY0%RAUTEFS)
  CALL LOAD (ILUN_IN, YLPHY0%RAUTSBET)
  CALL LOAD (ILUN_IN, YLPHY0%RDTFAC)
  CALL LOAD (ILUN_IN, YLPHY0%REFLCAPE)
  CALL LOAD (ILUN_IN, YLPHY0%RENTRMOD)
  CALL LOAD (ILUN_IN, YLPHY0%RETAMIN)
  CALL LOAD (ILUN_IN, YLPHY0%REVASX)
  CALL LOAD (ILUN_IN, YLPHY0%RFACNSM)
  CALL LOAD (ILUN_IN, YLPHY0%RHCRIT1)
  CALL LOAD (ILUN_IN, YLPHY0%RHCRIT2)
  CALL LOAD (ILUN_IN, YLPHY0%RKDN)
  CALL LOAD (ILUN_IN, YLPHY0%RNEBCX)
  CALL LOAD (ILUN_IN, YLPHY0%RNINTR)
  CALL LOAD (ILUN_IN, YLPHY0%RNINTS)
  CALL LOAD (ILUN_IN, YLPHY0%RQCRNS)
  CALL LOAD (ILUN_IN, YLPHY0%RQICRMAX)
  CALL LOAD (ILUN_IN, YLPHY0%RQICRMIN)
  CALL LOAD (ILUN_IN, YLPHY0%RQICRSN)
  CALL LOAD (ILUN_IN, YLPHY0%RQICRT1)
  CALL LOAD (ILUN_IN, YLPHY0%RQICRT2)
  CALL LOAD (ILUN_IN, YLPHY0%RQLCR)
  CALL LOAD (ILUN_IN, YLPHY0%RRIMEF)
  CALL LOAD (ILUN_IN, YLPHY0%RSMOOTHMELT)
  CALL LOAD (ILUN_IN, YLPHY0%SCO)
  CALL LOAD (ILUN_IN, YLPHY0%TCA)
  CALL LOAD (ILUN_IN, YLPHY0%TCW)
  CALL LOAD (ILUN_IN, YLPHY0%TDDGP)
  CALL LOAD (ILUN_IN, YLPHY0%TENTR)
  CALL LOAD (ILUN_IN, YLPHY0%TENTRX)
  CALL LOAD (ILUN_IN, YLPHY0%TEQC)
  CALL LOAD (ILUN_IN, YLPHY0%TEQH)
  CALL LOAD (ILUN_IN, YLPHY0%TFVI)
  CALL LOAD (ILUN_IN, YLPHY0%TFVL)
  CALL LOAD (ILUN_IN, YLPHY0%TFVR)
  CALL LOAD (ILUN_IN, YLPHY0%TFVS)
  CALL LOAD (ILUN_IN, YLPHY0%THPCMT)
  CALL LOAD (ILUN_IN, YLPHY0%TUDGP)
  CALL LOAD (ILUN_IN, YLPHY0%TVFC)
  CALL LOAD (ILUN_IN, YLPHY0%VVN)
  CALL LOAD (ILUN_IN, YLPHY0%VVX)
  CALL LOAD (ILUN_IN, YLPHY0%WCAPEMOD)

  YRPHY0 = YLPHY0

END SUBROUTINE
SUBROUTINE LOAD_YOMPHY1
USE YOMPHY1
  TYPE(TPHY1) :: YLPHY1
  CALL LOAD (ILUN_IN, YLPHY1%TMERGL)
  YRPHY1 = YLPHY1
END SUBROUTINE
SUBROUTINE LOAD_YOMPHY2
USE YOMPHY2
  TYPE(TPHY2) :: YLPHY2
  CALL LOAD (ILUN_IN, YLPHY2%TSPHY)
  YRPHY2 = YLPHY2
END SUBROUTINE
SUBROUTINE LOAD_YOMRIP
USE YOMRIP
  TYPE(TRIP) :: YLRIP
  CALL LOAD (ILUN_IN, YLRIP%RSTATI)
  YRRIP = YLRIP
END SUBROUTINE
SUBROUTINE LOAD_YOMSCM
USE YOMSCM
  INTEGER(KIND=JPIM) :: INFRSCM
  CALL LOAD (ILUN_IN, INFRSCM)
  NFRSCM = INFRSCM
END SUBROUTINE
SUBROUTINE LOAD_YOMTOPH
USE YOMTOPH
  TYPE(TTOPH) :: YLTOPH
  CALL LOAD (ILUN_IN, YLTOPH%NTCVIM)
  YRTOPH = YLTOPH
END SUBROUTINE
END SUBROUTINE ACPCMT_LOAD_ALL
