SUBROUTINE ACPCMT_LOAD_ALL
USE LOAD_MOD, ONLY : OPEN_LOAD, CLOSE_LOAD, ILUN_IN, LOAD
  CALL OPEN_LOAD ("ACPCMT")
  CALL LOAD_YEMGEO
  CALL LOAD_YOMCAPE
  CALL LOAD_YOMCST
  CALL LOAD_YOMCT0
  CALL LOAD_YOMCT3
  CALL LOAD_YOMDIM
  CALL LOAD_YOMFPC
  CALL LOAD_YOMGEM
  CALL LOAD_YOMPHY
  CALL LOAD_YOMPHY0
  CALL LOAD_YOMPHY1
  CALL LOAD_YOMPHY2
  CALL LOAD_YOMRIP
  CALL LOAD_YOMSCM
  CALL LOAD_YOMTOPH
  CALL CLOSE_LOAD

CONTAINS
SUBROUTINE LOAD_YEMGEO
USE YEMGEO
  CALL LOAD (ILUN_IN, YREGEO%EDELX)
  CALL LOAD (ILUN_IN, YREGEO%EDELY)
END SUBROUTINE
SUBROUTINE LOAD_YOMCAPE
USE YOMCAPE
  CALL LOAD (ILUN_IN, GCAPERET)
  CALL LOAD (ILUN_IN, NCAPEITER)
  CALL LOAD (ILUN_IN, NETAPES)
END SUBROUTINE
SUBROUTINE LOAD_YOMCST
USE YOMCST
  CALL LOAD (ILUN_IN, RA)
  CALL LOAD (ILUN_IN, RALPD)
  CALL LOAD (ILUN_IN, RALPS)
  CALL LOAD (ILUN_IN, RALPW)
  CALL LOAD (ILUN_IN, RATM)
  CALL LOAD (ILUN_IN, RBETD)
  CALL LOAD (ILUN_IN, RBETS)
  CALL LOAD (ILUN_IN, RBETW)
  CALL LOAD (ILUN_IN, RCPD)
  CALL LOAD (ILUN_IN, RCPV)
  CALL LOAD (ILUN_IN, RCS)
  CALL LOAD (ILUN_IN, RCW)
  CALL LOAD (ILUN_IN, RD)
  CALL LOAD (ILUN_IN, RDAY)
  CALL LOAD (ILUN_IN, RDT)
  CALL LOAD (ILUN_IN, REA)
  CALL LOAD (ILUN_IN, REPSM)
  CALL LOAD (ILUN_IN, RETV)
  CALL LOAD (ILUN_IN, RG)
  CALL LOAD (ILUN_IN, RGAMD)
  CALL LOAD (ILUN_IN, RGAMS)
  CALL LOAD (ILUN_IN, RGAMW)
  CALL LOAD (ILUN_IN, RKAPPA)
  CALL LOAD (ILUN_IN, RLSTT)
  CALL LOAD (ILUN_IN, RLVTT)
  CALL LOAD (ILUN_IN, RPI)
  CALL LOAD (ILUN_IN, RTT)
  CALL LOAD (ILUN_IN, RV)
END SUBROUTINE
SUBROUTINE LOAD_YOMCT0
USE YOMCT0
  CALL LOAD (ILUN_IN, LELAM)
END SUBROUTINE
SUBROUTINE LOAD_YOMCT3
USE YOMCT3
  CALL LOAD (ILUN_IN, NSTEP)
END SUBROUTINE
SUBROUTINE LOAD_YOMDIM
USE YOMDIM
  CALL LOAD (ILUN_IN, YRDIM%NDLON)
  CALL LOAD (ILUN_IN, YRDIM%NSMAX)
END SUBROUTINE
SUBROUTINE LOAD_YOMFPC
USE YOMFPC
  CALL LOAD (ILUN_IN, RENTRA)
END SUBROUTINE
SUBROUTINE LOAD_YOMGEM
USE YOMGEM
  CALL LOAD (ILUN_IN, YRGEM%RDELXN)
END SUBROUTINE
SUBROUTINE LOAD_YOMPHY
USE YOMPHY
  CALL LOAD (ILUN_IN, YRPHY%LCOLLEC)
  CALL LOAD (ILUN_IN, YRPHY%LCVPPKF)
  CALL LOAD (ILUN_IN, YRPHY%LEDKF)
  CALL LOAD (ILUN_IN, YRPHY%LEVAPP)
  CALL LOAD (ILUN_IN, YRPHY%LNEBNXR)
  CALL LOAD (ILUN_IN, YRPHY%LNEIGE)
  CALL LOAD (ILUN_IN, YRPHY%LQXRTGH)
  CALL LOAD (ILUN_IN, YRPHY%LSMOOTHMELT)
  CALL LOAD (ILUN_IN, YRPHY%NBITER)
  CALL LOAD (ILUN_IN, YRPHY%NPHYREP)
END SUBROUTINE
SUBROUTINE LOAD_YOMPHY0
USE YOMPHY0
  CALL LOAD (ILUN_IN, YRPHY0%ADOE)
  CALL LOAD (ILUN_IN, YRPHY0%ALFX)
  CALL LOAD (ILUN_IN, YRPHY0%ALFX_HR)
  CALL LOAD (ILUN_IN, YRPHY0%ALFX_LR)
  CALL LOAD (ILUN_IN, YRPHY0%ECMNP)
  CALL LOAD (ILUN_IN, YRPHY0%FENTRT)
  CALL LOAD (ILUN_IN, YRPHY0%FEVAPC)
  CALL LOAD (ILUN_IN, YRPHY0%FNEBC)
  CALL LOAD (ILUN_IN, YRPHY0%FQLIC)
  CALL LOAD (ILUN_IN, YRPHY0%GALMAX)
  CALL LOAD (ILUN_IN, YRPHY0%GALMIN)
  CALL LOAD (ILUN_IN, YRPHY0%GALTAU)
  CALL LOAD (ILUN_IN, YRPHY0%GAMAP1)
  CALL LOAD (ILUN_IN, YRPHY0%GCHI0)
  CALL LOAD (ILUN_IN, YRPHY0%GCLOEB)
  CALL LOAD (ILUN_IN, YRPHY0%GCVADET)
  CALL LOAD (ILUN_IN, YRPHY0%GCVADS)
  CALL LOAD (ILUN_IN, YRPHY0%GCVCINC)
  CALL LOAD (ILUN_IN, YRPHY0%GCVENTRN)
  CALL LOAD (ILUN_IN, YRPHY0%GCVENTRX)
  CALL LOAD (ILUN_IN, YRPHY0%GCVENTR_MIN)
  CALL LOAD (ILUN_IN, YRPHY0%GCVEZ)
  CALL LOAD (ILUN_IN, YRPHY0%GCVFNEO)
  CALL LOAD (ILUN_IN, YRPHY0%GCVFNEP1)
  CALL LOAD (ILUN_IN, YRPHY0%GCVFNEP2)
  CALL LOAD (ILUN_IN, YRPHY0%GCVFNER)
  CALL LOAD (ILUN_IN, YRPHY0%GCVFRR)
  CALL LOAD (ILUN_IN, YRPHY0%GCVGQX)
  CALL LOAD (ILUN_IN, YRPHY0%GCVRE)
  CALL LOAD (ILUN_IN, YRPHY0%GCVRESN)
  CALL LOAD (ILUN_IN, YRPHY0%GCVRESX)
  CALL LOAD (ILUN_IN, YRPHY0%GCVTEXC)
  CALL LOAD (ILUN_IN, YRPHY0%GCVTRMIN)
  CALL LOAD (ILUN_IN, YRPHY0%GCVUV)
  CALL LOAD (ILUN_IN, YRPHY0%GCVWEXC)
  CALL LOAD (ILUN_IN, YRPHY0%GDDSDE)
  CALL LOAD (ILUN_IN, YRPHY0%GDEPTH)
  CALL LOAD (ILUN_IN, YRPHY0%GEXPKD)
  CALL LOAD (ILUN_IN, YRPHY0%GFRIC)
  CALL LOAD (ILUN_IN, YRPHY0%GFSURF)
  CALL LOAD (ILUN_IN, YRPHY0%GINSTX)
  CALL LOAD (ILUN_IN, YRPHY0%GKEDDRE)
  CALL LOAD (ILUN_IN, YRPHY0%GMUKEDD)
  CALL LOAD (ILUN_IN, YRPHY0%GNHACC)
  CALL LOAD (ILUN_IN, YRPHY0%GNHDEV)
  CALL LOAD (ILUN_IN, YRPHY0%GNHDSMOS)
  CALL LOAD (ILUN_IN, YRPHY0%GNHDSMOW)
  CALL LOAD (ILUN_IN, YRPHY0%GNHDTAU)
  CALL LOAD (ILUN_IN, YRPHY0%GPRONI)
  CALL LOAD (ILUN_IN, YRPHY0%GRBCC)
  CALL LOAD (ILUN_IN, YRPHY0%GREDDRS)
  CALL LOAD (ILUN_IN, YRPHY0%GREMAX)
  CALL LOAD (ILUN_IN, YRPHY0%GREMIN)
  CALL LOAD (ILUN_IN, YRPHY0%GRHCMOD)
  CALL LOAD (ILUN_IN, YRPHY0%GSDAMAX)
  CALL LOAD (ILUN_IN, YRPHY0%GSDAMIN)
  CALL LOAD (ILUN_IN, YRPHY0%GSDMAX)
  CALL LOAD (ILUN_IN, YRPHY0%GSDMIN)
  CALL LOAD (ILUN_IN, YRPHY0%GSHELL)
  CALL LOAD (ILUN_IN, YRPHY0%GSIGA)
  CALL LOAD (ILUN_IN, YRPHY0%GSINHD)
  CALL LOAD (ILUN_IN, YRPHY0%GSINHR)
  CALL LOAD (ILUN_IN, YRPHY0%GTDCL)
  CALL LOAD (ILUN_IN, YRPHY0%GUDDD)
  CALL LOAD (ILUN_IN, YRPHY0%LADVLIM)
  CALL LOAD (ILUN_IN, YRPHY0%LCVCONTAU)
  CALL LOAD (ILUN_IN, YRPHY0%LCVEOD)
  CALL LOAD (ILUN_IN, YRPHY0%LCVIMPT)
  CALL LOAD (ILUN_IN, YRPHY0%LCVMICC)
  CALL LOAD (ILUN_IN, YRPHY0%LCVNAUV)
  CALL LOAD (ILUN_IN, YRPHY0%LCVNHD)
  CALL LOAD (ILUN_IN, YRPHY0%LCVTADV)
  CALL LOAD (ILUN_IN, YRPHY0%LCVUVM)
  CALL LOAD (ILUN_IN, YRPHY0%LGDDD)
  CALL LOAD (ILUN_IN, YRPHY0%LGPRONI1)
  CALL LOAD (ILUN_IN, YRPHY0%LGVVEX)
  CALL LOAD (ILUN_IN, YRPHY0%LSBUO)
  CALL LOAD (ILUN_IN, YRPHY0%NCAPEMOD)
  CALL LOAD (ILUN_IN, YRPHY0%NCVCLOS)
  CALL LOAD (ILUN_IN, YRPHY0%NCVENTR)
  CALL LOAD (ILUN_IN, YRPHY0%NCVQLI)
  CALL LOAD (ILUN_IN, YRPHY0%NCVSIG)
  CALL LOAD (ILUN_IN, YRPHY0%NPRONI)
  CALL LOAD (ILUN_IN, YRPHY0%QXRAL)
  CALL LOAD (ILUN_IN, YRPHY0%QXRDEL)
  CALL LOAD (ILUN_IN, YRPHY0%QXRHX)
  CALL LOAD (ILUN_IN, YRPHY0%QXRR)
  CALL LOAD (ILUN_IN, YRPHY0%QXRTGH)
  CALL LOAD (ILUN_IN, YRPHY0%RACCEF)
  CALL LOAD (ILUN_IN, YRPHY0%RAGGEF)
  CALL LOAD (ILUN_IN, YRPHY0%RAUTEFR)
  CALL LOAD (ILUN_IN, YRPHY0%RAUTEFS)
  CALL LOAD (ILUN_IN, YRPHY0%RAUTSBET)
  CALL LOAD (ILUN_IN, YRPHY0%RDTFAC)
  CALL LOAD (ILUN_IN, YRPHY0%REFLCAPE)
  CALL LOAD (ILUN_IN, YRPHY0%RENTRMOD)
  CALL LOAD (ILUN_IN, YRPHY0%RETAMIN)
  CALL LOAD (ILUN_IN, YRPHY0%REVASX)
  CALL LOAD (ILUN_IN, YRPHY0%RFACNSM)
  CALL LOAD (ILUN_IN, YRPHY0%RHCRIT1)
  CALL LOAD (ILUN_IN, YRPHY0%RHCRIT2)
  CALL LOAD (ILUN_IN, YRPHY0%RKDN)
  CALL LOAD (ILUN_IN, YRPHY0%RNEBCX)
  CALL LOAD (ILUN_IN, YRPHY0%RNINTR)
  CALL LOAD (ILUN_IN, YRPHY0%RNINTS)
  CALL LOAD (ILUN_IN, YRPHY0%RQCRNS)
  CALL LOAD (ILUN_IN, YRPHY0%RQICRMAX)
  CALL LOAD (ILUN_IN, YRPHY0%RQICRMIN)
  CALL LOAD (ILUN_IN, YRPHY0%RQICRSN)
  CALL LOAD (ILUN_IN, YRPHY0%RQICRT1)
  CALL LOAD (ILUN_IN, YRPHY0%RQICRT2)
  CALL LOAD (ILUN_IN, YRPHY0%RQLCR)
  CALL LOAD (ILUN_IN, YRPHY0%RRIMEF)
  CALL LOAD (ILUN_IN, YRPHY0%RSMOOTHMELT)
  CALL LOAD (ILUN_IN, YRPHY0%SCO)
  CALL LOAD (ILUN_IN, YRPHY0%TCA)
  CALL LOAD (ILUN_IN, YRPHY0%TCW)
  CALL LOAD (ILUN_IN, YRPHY0%TDDGP)
  CALL LOAD (ILUN_IN, YRPHY0%TENTR)
  CALL LOAD (ILUN_IN, YRPHY0%TENTRX)
  CALL LOAD (ILUN_IN, YRPHY0%TEQC)
  CALL LOAD (ILUN_IN, YRPHY0%TEQH)
  CALL LOAD (ILUN_IN, YRPHY0%TFVI)
  CALL LOAD (ILUN_IN, YRPHY0%TFVL)
  CALL LOAD (ILUN_IN, YRPHY0%TFVR)
  CALL LOAD (ILUN_IN, YRPHY0%TFVS)
  CALL LOAD (ILUN_IN, YRPHY0%THPCMT)
  CALL LOAD (ILUN_IN, YRPHY0%TUDGP)
  CALL LOAD (ILUN_IN, YRPHY0%TVFC)
  CALL LOAD (ILUN_IN, YRPHY0%VVN)
  CALL LOAD (ILUN_IN, YRPHY0%VVX)
  CALL LOAD (ILUN_IN, YRPHY0%WCAPEMOD)
END SUBROUTINE
SUBROUTINE LOAD_YOMPHY1
USE YOMPHY1
  CALL LOAD (ILUN_IN, YRPHY1%TMERGL)
END SUBROUTINE
SUBROUTINE LOAD_YOMPHY2
USE YOMPHY2
  CALL LOAD (ILUN_IN, YRPHY2%TSPHY)
END SUBROUTINE
SUBROUTINE LOAD_YOMRIP
USE YOMRIP
  CALL LOAD (ILUN_IN, YRRIP%RSTATI)
END SUBROUTINE
SUBROUTINE LOAD_YOMSCM
USE YOMSCM
  CALL LOAD (ILUN_IN, NFRSCM)
END SUBROUTINE
SUBROUTINE LOAD_YOMTOPH
USE YOMTOPH
  CALL LOAD (ILUN_IN, YRTOPH%NTCVIM)
END SUBROUTINE
END SUBROUTINE ACPCMT_LOAD_ALL
