#include "attr.h"
SUBROUTINE ACPCMT ( KIDIA,KFDIA,KLON,KTDIA,KLEV,KTRA,&
  & PALPH,PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PLH,PR,&
  & PDELP,PLNPR,&
  & PQ,PQI,PQL,PRR,PS,PQLIS,PQSAT,PQW,&
  & PRDELP,PCVGQ,PT,PTW,PU,PV,PTKE,PTRA,&
  & PQLCONV, PQICONV , PQRCONV, PQSCONV, &
  ! - INPUT 1D .
  & PGM, PTS, PQS, PNEIJ, PLSM, PVETAF, &
  ! - OUTPUT 2D .
  & PDIFCQ,PDIFCQL,PDIFCQI,PDIFCQLC,PDIFCQIC,PDIFCS,PDIFCTH,&
  & PFCCQL,PFCCQN,PSTRCU,PSTRCV,PSTRCTRA,&
  & PFIMCC,PFPEVPCL,PFPEVPCN,&
  & PFPLCL,PFPLCN,PMF_UP,&
  & PFPFPCL,PFPFPCN,&
  & PFEDQLC, PFEDQIC, PFEDQRC, PFEDQSC,&
  & PFCNEGQLC,PFCNEGQIC,PFCNEGQRC,PFCNEGQSC, &
  & KNLAB,&
  & PNEBC,PQLIC,PTU,PQU,PQC_DET_PCMT,PCSGC, &
  ! - OUTPUT 1D .
  & KNND, PCAPE,PAIPCMT,PALF_CAPE,PALF_CVGQ,&
  ! - INPUT/OUTPUT 2D .
  & PUDAL,PUDOM,PDDAL,PDDOM, &
  & KSTACK, PSTACK, KPSTSZ, KKSTSZ, KPSTPT, KKSTPT)


USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTRA

REAL(KIND=JPRB), INTENT(IN)    :: PALPH(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PCP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PLH(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PR(KLON,KLEV)

REAL(KIND=JPRB), INTENT(IN)    :: PDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PLNPR(KLON,KLEV)

REAL(KIND=JPRB), INTENT(IN)    :: PQ(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQI(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PRR(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQLIS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQW(KLON,KLEV)

REAL(KIND=JPRB), INTENT(IN)    :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PCVGQ(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PTW(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PTKE(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PTRA(KLON, KLEV, KTRA)

REAL(KIND=JPRB), INTENT(IN)    :: PQLCONV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQICONV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQRCONV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN)    :: PQSCONV(KLON,KLEV)

REAL(KIND=JPRB), INTENT(IN)    :: PGM(KLON)
REAL(KIND=JPRB), INTENT(IN)    :: PTS(KLON)
REAL(KIND=JPRB), INTENT(IN)    :: PQS(KLON)
REAL(KIND=JPRB), INTENT(IN)    :: PNEIJ(KLON)
REAL(KIND=JPRB), INTENT(IN)    :: PLSM(KLON)
REAL(KIND=JPRB), INTENT(IN)    :: PVETAF(KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQ(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQLC(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQIC(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCTH(KLON,0:KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQN(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCU(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCV(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PMF_UP(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCTRA(KLON, 0:KLEV, KTRA)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFIMCC(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCN(KLON,0:KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCN(KLON,0:KLEV)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFPFPCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPFPCN(KLON,0:KLEV)

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQLC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQIC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQRC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQSC(KLON,0:KLEV)

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQLC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQIC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQRC(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQSC(KLON,0:KLEV)

INTEGER(KIND=JPIM), INTENT(INOUT) :: KNLAB(KLON,KLEV)
INTEGER(KIND=JPIM), INTENT(INOUT) :: KNND(KLON)

REAL(KIND=JPRB), INTENT(OUT)   :: PNEBC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQLIC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PTU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PQC_DET_PCMT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT)   :: PCSGC(KLON,KLEV)

REAL(KIND=JPRB), INTENT(OUT)   :: PCAPE(KLON)
REAL(KIND=JPRB), INTENT(OUT)   :: PAIPCMT(KLON)

REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CAPE(KLON)
REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CVGQ(KLON)

REAL(KIND=JPRB), INTENT(INOUT) :: PUDAL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PUDOM(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDAL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDOM(KLON,KLEV)
REAL(KIND=JPRB),   INTENT(OUT)   :: PSTACK (KLON, KPSTSZ)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSTACK (KLON, KKSTSZ)
INTEGER(KIND=JPIM),INTENT(IN)    :: KPSTSZ, KKSTSZ, KPSTPT, KKSTPT


! LOCALS.

REAL(KIND=JPRB)   :: ZTCVIM
REAL(KIND=JPRB)   :: ZICE

REAL(KIND=JPRB)   :: ZQLCONVPREC

INTEGER(KIND=JPIM) :: JLEV,JLON,INEBC,IQLIC,IQLIC_MICRO,JTRA
REAL(KIND=JPRB) :: ZCCHSL,ZCCHSN,ZEPS


REAL(KIND=JPRB) :: ZFRACP,ZTH

LOGICAL         :: LLADJCLD
INTEGER(KIND=JPIM) :: IPSTPT_ZALF

INTEGER(KIND=JPIM) :: IPSTPT_ZSU

INTEGER(KIND=JPIM) :: IPSTPT_ZEVAPO

INTEGER(KIND=JPIM) :: IPSTPT_ZQMIC

INTEGER(KIND=JPIM) :: IPSTPT_ZTMIC

INTEGER(KIND=JPIM) :: IPSTPT_ZTMPVAR

INTEGER(KIND=JPIM) :: IPSTPT_ZDEPTH

INTEGER(KIND=JPIM) :: IPSTPT_ZQ_COND_XR96

INTEGER(KIND=JPIM) :: IPSTPT_ZQICED

INTEGER(KIND=JPIM) :: IPSTPT_ZQLCED

INTEGER(KIND=JPIM) :: IPSTPT_ZDAL

INTEGER(KIND=JPIM) :: IPSTPT_ZNEBC_MICRO

INTEGER(KIND=JPIM) :: IPSTPT_ZQLIC_MICRO

INTEGER(KIND=JPIM) :: IPSTPT_ZFHMLTSC

INTEGER(KIND=JPIM) :: IPSTPT_ZFHEVPPC

INTEGER(KIND=JPIM) :: IPSTPT_ZFCCQNTMP

INTEGER(KIND=JPIM) :: IPSTPT_ZW_CONV

INTEGER(KIND=JPIM) :: IPSTPT_ZW_COMPENS

INTEGER(KIND=JPIM) :: IPSTPT_ZQLC

INTEGER(KIND=JPIM) :: IPSTPT_ZUDW

INTEGER(KIND=JPIM) :: IPSTPT_ZQIC

INTEGER(KIND=JPIM) :: IPSTPT_ZQSC

INTEGER(KIND=JPIM) :: IPSTPT_ZFCCQLTMP

INTEGER(KIND=JPIM) :: IPSTPT_ZDETR_D

INTEGER(KIND=JPIM) :: IPSTPT_ZENTR_D

INTEGER(KIND=JPIM) :: IPSTPT_ZDETR_D_RS

INTEGER(KIND=JPIM) :: IPSTPT_ZDETR_U_RS

INTEGER(KIND=JPIM) :: IPSTPT_ZDETR_U

INTEGER(KIND=JPIM) :: IPSTPT_ZENTR_U

INTEGER(KIND=JPIM) :: IPSTPT_ZUDQC

INTEGER(KIND=JPIM) :: IPSTPT_ZDDW

INTEGER(KIND=JPIM) :: IPSTPT_ZQRC

INTEGER(KIND=JPIM) :: IPSTPT_ZEROV

INTEGER(KIND=JPIM) :: IPSTPT, IKSTPT


#include "acmtud.intfb.h"




IPSTPT = KPSTPT

IKSTPT = KKSTPT

IPSTPT_ZEROV = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQRC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDDW = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZUDQC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZENTR_U = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDETR_U = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDETR_U_RS = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDETR_D_RS = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZENTR_D = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDETR_D = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZFCCQLTMP = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZQSC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQIC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZUDW = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQLC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZW_COMPENS = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZW_CONV = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZFCCQNTMP = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZFHEVPPC = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZFHMLTSC = IPSTPT

IPSTPT = IPSTPT + KLEV-0+1

IPSTPT_ZQLIC_MICRO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZNEBC_MICRO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDAL = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQLCED = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQICED = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQ_COND_XR96 = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZDEPTH = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTMPVAR = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZTMIC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQMIC = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZEVAPO = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZSU = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZALF = IPSTPT

IPSTPT = IPSTPT + 1

CALL ACMTUD ( KIDIA,KFDIA,KLON,KTDIA,KLEV,KTRA, &
& PAPRSF, PR, PT, PQLIC, PUDOM, PSTACK, KPSTSZ, IPSTPT)

END SUBROUTINE
