!-----------------------------------------------------------------------
!$acc routine (ACPLUIZ) seq
SUBROUTINE ACPLUIZ( KIDIA, KFDIA, KLON, KTDIA, KLEV,&
 !-----------------------------------------------------------------------
 ! - INPUT -
 & PT, PQ, PQL, PQI, PQR, PQS,&
 & PDELP, PAPRSF, PCP, PR, PNEBS, PQCS, PNEB_CVPP, PQLI_CVPP,PQC_DET_PCMT,&
 & PTENDH, PTENDQ, LDADJCLD, PAPHI,&
 & PTS, PNEIJ, PLSM, PGM, PVETAF,&
 ! - OUTPUT -
 & PFCSQL, PFCSQN, PFPLSL, PFPLSN,&
 & PFPEVPL, PFPEVPN, PFPFPL, PFPFPN, PSEDIQL, PSEDIQN,KSTPT,KSTSZ,PSTACK )


#include "temp.h"

!**** *ACPLUIZ * - PROGNOSTIC CLOUD SCMEME (LOPEZ)

!**   Interface.
!     ----------
!        *CALL* *ACPLUIZ*

!-----------------------------------------------------------------------

! -   ARGUMENTS D'ENTREE./INPUT ARGUMENTS.
!     ------------------------------------

! - NOM DES PARAMETRES DE DIMENSIONNEMENT DE LA PHYSIQUE.

! KIDIA      : INDICE DE DEPART DES BOUCLES VECTORISEES SUR L'HORIZONT..
!            : START OF HORIZONTAL LOOP 
! KFDIA      : INDICE DE FIN DES BOUCLES VECTORISEES SUR L'HORIZONTALE.
!            : END OF HORIZONTAL LOOP
! KLON       : DIMENSION HORIZONTALE DES TABLEAUX.
!            : HORIZONTAL DIMENSION  
! KTDIA      : INDICE DE DEPART DES BOUCLES VERTICALES. 
!            : START OF THE VERTICAL LOOP IN THE PHYSICS. 
! KLEV       : DIMENSION VERTICALE DES TABLEAUX "FULL LEVEL".
!            : END OF VERTICAL LOOP AND VERTICAL DIMENSION

! - 2D (1:KLEV)

! PT         : TEMPERATURE.
!            : TEMPERATURE.
! PQ         : HUMIDITE SPECIFIQUE DE LA VAPEUR D'EAU.
!            : SPECIFIC HUMIDITY OF WATER VAPOUR.
! PQL        : HUMIDITE SPECIFIQUE DE L'EAU CONDENSEE LIQUIDE.
!            : SPECIFIC HUMIDITY OF LIQUID CONDENSATED WATER.
! PQI        : HUMIDITE SPECIFIQUE DE L'EAU CONDENSEE GLACE.
!            : SPECIFIC HUMIDITY OF SOLID CONDENSATED WATER.
! PQR        : PRECIPITATIONS LIQUIDES.
!            : LIQUID PECIPITATIONS.
! PQS        : PRECIPITATIONS SOLIDES.
!            : SOLID PECIPITATIONS.
! PDELP      : EPAISSEUR EN PRESSION DE LA COUCHE.
!            : LAYER THICKNESS IN PRESSURE UNITS.  
! PAPRSF     : PRESSION AUX NIVEAUX DES COUCHES.
!            : PRESSURE ON FULL LEVELS.
! PCP        : CHALEUR MASSIQUE A PRESSION CONSTANTE DE L'AIR.
!            : SPECIFIC HEAT AT CONSTANT PRESSURE FOR AIR.
! PR         : CONSTANTE DES GAZ POUR L'AIR.
!            : GAS CONSTANT FOR AIR.
! PNEBS      : NEBULOSITE PARTIELLE STRATIFORME.
!            : STRATIFORM FRACTIONAL CLOUDINESS.
! PQCS       : CONTENU "STRATIFORME" EN CONDENSAT NUAGEUX (LIQ. + SOL.).
!            : STRATIRORM CLOUD WATER (LIQUID + SOLID).
! PNEB_CVPP  : NEBULOSITE PARTIELLE CONVECTION PEU PROFONDE.
!            : SHALLOW CONVECTION FRACTIONAL CLOUDINESS.
! PQLI_CVPP  : CONTENU "CVPP" EN CONDENSAT NUAGEUX (LIQ. + SOL.).
!            : SHALLOW CONVECTION CLOUD WATER (LIQUID + SOLID).
! PQC_DET_PCMT: CONTENU EN CONDENSAT NUAGEUX DETRAINE PAR PCMT (LIQ. + SOL.).
!            : DEEP CONVECTION DETRAINED CLOUD WATER (LIQUID + SOLID).
! PTENDH     : TENDANCE D'ENTHALPIE.
!            : ENTHALPY TENDENCY.
! PTENDQ     : TENDANCE D'HUMIDITE SPECIFIQUE.
!            : SPECIFIC HUMIDITY TENDENCY.

! - 2D (0:KLEV)

! PAPHI      : GEOPOTENTIEL SUR DEMI-NIVEAUX.
!            : GEOPOTENTIAL ON HALF-LEVELS.

! - 1D (1:KLON) .
                                                                                
! PTS        : TEMPERATURE DE SURFACE.
!            : SURFACE TEMPERATURE.
! PNEIJ      : PROPORTION DE LA MAILLE RECOUVERTE DE NEIGE.
!            : SNOW FRACTION.
! PLSM       : INDICE TERRE/MER.
!            : LAND/SEA MASK.
! PGM        : FACTEUR D'ECHELLE.
!            : MAPPING FACTOR.
! PVETAF     : COORDONNEE VERTICALE ETA.
!            : VERTICAL COORDINATE ETA.

!-----------------------------------------------------------------------

! -   ARGUMENTS EN SORTIE.
!     ---------------------------

! - 2D (0:KLEV) .

! PFCSQN     : FLUX DE CONDENSATION LIE AUX RR STRATIFORMES NEIGEUSES.
!            : STRATIFORM CONDENSATION FLUX FOR ICE.
! PFCSQL     : FLUX DE CONDENSATION LIE AUX RR STRATIFORMES LIQUIDES.
!            : STRATIFORM CONDENSATION FLUX FOR LIQUID WATER.
! PFPLSL     : FLUX DE PRECIPITATION LIQUIDE (PLUIE).
!            : RAIN FLUX.
! PFPLSN     : FLUX DE PRECIPITATION SOLIDE  (NEIGE).
!            : ICE PRECIPITATION FLUX.
! PFPEVPL    : FLUX ASSOCIE A L'EVAPORATION DES PRECIP.
!            : FLUX ASSOCIATED TO EVAPORATION OF PRECIPITATIONS.
! PFPEVPN    : FLUX ASSOCIE A LA SUBLIMATION DES PRECIP.
!            : FLUX ASSOCIATED TO SUBLIMATION OF PRECIPITATIONS.
! PFPFPL     : FLUX DE GENERATION DE PRECIPITATIONS LIQUIDES.
!            : FLUX OF LIQUID PRECIPITATION GENERATION.
! PFPFPN     : FLUX DE GENERATION DE PRECIPITATIONS SOLIDES.
!            : FLUX OF SOLID PRECIPITATION GENERATION.
! PSEDIQL    : FLUX SEDIMENTATION D'EAU LIQUIDE NUAGEUSE.
!            : FLUX SEDIMENTATION OF CLOUD LIQUID WATER.
! PSEDIQN    : FLUX SEDIMENTATION D'EAU SOLIDE NUAGEUSE.
!            : FLUX SEDIMENTATION OF CLOUD SOLID WATER.

!-----------------------------------------------------------------------

!     Auteur.
!     -------
!         04-10, Francois Bouyssel

!     Modifications.
!     --------------
!         05-05, F.Bouyssel : Introduction of vertical coordinate eta
!         05-07, F.Bouyssel : New arguments from aplpar to acmicro
!         05-11, F.Bouyssel : Remove ZAUTO,ZQCMIC,ZQPMIC
!         06-01, F.Bouyssel : Introduction of PQS, PFPEVPL, PFPEVPN
!         06-01, F.Bouyssel : Microphysical adjustment at the beginning
!         06-04, F.Bouyssel : Key for Smith's adjustment LADJCLD 
!         06-06, Y.Bouteloup: Statistical sedimentation (ADVPRCS)
!         09-10, F.Bouyssel : Cleaning ADVPRC and ACNEBSM
!         10-04, Y.Bouteloup: No rain production by autoconversion in
!                             case of negative temperature
!         10-07, F.Bouyssel : Bug correction related with ZDPSGDT
!         10-12, F.Bouyssel : Introduction of LADJCLD
!         11-01, F.Bouyssel : Bug correction in case of negative temperature
!       2011-06, M. Jerczynski : some cleaning to meet norms
!       2014-04, JM Piriou : add detrained condensate from PCMT convection
!       2016-06, Y. Bouteloup : adjustment done as a function of a dummy logical argument, instead of global.

!-----------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMPHY    , ONLY : YRPHY
USE YOMPHY0   , ONLY : YRPHY0
USE YOMPHY2   , ONLY : YRPHY2
USE YOMCST    , ONLY : RG   , RTT  , RDT
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMPHY0   , ONLY : YRPHY0
USE YOMPHY1   , ONLY : YRPHY1
USE YOMPHY2   , ONLY : YRPHY2
USE YOMCST    , ONLY : RTT

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KTDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT     (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQ     (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQL    (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQI    (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQR    (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQS    (KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDELP  (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRSF (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCP    (KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PR     (KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PNEBS  (KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PQCS   (KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNEB_CVPP(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQLI_CVPP(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQC_DET_PCMT(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTENDH (KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTENDQ (KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPHI  (KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTS    (KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNEIJ  (KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLSM   (KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGM   (KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVETAF(KLEV)

LOGICAL           ,INTENT(IN)    :: LDADJCLD

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCSQL (KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCSQN (KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPLSL (KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPLSN (KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPEVPL(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPEVPN(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPFPL (KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPFPN (KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSEDIQL(KLON,0:KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSEDIQN(KLON,0:KLEV) 

INTEGER(KIND=JPIM),INTENT(IN)    :: KSTSZ
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTPT
REAL (KIND=JPRB)   ,INTENT(INOUT) :: PSTACK (KSTSZ)

temp (REAL(KIND=JPRB), ZRHCRI, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZRMF, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZQSATS, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZT, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZQ, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZAUTOL, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZAUTOI, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZQL, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZQI, (KLON,KLEV))
temp (REAL(KIND=JPRB), ZFLUXCOR, (KLON,KLEV))

REAL(KIND=JPRB) :: ZDPSGDT,ZICE,ZGDT,ZGDTI,ZIGEL,ZEPS1
INTEGER(KIND=JPIM) :: JLON,JLEV
INTEGER(KIND=JPIM) :: JLON,JLEV
REAL(KIND=JPRB) :: ZAUTOL_ACMI
REAL(KIND=JPRB) :: ZAUTOI_ACMI
REAL(KIND=JPRB) :: ZDELT_ACMI
REAL(KIND=JPRB) :: ZEFFA_ACMI
REAL(KIND=JPRB) :: ZQL_ACMI,ZQI_ACMI,ZCAUT_ACMI,&
 & ZALPH_ACMI,ZDUM_ACMI,ZQCR_ACMI,ZARG1_ACMI,ZARG2_ACMI,ZBETA_ACMI,ZFACICE_ACMI

#include "abor1.intfb.h"
#include "acnebsm.intfb.h"
#include "advprcs.intfb.h"

#include "fctdoi.func.h"

!     ------------------------------------------------------------------

!     CHECK RELIABILITY OF INPUT ARGUMENTS.



!     ------------------------------------------------------------------

! - - - - - - - -
! ADJUSTMENT
! - - - - - - - -

init_stack ()

alloc (ZRHCRI)
alloc (ZRMF)
alloc (ZQSATS)
alloc (ZT)
alloc (ZQ)
alloc (ZAUTOL)
alloc (ZAUTOI)
alloc (ZQL)
alloc (ZQI)
alloc (ZFLUXCOR)



ZEPS1=1.E-12_JPRB

ZGDT=RG*YRPHY2%TSPHY
ZGDTI=1.0_JPRB/ZGDT

! - - - - - - - -
! AUTOCONVERSION
! - - - - - - - -

!     ------------------------------------------------------------------
!     CHECK RELIABILITY OF INPUT ARGUMENTS.
!     ------------------------------------------------------------------
! Define threshold for ice autoconversion as a function of temperature
! --------------------------------------------------------------------

ZARG1_ACMI = 2.0_JPRB*YRPHY0%RQICRMAX*(1.0_JPRB-0.999_JPRB)/(YRPHY0%RQICRMAX-YRPHY0%RQICRMIN)-1.0_JPRB
ZARG2_ACMI = 2.0_JPRB*(YRPHY0%RQICRMAX-1.5_JPRB*YRPHY0%RQICRMIN)/(YRPHY0%RQICRMAX-YRPHY0%RQICRMIN)-1.0_JPRB
ZARG1_ACMI = 0.5_JPRB*LOG(ABS((1.0_JPRB+ZARG1_ACMI)/(1.0_JPRB-ZARG1_ACMI)))
ZARG2_ACMI = 0.5_JPRB*LOG(ABS((1.0_JPRB+ZARG2_ACMI)/(1.0_JPRB-ZARG2_ACMI)))
ZALPH_ACMI = (ZARG1_ACMI - ZARG2_ACMI)/(YRPHY0%RQICRT2-YRPHY0%RQICRT1)
ZBETA_ACMI = ZARG1_ACMI - YRPHY0%RQICRT2 * ZALPH_ACMI
 

JLON = KIDIA

IF ( LDADJCLD ) THEN

  DO JLEV = KTDIA, KLEV
      ZT(JLON,JLEV) = PT(JLON,JLEV)+YRPHY2%TSPHY*PTENDH(JLON,JLEV)/PCP(JLON,JLEV)
      ZQ(JLON,JLEV) = MAX( 0.0_JPRB,PQ(JLON,JLEV)+YRPHY2%TSPHY*PTENDQ(JLON,JLEV) )
  ENDDO

  CALL ACNEBSM ( KIDIA,KFDIA,KLON,KTDIA,KLEV,&
               & ZT,ZQ,PQL,PQI,PAPHI,PAPRSF,PCP,PR,&
               & PGM(JLON),PVETAF,&
               & PQCS,PNEBS,ZRHCRI,ZRMF,ZQSATS,ISTPT,KSTSZ,PSTACK )

ELSE

  DO JLEV = KTDIA, KLEV
      ZT(JLON,JLEV) = PT(JLON,JLEV)
      ZQ(JLON,JLEV) = PQ(JLON,JLEV)
  ENDDO

ENDIF

! CLOUD OVERLAP FOR STRATIFORM AND SHALLOW CLOUDS
! -----------------------------------------------
                                                                                
DO JLEV = KTDIA, KLEV
    ZICE = FONICE(ZT(JLON,JLEV))
    PQCS (JLON,JLEV) = PQCS(JLON,JLEV) + PQLI_CVPP(JLON,JLEV) + PQC_DET_PCMT(JLON,JLEV)
    PNEBS(JLON,JLEV) = MIN(1.0_JPRB-ZEPS1,MAX(PNEBS(JLON,JLEV),ZEPS1))
    PNEBS(JLON,JLEV) = MAX( PNEBS(JLON,JLEV) , PNEB_CVPP(JLON,JLEV) )
    ZQL  (JLON,JLEV) = PQCS(JLON,JLEV)*(1.0_JPRB-ZICE)
    ZQI  (JLON,JLEV) = PQCS(JLON,JLEV)*ZICE

    ZDELT_ACMI = ZT(JLON,JLEV) - RTT

! Efficiency for ice conversion as a function of temperature.
! -----------------------------------------------------------
    ZEFFA_ACMI = EXP(YRPHY0%RAUTSBET*ZDELT_ACMI)

! ---------------------------------------------------
! MICROPHYSICAL AUTOCONVERSION IN THE STRATIFORM CASE
! ---------------------------------------------------

! Compute in-cloud values
! -----------------------

    ZQL_ACMI = MAX(0.0_JPRB,ZQL(JLON,JLEV)/PNEBS(JLON,JLEV))
    ZQI_ACMI = MAX(0.0_JPRB,ZQI(JLON,JLEV)/PNEBS(JLON,JLEV))

! AUTOCONVERSION OF CLOUD LIQUID WATER INTO RAIN
! ----------------------------------------------

    ZCAUT_ACMI = YRPHY0%RAUTEFR
    ZDUM_ACMI = (1.0_JPRB-EXP(-ZCAUT_ACMI*YRPHY2%TSPHY)) * (ZQL_ACMI-YRPHY0%RQLCR) / YRPHY2%TSPHY
    ZAUTOL_ACMI = MAX(0.0_JPRB,ZDUM_ACMI)

! AUTOCONVERSION OF CLOUD ICE INTO PRECIPITATING ICE
! --------------------------------------------------

    ZCAUT_ACMI = YRPHY0%RAUTEFS * ZEFFA_ACMI
    ZQCR_ACMI = YRPHY0%RQICRMAX - (YRPHY0%RQICRMAX - YRPHY0%RQICRMIN) * 0.5_JPRB &
     & * (1.0_JPRB + TANH(ZALPH_ACMI * ZDELT_ACMI + ZBETA_ACMI))
    ZFACICE_ACMI = PLSM(JLON)*PNEIJ(JLON) + (1.0_JPRB-PLSM(JLON)) &
     & * MAX(0.0_JPRB,SIGN(1.0_JPRB,YRPHY1%TMERGL-PTS(JLON)))
    ZQCR_ACMI = ZQCR_ACMI * (1.0_JPRB-ZFACICE_ACMI*(1.0_JPRB-YRPHY0%RQICRSN))
    ZDUM_ACMI = (1.0_JPRB-EXP(-ZCAUT_ACMI*YRPHY2%TSPHY)) * (ZQI_ACMI-ZQCR_ACMI) / YRPHY2%TSPHY
    ZAUTOI_ACMI = MAX(0.0_JPRB,ZDUM_ACMI)
 
! TOTAL AUTOCONVERSION TERM
! -------------------------

    ZAUTOL(JLON,JLEV) = ZAUTOL_ACMI * PNEBS(JLON,JLEV)
    ZAUTOI(JLON,JLEV) = ZAUTOI_ACMI * PNEBS(JLON,JLEV)

! In case of negative temperature 
! no rain production by autoconversion 
! - - - - - - - - - - - - - - - - - -


    ZDPSGDT  = ZGDTI * PDELP(JLON,JLEV)
    ZIGEL = MAX(0.0_JPRB,SIGN(1.0_JPRB,RTT-PT(JLON,JLEV)))
    ZFLUXCOR(JLON,JLEV) = ZIGEL*ZAUTOL(JLON,JLEV)
    ZAUTOL(JLON,JLEV) = ZAUTOL(JLON,JLEV) - ZFLUXCOR(JLON,JLEV)
    ZAUTOI(JLON,JLEV) = ZAUTOI(JLON,JLEV) + ZFLUXCOR(JLON,JLEV)
    ZQL(JLON,JLEV) = ZQL(JLON,JLEV) - ZFLUXCOR(JLON,JLEV)*YRPHY2%TSPHY
    ZQI(JLON,JLEV) = ZQI(JLON,JLEV) + ZFLUXCOR(JLON,JLEV)*YRPHY2%TSPHY
    PFCSQL(JLON,JLEV) = PFCSQL(JLON,JLEV-1) &
     & + ( ZQL(JLON,JLEV) - PQL(JLON,JLEV) ) * ZDPSGDT
    PFCSQN(JLON,JLEV) = PFCSQN(JLON,JLEV-1) &
     & + ( ZQI(JLON,JLEV) - PQI(JLON,JLEV) ) * ZDPSGDT
ENDDO

! - - - - - - - - - - - - - - - - - - -
! FALLING OF PRECIPITATING PARTICLES,
! COLLECTION AND EVAPORATION PROCESSES.
! - - - - - - - - - - - - - - - - - - -

CALL ADVPRCS ( KIDIA, KFDIA, KLON, KTDIA, KLEV,&
             & ZT, ZQ, ZQL, ZQI, ZAUTOL, ZAUTOI,&
             & PQR, PQS, PNEBS,&
             & PCP, PR, PAPHI, PAPRSF, PDELP,&
             & PFPLSL , PFPLSN, PFPEVPL, PFPEVPN, PFPFPL, PFPFPN,&
             & PSEDIQL, PSEDIQN,ISTPT,KSTSZ,PSTACK )


END SUBROUTINE ACPLUIZ
