SUBROUTINE ADVPRCS (KIDIA, KFDIA, KLON, KTDIA, KFLEV,&
 & PT, PQ, PQL, PQI, PAUTOL, PAUTOI, &
 & PQR, PQS, PNEB, &
 & PCP, PR, PAPHI, PAPRSF, PDELP,&
 & PFPLSL, PFPLSN, PFPEVPL, PFPEVPN, PFPFPL, PFPFPN, PSEDIQL, PSEDIQN, KSTACK, PSTACK, KPSTSZ, KKSTSZ, KPSTPT, KKSTPT )  

! ========================================================

!   THIS ROUTINE PERFORMS THE VERTICAL ADVECTION OF
!   PRECIPITATION PARTICLES.
!   IT ALSO COMPUTES COLLECTION AND EVAPORATION PROCESSES.

! ========================================================

!   Auteur: Yves Bouteloup, CNRM/GMAP FROM ADVPRC

!   Date: 2006-06   

!     Modifications.
!     --------------
!     2006-10-30, F. Bouyssel : Introduction of RHEVAP and ZALPHA
!     2007-04-06, F. Bouyssel : Change in precipitation evaporation (LLEVAPX)
!     2008-01-24, Y. Bouteloup : Change in taking account of the melting (like evaporation for snow !)
! This is very important. Each disparition process for a species must be treated as this
!     2010-04-06, F. Bouyssel : Sedimentation speed for clouds
!     2010-04-30, Y. Bouteloup : Freezing of rain + some cleaning and simplifications
!     2010-12-03, F. Bouyssel : Removal of ZQFRZ=0=ZQFRZX
!     2011-06-08, O. Riviere: Introduction of LSMOOTHMELT to smooth melting
!     around 0°C
!      R. El Khatib 22-Jul-2014 Vectorizations
! ========================================================

! ---------------
! INPUT VARIABLES
! ---------------

! KIDIA, : DEBUT/FIN DES BOUCLES HORIZONTALES (IST,IEND DANS CPG).
! KFDIA  : START/END OF HORIZONTAL LOOP       (IST,IEND IN   CPG).
! KLON   : DIMENSION HORIZONTALE              (NPROMA   DANS CPG).
!        : HORIZONTAL DIMENSION               (NPROMA   IN   CPG).
! KTDIA  : INDICE DE DEPART DES BOUCLES VERTICALES.
!        : START OF THE VERTICAL LOOP IN THE PHYSICS.
! KLEV   : FIN BOUCLE VERTICALES, DIMENSION VERTICALE (NFLEVG DANS CPG).
!        : END OF VERTICAL LOOP, VERTICAL DIMENSION   (NFLEVG IN   CPG).

! PT     : TEMPERATURE.
!        : TEMPERATURE.
! PQ     : HUMIDITE SPECIFIQUE DE LA VAPEUR D'EAU.
!        : SPECIFIC HUMIDITY OF WATER VAPOUR.
! PQL    : QUANTITE SPECIFIQUE D'EAU CONDENSEE LIQUIDE
!        : LIQUID CONDENSED WATER SPECIFIC HUMIDITY
! PQI    : QUANTITE SPECIFIQUE D'EAU CONDENSEE SOLIDE
!        : SOLID CONDENSED WATER SPECIFIC HUMIDITY
! PAUTOL : GENERATION DE PRECIPITATIONS A PARTIR DE L'EAU NUAGEUSE LIQ.
!        : GENERATION OF PRECIPITATION FROM LIQUID CLOUD WATER (ACMICRO). 
! PAUTOI : GENERATION DE PRECIPITATIONS A PARTIR DE L'EAU NUAGEUSE SOLIDE.
!        : GENERATION OF PRECIPITATION FROM SOLID CLOUD WATER (ACMICRO). 
! PQR    : QUANTITE SPECIFIQUE D'EAU PRECIPITANTE LIQUIDE.
!        : LIQUID PRECIPITATING WATER SPECIFIC HUMIDITY.
! PQS    : QUANTITE SPECIFIQUE D'EAU PRECIPITANTE SOLIDE.
!        : SOLID PRECIPITATING WATER SPECIFIC HUMIDITY.
! PNEB   : NEBULOSITE TOTALE
!        : TOTAL CLOUDINESS  
! PCP    : CHALEUR MASSIQUE A PRESSION CONSTANTE DE L'AIR.
!        : SPECIFIC HEAT AT CONSTANT PRESSURE FOR AIR.
! PR     : CONSTANTE DES GAZ POUR L'AIR.
!        : GAS CONSTANT FOR AIR.
! PAPHI  : GEOPOTENTIEL SUR DEMI-NIVEAUX.
!        : GEOPOTENTIAL ON HALF-LEVELS.
! PAPRSF : PRESSION SUR LES NIVEAUX PLEINS.
!        : PRESSURE ON FULL LEVELS.
! PDELP  : EPAISSEUR EN PRESSION DE LA COUCHE.
!        : LAYER THICKNESS IN PRESSURE UNITS.

! ---------------
! OUTPUT VARIABLES
! ---------------

! PFPLSL  : FLUX DE PRECIPITATION LIQUIDE (PLUIE).
!         : RAIN FLUX.
! PFPLSN  : FLUX DE PRECIPITATION SOLIDE  (NEIGE).
!         : ICE PRECIPITATION FLUX.
! PFPEVPL : FLUX ASSOCIE A L'EVAPORATION DES PRECIP.
!         : FLUX ASSOCIATED TO EVAPORATION OF PRECIPITATIONS.
! PFPEVPN : FLUX ASSOCIE A LA SUBLIMATION DES PRECIP.
!         : FLUX ASSOCIATED TO SUBLIMATION OF PRECIPITATIONS.
! PFPFPL  : FLUX DE GENERATION DE PRECIPITATIONS LIQUIDES.
!         : FLUX OF LIQUID PRECIPITATION GENERATION.
! PFPFPN  : FLUX DE GENERATION DE PRECIPITATIONS SOLIDES.
!         : FLUX OF SOLID PRECIPITATION GENERATION.
! PSEDIQL : FLUX SEDIMENTATION D'EAU LIQUIDE NUAGEUSE.
!         : FLUX SEDIMENTATION OF CLOUD LIQUID WATER.
! PSEDIQN : FLUX SEDIMENTATION D'EAU SOLIDE NUAGEUSE.
!         : FLUX SEDIMENTATION OF CLOUD SOLID WATER.

! ========================================================

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMPHY    , ONLY : YRPHY
USE YOMPHY0   , ONLY : YRPHY0
USE YOMPHY2   , ONLY : YRPHY2
USE YOMCST    , ONLY : RG   , RV   , RTT  , RPI  ,&
 & RCS  , RCW  , RCPV , RLVTT, RLSTT, RETV , RALPW, RALPS,&
 & RALPD, RBETW, RBETS, RBETD, RGAMW, RGAMS, RGAMD


IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT     (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQ     (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQL    (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQI    (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAUTOL (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAUTOI (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQR    (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQS    (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNEB   (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCP    (KLON,KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PR     (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPHI  (KLON,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRSF (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDELP  (KLON,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPLSL (KLON,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPLSN (KLON,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPEVPL(KLON,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPEVPN(KLON,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPFPL (KLON,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPFPN (KLON,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSEDIQL(KLON,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSEDIQN(KLON,0:KFLEV)
REAL(KIND=JPRB),   INTENT(OUT)   :: PSTACK (KLON, KPSTSZ)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSTACK (KLON, KKSTSZ)
INTEGER(KIND=JPIM),INTENT(IN)    :: KPSTSZ, KKSTSZ, KPSTPT, KKSTPT


REAL(KIND=JPRB) :: ZEPS,ZFVELR,ZFVELS,ZTMELT,ZRHOW,ZNRHOW      &
 & , ZDVISC,ZSQTVIS,ZCDARV,ZRHOREF,ZEXP1,ZEXP4,ZEXP6           &
 & , ZPREF,ZCLEAR,ZKDIFF,ZFACT3,ZFACT4                    &
 & , ZSSATW,ZCONDT,ZDIFFV,ZCEV,ZCSU                   &
 & , ZSSATI,ZQR,ZQS                                &
 & , ZACCR,ZAGGR,ZRIMI                             &
 & , ZCOEFF1,ZCOEFF2,ZCOEFF2B,ZCOEFF3,ZCOEFF4,ZCOEFF5,ZCOEFF6  &
 & , ZNU1,ZNU2,ZTAU1,ZTAU2,ZSIGMA1,ZSIGMA2                     &
 & , ZFVENTR1,ZFVENTR2,ZFVENTS1,ZFVENTS2                       &
 & , ZLHFUS,ZSUBSA,ZEVAPPL,ZEVAPPN,ZINT1,ZQMLTX,ZQFRZX,ZQFRZ   &
 & , ZTQEVAPPL,ZTQEVAPPN,ZTCOLLL,ZTCOLLN,ZQFPFPL,ZQFPFPN,ZQMLT &
 & , ZQPRTOT1,ZQPSTOT1,ZQPSTOT2,ZQPRTOT2       &
 & , ZALPHA,ZDZS, ZP1, ZP2, ZP3, ZDZL, ZDZI, ZP1L, ZP2L, ZP1I, ZP2I


REAL(KIND=JPRB), EXTERNAL :: FCGENERALIZED_GAMMA


 

LOGICAL :: LLMELTS,LLFREEZ
LOGICAL :: LLEVAPX
INTEGER(KIND=JPIM) :: JLEV, JLON
INTEGER(KIND=JPIM) :: IPSTPT_ZAUTOI

INTEGER(KIND=JPIM) :: IPSTPT_ZAUTOL

INTEGER(KIND=JPIM) :: IPSTPT_ZQSATI

INTEGER(KIND=JPIM) :: IPSTPT_ZQSATW

INTEGER(KIND=JPIM) :: IPSTPT_ZQPS

INTEGER(KIND=JPIM) :: IPSTPT_ZQPR

INTEGER(KIND=JPIM) :: IPSTPT_ZQI

INTEGER(KIND=JPIM) :: IPSTPT_ZQL

INTEGER(KIND=JPIM) :: IPSTPT_ZFVEL

INTEGER(KIND=JPIM) :: IPSTPT_ZCRIM

INTEGER(KIND=JPIM) :: IPSTPT_ZCACC

INTEGER(KIND=JPIM) :: IPSTPT_ZCAGG

INTEGER(KIND=JPIM) :: IPSTPT_ZCSU2

INTEGER(KIND=JPIM) :: IPSTPT_ZCSU1

INTEGER(KIND=JPIM) :: IPSTPT_ZCEV2

INTEGER(KIND=JPIM) :: IPSTPT_ZCEV1

INTEGER(KIND=JPIM) :: IPSTPT_ZNS

INTEGER(KIND=JPIM) :: IPSTPT_ZEFFA

INTEGER(KIND=JPIM) :: IPSTPT_ZDELT

INTEGER(KIND=JPIM) :: IPSTPT_ZDPSGDT

INTEGER(KIND=JPIM) :: IPSTPT_ZDPSG

INTEGER(KIND=JPIM) :: IPSTPT_ZALTIH

INTEGER(KIND=JPIM) :: IPSTPT_ZRHO

INTEGER(KIND=JPIM) :: IPSTPT_ZDZ

INTEGER(KIND=JPIM) :: IPSTPT_ZQPSTOT

INTEGER(KIND=JPIM) :: IPSTPT_ZPOW2

INTEGER(KIND=JPIM) :: IPSTPT_ZPOW1

INTEGER(KIND=JPIM) :: IPSTPT_ZWORK3

INTEGER(KIND=JPIM) :: IPSTPT_ZWORK2

INTEGER(KIND=JPIM) :: IPSTPT_ZWORK1

INTEGER(KIND=JPIM) :: IPSTPT, IKSTPT


#include "fcttrm.func.h"

! --------------------------------------------------------

!     CHECK RELIABILITY OF INPUT ARGUMENTS.




IPSTPT = KPSTPT

IKSTPT = KKSTPT

IPSTPT_ZWORK1 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZWORK2 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZWORK3 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZPOW1 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZPOW2 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQPSTOT = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDZ = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRHO = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZALTIH = IPSTPT

IPSTPT = IPSTPT + KFLEV-0+1

IPSTPT_ZDPSG = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZDPSGDT = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZDELT = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZEFFA = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZNS = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZCEV1 = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZCEV2 = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZCSU1 = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZCSU2 = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZCAGG = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZCACC = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZCRIM = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZFVEL = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZQL = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZQI = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZQPR = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZQPS = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZQSATW = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZQSATI = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZAUTOL = IPSTPT

IPSTPT = IPSTPT + KFLEV

IPSTPT_ZAUTOI = IPSTPT

IPSTPT = IPSTPT + KFLEV

IF (IPSTPT > KPSTSZ) CALL ABOR1 ('IPSTPT > KPSTSZ')

IF (IKSTPT > KKSTSZ) CALL ABOR1 ('IKSTPT > KKSTSZ')
ZDZL   = YRPHY0%TFVL*YRPHY2%TSPHY
ZDZI   = YRPHY0%TFVI*YRPHY2%TSPHY

!- - - - - - - - - - - - - - -
IF (YRPHY2%TSPHY > 0.0_JPRB) THEN
!- - - - - - - - - - - - - - -

  LLMELTS = .TRUE.
  LLFREEZ = .TRUE.
  LLEVAPX = ( YRPHY0%REVASX /= 0.0_JPRB )

      ! ----------
      ! Constants      
      ! ----------

  ZEPS = 1.E-20_JPRB

      ! ----------------------------------------------------------
      ! COEFFICIENTS IN DISTRIBUTIONS OF PARTICLE SPEED AND MASS  
      ! ----------------------------------------------------------

  ZNU1 = 377.8_JPRB
  ZNU2 = 2.0_JPRB/3._JPRB
  ZTAU1 = 21._JPRB
  ZTAU2 = 0.5_JPRB
  ZSIGMA1 = 0.069_JPRB
  ZSIGMA2 = 2.0_JPRB

      ! ------------------------------------------------------
      ! COEFFICIENTS IN VENTILATION FACTOR FOR RAIN AND SNOW
      ! ------------------------------------------------------

  ZFVENTR1 = 0.78_JPRB
  ZFVENTR2 = 0.31_JPRB
  ZFVENTS1 = 0.65_JPRB
  ZFVENTS2 = 0.44_JPRB

      ! ------------
      ! FALL SPEEDS
      ! ------------

      
  ZFVELR = YRPHY0%TFVR
  ZFVELS = YRPHY0%TFVS
  
  ZTMELT = RTT 
  ZRHOW = 1000._JPRB
  ZNRHOW = YRPHY0%RNINTR * ZRHOW
  ZDVISC = 1.669E-05_JPRB
  ZSQTVIS = SQRT(ZDVISC)
  ZCDARV = 2.31E-02_JPRB * RV
  ZRHOREF = 1.2_JPRB
  ZEXP1 = 1.0_JPRB/3._JPRB
  ZEXP4 = 2.0_JPRB*ZEXP1
  ZEXP6 = 17._JPRB/24._JPRB
  ZPREF = 1.E+05_JPRB
  ZCOEFF1 = 12.695_JPRB * ZNU1 * FCGENERALIZED_GAMMA(3._JPRB+ZNU2) * YRPHY0%RACCEF &
   & / (4._JPRB * ZRHOW)  
!LOP  ZCOEFF2 = 0.0485_JPRB * ZTAU1 * FCGENERALIZED_GAMMA(3._JPRB+ZTAU2) * RRIMEF &
!LOP   & * RPI / (4._JPRB * (2.0_JPRB**(1.0_JPRB+ZTAU2/3._JPRB)) * ZSIGMA1) 
  ZCOEFF2 = 0.0485_JPRB * ZTAU1 * FCGENERALIZED_GAMMA(3._JPRB+ZTAU2) * YRPHY0%RRIMEF &
   & * RPI /  4._JPRB &
   & / (FCGENERALIZED_GAMMA(ZSIGMA2+1.0_JPRB)**((3._JPRB+ZTAU2)/(1.0_JPRB+ZSIGMA2))) &
   & / ZSIGMA1   
  ZCOEFF2B = ZCOEFF2 * YRPHY0%RAGGEF / YRPHY0%RRIMEF
  ZCOEFF3 = 2.0_JPRB * ZFVENTR1 * SQRT(RPI)
  ZCOEFF4 = 2.0_JPRB * RPI**((3._JPRB-ZNU2)/8._JPRB) * ZFVENTR2 * SQRT(ZNU1) &
   & * (ZRHOREF**0.2_JPRB) * FCGENERALIZED_GAMMA((ZNU2+5._JPRB)/2.0_JPRB)   
  ZCOEFF5 = 4._JPRB * ZFVENTS1 / (2.0_JPRB * ZSIGMA1)**ZEXP4 
  ZCOEFF6 = 5.784_JPRB * 4._JPRB * ZFVENTS2 * SQRT(ZTAU1) &
   & * (ZRHOREF**0.2_JPRB) * FCGENERALIZED_GAMMA((ZTAU2+5._JPRB)/2.0_JPRB) &
   & / (2.0_JPRB * ZSIGMA1)**((ZTAU2+5._JPRB)/6._JPRB)   

      ! ---------------
      ! Initializations
      ! ---------------

  DO JLEV = 0, KFLEV
    DO JLON = KIDIA, KFDIA
      PSTACK (JLON, IPSTPT_ZALTIH+JLEV-(0)) = PAPHI(JLON,JLEV) / RG 
    ENDDO
  ENDDO

    ! ==========================
    ! COMPUTE DENSITY, THICKNESS
    ! ==========================

  DO JLEV = KTDIA, KFLEV
    DO JLON = KIDIA, KFDIA
      PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1)) = PDELP(JLON,JLEV) / RG
      PSTACK (JLON, IPSTPT_ZDPSGDT+JLEV-(1)) = &
      &  PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1)) * YRPHY2%TSPHY
      PSTACK (JLON, IPSTPT_ZDELT+JLEV-(1)) = PT(JLON,JLEV) - RTT
      PSTACK (JLON, IPSTPT_ZRHO+JLEV-(1)) = PAPRSF(JLON,JLEV) / PR(JLON,JLEV) / &
      & PT(JLON,JLEV)  
      PSTACK (JLON, IPSTPT_ZQPR+JLEV-(1)) = PQR(JLON,JLEV)
      PSTACK (JLON, IPSTPT_ZQPS+JLEV-(1)) = PQS(JLON,JLEV)
      PSTACK (JLON, IPSTPT_ZAUTOL+JLEV-(1)) = PAUTOL(JLON,JLEV) *&
      &  PSTACK (JLON, IPSTPT_ZDPSGDT+JLEV-(1))
      PSTACK (JLON, IPSTPT_ZAUTOI+JLEV-(1)) = PAUTOI(JLON,JLEV) *&
      &  PSTACK (JLON, IPSTPT_ZDPSGDT+JLEV-(1))
    ENDDO        
  ENDDO  

     ! ======================================
     ! OTHER INITIALIZATIONS FOR MICROPHYSICS
     ! ======================================

  DO JLEV=KTDIA,KFLEV
!   Isolate in a loop what may not vectorize:
    DO JLON=KIDIA,KFDIA
      PSTACK (JLON, IPSTPT_ZWORK1)=FOEW(PT(JLON,JLEV),0.0_JPRB)
      PSTACK (JLON, IPSTPT_ZWORK2)=FOEW(PT(JLON,JLEV),1.0_JPRB)
      PSTACK (JLON, IPSTPT_ZWORK3)= ( ZRHOREF /&
      &  PSTACK (JLON, IPSTPT_ZRHO+JLEV-(1)) )**0.4_JPRB
    ENDDO
!   This loop should vectorize:
    DO JLON=KIDIA,KFDIA

      ZALPHA=MAX(ZEPS,PQS(JLON,JLEV))/MAX(ZEPS,PQR(JLON,JLEV)+PQS(JLON,JLEV))
      PSTACK (JLON, IPSTPT_ZFVEL+JLEV-(1)) = ZALPHA*ZFVELS + (1.0_JPRB - ZALPHA)&
      & *ZFVELR 
       ! -----------------------------------------------------------
       ! Efficiency for ice aggregation as a function of temperature.
       ! -----------------------------------------------------------
      PSTACK (JLON, IPSTPT_ZEFFA+JLEV-(1)) = EXP(0.025_JPRB *&
      &  PSTACK (JLON, IPSTPT_ZDELT+JLEV-(1)))

       ! ---------------------------------------------------------
       ! Intercept parameter for ice as a function of temperature.
       ! ---------------------------------------------------------
      PSTACK (JLON, IPSTPT_ZNS+JLEV-(1)) = YRPHY0%RNINTS * EXP(-0.1222_JPRB *&
      &  PSTACK (JLON, IPSTPT_ZDELT+JLEV-(1)))

      PSTACK (JLON, IPSTPT_ZQL+JLEV-(1)) = MAX(0.0_JPRB,PQL(JLON,JLEV) -PAUTOL(&
      & JLON,JLEV)*YRPHY2%TSPHY)
      PSTACK (JLON, IPSTPT_ZQI+JLEV-(1)) = MAX(0.0_JPRB,PQI(JLON,JLEV) -PAUTOI(&
      & JLON,JLEV)*YRPHY2%TSPHY)

      ZCLEAR = 1.0_JPRB - PNEB(JLON,JLEV)
      ZKDIFF = 2.E-5_JPRB * ZPREF / PAPRSF(JLON,JLEV)
      ZFACT3 = (ZSQTVIS * ZKDIFF)**ZEXP1
      ZFACT4 = RV * PT(JLON,JLEV) / ZKDIFF

       ! -----------------------
       ! For evaporation of rain
       ! -----------------------
      PSTACK (JLON, IPSTPT_ZQSATW+JLEV-(1)) = FOQS(PSTACK (JLON, IPSTPT_ZWORK1)/&
      &  PAPRSF(JLON,JLEV))
      ZSSATW = 1.0_JPRB - PQ(JLON,JLEV)/PSTACK (JLON, IPSTPT_ZQSATW+JLEV-(1))

      ZCONDT = ( FOLH(PT(JLON,JLEV),0.0_JPRB)/PT(JLON,JLEV) )**2 /ZCDARV
      ZDIFFV = ZFACT4 / PSTACK (JLON, IPSTPT_ZWORK1)

      ZCEV = ZSSATW * ZCLEAR * YRPHY0%RNINTR / &
      & PSTACK (JLON, IPSTPT_ZRHO+JLEV-(1)) / (ZCONDT + ZDIFFV)  
      ZCEV = MAX(0.0_JPRB,ZCEV)
      PSTACK (JLON, IPSTPT_ZCEV1+JLEV-(1)) = ZCEV * ZCOEFF3 
      PSTACK (JLON, IPSTPT_ZCEV2+JLEV-(1)) = ZCEV * ZCOEFF4 / ZFACT3

       ! -----------------------
       ! For sublimation of snow
       ! -----------------------
      PSTACK (JLON, IPSTPT_ZQSATI+JLEV-(1)) = FOQS(PSTACK (JLON, IPSTPT_ZWORK2)/&
      &  PAPRSF(JLON,JLEV))
      ZSSATI = 1.0_JPRB - PQ(JLON,JLEV)/PSTACK (JLON, IPSTPT_ZQSATI+JLEV-(1))

      ZCONDT = ( FOLH(PT(JLON,JLEV),1.0_JPRB)/PT(JLON,JLEV) )**2 /ZCDARV
      ZDIFFV = ZFACT4 / PSTACK (JLON, IPSTPT_ZWORK2)

      ZCSU = ZSSATI * ZCLEAR * PSTACK (JLON, IPSTPT_ZNS+JLEV-(1)) / &
      &  PSTACK (JLON, IPSTPT_ZRHO+JLEV-(1)) / (ZCONDT + ZDIFFV)  
      ZCSU = MAX(0.0_JPRB,ZCSU)
      PSTACK (JLON, IPSTPT_ZCSU1+JLEV-(1)) = ZCSU * ZCOEFF5
      PSTACK (JLON, IPSTPT_ZCSU2+JLEV-(1)) = ZCSU * ZCOEFF6 / ZFACT3

       ! ------------------------
       ! For collection processes
       ! ------------------------
      PSTACK (JLON, IPSTPT_ZCACC+JLEV-(1)) = ZCOEFF1 *&
      &  PSTACK (JLON, IPSTPT_ZWORK3)
      PSTACK (JLON, IPSTPT_ZCRIM+JLEV-(1)) = ZCOEFF2 *&
      &  PSTACK (JLON, IPSTPT_ZWORK3)
      PSTACK (JLON, IPSTPT_ZCAGG+JLEV-(1)) = ZCOEFF2B * &
      &  PSTACK (JLON, IPSTPT_ZWORK3) * PSTACK (JLON, IPSTPT_ZEFFA+JLEV-(1))

    ENDDO
  ENDDO

    ! =============================================
    ! PERFORM STATISTICAL ADVECTION OF PRECIPITATION
    ! =============================================

    !-- -- -- -- -- --
  DO JLEV=KTDIA,KFLEV  
    !-- -- -- -- -- --


      ! =================================================
      ! First computation of total rain and snow which fall  
      ! through the curent level. Only 3 terms at this stage :
      ! 1 ==> Initial contents
      ! 2 ==> Flux from the upper level
      ! 3 ==> Autoconversion flux 
      
      ! In this version there is only one falling speed, depending of 
      ! the nature of the precipitation (like ADVPRC)
      ! =================================================

    DO JLON = KIDIA, KFDIA
    
      PSTACK (JLON, IPSTPT_ZDZ)   = PSTACK (JLON, IPSTPT_ZFVEL+JLEV-(1))*YRPHY2&
      & % TSPHY
    
      PSTACK (JLON, IPSTPT_ZWORK3) = MAX(0.0_JPRB,                              &
      &  PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))*                                  &
      &  PSTACK (JLON, IPSTPT_ZQPR+JLEV-(1)) + YRPHY2%TSPHY*(PFPLSL(JLON,JLEV-1)&
      &  ) + PSTACK (JLON, IPSTPT_ZAUTOL+JLEV-(1)))
      PSTACK (JLON, IPSTPT_ZQPSTOT) = MAX(0.0_JPRB,                             &
      &  PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))*                                  &
      &  PSTACK (JLON, IPSTPT_ZQPS+JLEV-(1)) + YRPHY2%TSPHY*(PFPLSN(JLON,JLEV-1)&
      &  ) + PSTACK (JLON, IPSTPT_ZAUTOI+JLEV-(1)))

!  New formulation which does not take into account initial contents
! This implies a total independence to CFL criteria therefore to the layers thickness

!      ZWORK3(JLON) = MAX(0.0_JPRB,TSPHY*(PFPLSL(JLON,JLEV-1))+ZAUTOL(JLON,JLEV))
!      ZQPSTOT(JLON) = MAX(0.0_JPRB,TSPHY*(PFPLSN(JLON,JLEV-1))+ZAUTOI(JLON,JLEV))

    ENDDO

    DO JLON = KIDIA, KFDIA

      ZQR = PSTACK (JLON, IPSTPT_ZWORK3) / PSTACK (JLON, IPSTPT_ZDZ)
      ZQS = PSTACK (JLON, IPSTPT_ZQPSTOT) / PSTACK (JLON, IPSTPT_ZDZ)
      
      IF (YRPHY%LEVAPP) THEN

        PSTACK (JLON, IPSTPT_ZWORK1) =  ZQR / ZNRHOW
        PSTACK (JLON, IPSTPT_ZWORK2) =  ZQS / PSTACK (JLON, IPSTPT_ZNS+JLEV-(1))

      ENDIF

    ENDDO

    IF (YRPHY%LEVAPP) THEN
      DO JLON = KIDIA, KFDIA
        PSTACK (JLON, IPSTPT_ZPOW1)=PSTACK (JLON, IPSTPT_ZCEV2+JLEV-(1))*&
        &  PSTACK (JLON, IPSTPT_ZWORK1)**ZEXP6
        PSTACK (JLON, IPSTPT_ZPOW2)=PSTACK (JLON, IPSTPT_ZCSU1+JLEV-(1))*&
        &  PSTACK (JLON, IPSTPT_ZWORK2)**ZEXP4
      ENDDO
    ENDIF

    DO JLON = KIDIA, KFDIA

      ZTQEVAPPL = 0.0_JPRB
      ZTQEVAPPN = 0.0_JPRB
      ZQFPFPL   = 0.0_JPRB
      ZQFPFPN   = 0.0_JPRB
      ZTCOLLL   = 0.0_JPRB
      ZTCOLLN   = 0.0_JPRB
      ZQMLT     = 0.0_JPRB
      ZQMLTX    = 0.0_JPRB
      ZQFRZ     = 0.0_JPRB
      ZQFRZX    = 0.0_JPRB  
      ZACCR     = 0.0_JPRB

      IF (YRPHY%LEVAPP) THEN

           ! ----------------------------------------
           ! Evaporation/Sublimation of precipitation
           ! ----------------------------------------

        ZEVAPPL = PSTACK (JLON, IPSTPT_ZCEV1+JLEV-(1))*SQRT( &
        & PSTACK (JLON, IPSTPT_ZWORK1)) + PSTACK (JLON, IPSTPT_ZPOW1)
        ZEVAPPN = PSTACK (JLON, IPSTPT_ZPOW2) + &
        &  PSTACK (JLON, IPSTPT_ZCSU2+JLEV-(1))*PSTACK (JLON, IPSTPT_ZWORK2)

        ZINT1 = 1.0_JPRB / MAX(ZEPS,ZEVAPPL+ZEVAPPN)

        IF (LLEVAPX) THEN
          ZSUBSA = YRPHY0%REVASX*ZINT1*(1.0_JPRB-EXP(-1.0_JPRB/(YRPHY0%REVASX*ZINT1)))
          ZEVAPPL = ZSUBSA*ZEVAPPL
          ZEVAPPN = ZSUBSA*ZEVAPPN
        ENDIF

        ZSUBSA = ZINT1 * ZEVAPPL * (PSTACK (JLON, IPSTPT_ZQSATW+JLEV-(1)) - PQ(&
        & JLON,JLEV))
        ZTQEVAPPL = MAX(0.0_JPRB, MIN( PSTACK (JLON, IPSTPT_ZWORK3), ZEVAPPL *&
        &  PSTACK (JLON, IPSTPT_ZDPSGDT+JLEV-(1)), ZSUBSA *                   &
        &  PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1)) ))   

        ZSUBSA = ZINT1 * ZEVAPPN * (PSTACK (JLON, IPSTPT_ZQSATI+JLEV-(1)) - PQ(&
        & JLON,JLEV))
        ZTQEVAPPN = MAX(0.0_JPRB, MIN( PSTACK (JLON, IPSTPT_ZQPSTOT), ZEVAPPN *&
        &  PSTACK (JLON, IPSTPT_ZDPSGDT+JLEV-(1)), ZSUBSA *                    &
        &  PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1)) ))   

      ENDIF

      ZQPRTOT1 = PSTACK (JLON, IPSTPT_ZWORK3) - ZTQEVAPPL
      ZQPSTOT1 = PSTACK (JLON, IPSTPT_ZQPSTOT) - ZTQEVAPPN

      ZQR = ZQPRTOT1 / PSTACK (JLON, IPSTPT_ZDZ)
      ZQS = ZQPSTOT1 / PSTACK (JLON, IPSTPT_ZDZ)

      IF (YRPHY%LCOLLEC) THEN

           ! ----------------------------------------
           ! Collection of cloud liquid water by rain
           ! ----------------------------------------

        ZACCR = PSTACK (JLON, IPSTPT_ZQL+JLEV-(1))*(1.0_JPRB-EXP(-                 &
        &  PSTACK (JLON, IPSTPT_ZCACC+JLEV-(1))*ZQR*YRPHY2%TSPHY)) * MAX(0.0_JPRB, &
        & SIGN(1.0_JPRB,PT(JLON,JLEV)-RTT))
        

           ! -------------------------------
           ! Collection of cloud ice by snow
           ! -------------------------------
        ZAGGR = PSTACK (JLON, IPSTPT_ZQI+JLEV-(1))*(1.0_JPRB-EXP(-&
        &  PSTACK (JLON, IPSTPT_ZCAGG+JLEV-(1))*ZQS*YRPHY2%TSPHY))

           ! ----------------------------------------
           ! Collection of cloud liquid water by snow
           ! ----------------------------------------
        ZRIMI = PSTACK (JLON, IPSTPT_ZQL+JLEV-(1))*(1.0_JPRB-EXP(-&
        &  PSTACK (JLON, IPSTPT_ZCRIM+JLEV-(1))*ZQS*YRPHY2%TSPHY))

           ! ----------------------------
           ! Sum up collection processes
           ! ----------------------------
        ZTCOLLL = MAX(0.0_JPRB, MIN(ZACCR+ZRIMI, &
        & PSTACK (JLON, IPSTPT_ZQL+JLEV-(1))) ) *&
        &  PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))
        ZTCOLLN = MAX(0.0_JPRB, MIN(ZAGGR , PSTACK (JLON, IPSTPT_ZQI+JLEV-(1)))&
        &  ) * PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))

      ENDIF

      ZQPRTOT2  = PSTACK (JLON, IPSTPT_ZWORK3) + ZTCOLLL
      ZQPSTOT2  = PSTACK (JLON, IPSTPT_ZQPSTOT) + ZTCOLLN

      IF (LLMELTS) THEN

           ! ----------------------------
           ! Snow melting
           ! ----------------------------
        ZLHFUS = FOLH(PT(JLON,JLEV),1.0_JPRB) - FOLH(PT(JLON,JLEV),0.0_JPRB)
        ZQMLTX = PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1)) * PCP(JLON,JLEV) * MAX(0.0_JPRB, &
        & PSTACK (JLON, IPSTPT_ZDELT+JLEV-(1))) / ZLHFUS

         IF (.NOT. YRPHY%LSMOOTHMELT) THEN 
          ZQMLT = MIN ( ZQMLTX , ZQPSTOT2 - ZTQEVAPPN )
         ELSE
          ZQMLT=(ZQPSTOT2-ZTQEVAPPN)*(1+TANH(&
          & PSTACK (JLON, IPSTPT_ZDELT+JLEV-(1))/YRPHY0%RSMOOTHMELT))/2.0_JPRB
         ENDIF
       ENDIF 
       IF (LLFREEZ) THEN  

           ! ----------------------------
           ! Rain freezing
           ! ----------------------------
        
        ZQFRZX = PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1)) * PCP(JLON,JLEV) * MAX(0.0_JPRB, &
        & -PSTACK (JLON, IPSTPT_ZDELT+JLEV-(1))) / ZLHFUS
        
        ZQFRZ = MIN ( ZQFRZX , ZQPRTOT2 - ZTQEVAPPL ) 
        
      ENDIF

      
      PFPEVPL(JLON,JLEV) = PFPEVPL(JLON,JLEV-1) &
       & + ( ZTQEVAPPL - ZQMLT + ZQFRZ) / YRPHY2%TSPHY
      PFPEVPN(JLON,JLEV) = PFPEVPN(JLON,JLEV-1) &
       & + ( ZTQEVAPPN + ZQMLT - ZQFRZ) / YRPHY2%TSPHY

      PFPFPL (JLON,JLEV) = PFPFPL (JLON,JLEV-1) + ( ZTCOLLL +&
      &  PSTACK (JLON, IPSTPT_ZAUTOL+JLEV-(1)) ) / YRPHY2%TSPHY
      PFPFPN (JLON,JLEV) = PFPFPN (JLON,JLEV-1) + ( ZTCOLLN +&
      &  PSTACK (JLON, IPSTPT_ZAUTOI+JLEV-(1)) ) / YRPHY2%TSPHY


           ! ----------------------------
           ! Computation of fundamental proportions
           ! needed by the statistical algorithm
           ! (only YB formulation !)
           ! ----------------------------

! Rain and snow           
      ZDZS = PSTACK (JLON, IPSTPT_ZALTIH+JLEV-1-(0)) -&
      &  PSTACK (JLON, IPSTPT_ZALTIH+JLEV-(0))
      ZP1  = MIN(1._JPRB , PSTACK (JLON, IPSTPT_ZDZ)/ZDZS)
      ZP2  = MAX(0._JPRB,1._JPRB - ZDZS/PSTACK (JLON, IPSTPT_ZDZ))
      ZP3  = (ZP1 + ZP2)/2.0_JPRB
! Cloud liquid water      
      ZP1L  = MIN(1._JPRB , ZDZL/ZDZS)
      ZP2L  = MAX(0._JPRB,1._JPRB - ZDZS/MAX(ZEPS,ZDZL))
! Cloud ice
      ZP1I  = MIN(1._JPRB , ZDZI/ZDZS)
      ZP2I  = MAX(0._JPRB,1._JPRB - ZDZS/MAX(ZEPS,ZDZI))

      
! WARNING ! : Dans cette version pour coller a ADVPRC il n'y a pas de traitement separe de la neige 
!             et de la pluie. Ceci serait difficile dans ADVPRC mais trivial dans ADVPRCS      
    ! ================================================================
    ! COMPUTE FLUX ASSOCIATED TO FALLING OF PRECIPITATION
    ! ================================================================

      PFPLSL(JLON,JLEV) = (ZP1*PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))*            &
      &  PSTACK (JLON, IPSTPT_ZQPR+JLEV-(1)) + ZP2*YRPHY2%TSPHY*PFPLSL(JLON,JLEV&
      &  - 1) + ZP3*(PSTACK (JLON, IPSTPT_ZAUTOL+JLEV-(1)) + ZTCOLLL + ZQMLT)) *&
      &   MAX(0.0_JPRB, (1._JPRB - (ZTQEVAPPL+ZQFRZ)/MAX(ZEPS,ZQPRTOT2))) /     &
      & YRPHY2 %TSPHY
      

      PFPLSN(JLON,JLEV) = (ZP1*PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))*            &
      &  PSTACK (JLON, IPSTPT_ZQPS+JLEV-(1)) + ZP2*YRPHY2%TSPHY*PFPLSN(JLON,JLEV&
      &  - 1) + ZP3*(PSTACK (JLON, IPSTPT_ZAUTOI+JLEV-(1)) + ZTCOLLN + ZQFRZ)) *&
      &   MAX(0.0_JPRB, (1._JPRB - (ZTQEVAPPN+ZQMLT)/MAX(ZEPS,ZQPSTOT2))) /     &
      & YRPHY2 %TSPHY

      PSEDIQL(JLON,JLEV) = (ZP1L*PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))*       &
      &  PSTACK (JLON, IPSTPT_ZQL+JLEV-(1)) + ZP2L*YRPHY2%TSPHY*PSEDIQL(JLON,&
      & JLEV -1) ) / YRPHY2%TSPHY
       
      PSEDIQN(JLON,JLEV) = (ZP1I*PSTACK (JLON, IPSTPT_ZDPSG+JLEV-(1))*       &
      &  PSTACK (JLON, IPSTPT_ZQI+JLEV-(1)) + ZP2I*YRPHY2%TSPHY*PSEDIQN(JLON,&
      & JLEV -1) ) / YRPHY2%TSPHY
       
    ENDDO ! JLON = KIDIA, KFDIA

    !-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  ENDDO ! LEV=1,KFLEV : end of statistical advection 
    !-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

!- - - - - - - - - - - - - - - - - - - - - - -
ENDIF  ! End of test on TSPHY > 0.0_JPRB
!- - - - - - - - - - - - - - - - - - - - - - -


END SUBROUTINE ADVPRCS
