INTERFACE
#include "attr.h"
FUNCTION FCGENERALIZED_GAMMA(PX)  

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

REAL(KIND=JPRB), INTENT(IN)                     :: PX

REAL(KIND=JPRB) :: FCGENERALIZED_GAMMA

END FUNCTION FCGENERALIZED_GAMMA
END INTERFACE
