#include "attr.h"
SUBROUTINE FPCINCAPE(KIDIA,KFDIA,KLON,KLEV,KLEVST,PT,PRP,PQV,PCAPE,PCIN,KLCL,KFCL,KLNB, &
                   & KSTACK, PSTACK, KPSTSZ, KKSTSZ, KPSTPT, KKSTPT)

! --------------------------------------------------------------
! **** *FPCINCAPE* COMPUTE CAPE AND CIN.
! --------------------------------------------------------------
! SUBJECT:
!    ROUTINE COMPUTING CAPE AND CIN  

! INTERFACE:
!    *CALL* *FPCINCAPE*

! --------------------------------------------------------------
! -   INPUT ARGUMENTS
!     ---------------

! - DIMENSIONING

! KIDIA      : FIRST INDEX OF LOOPS
! KFDIA     : LAST INDEX OF LOOPS
! KLON   : DEPTH OF THE VECTORIZATION ARRAYS
! KLEV     : END OF VERTICAL LOOP AND VERTICAL DIMENSION

! - VARIABLES
! KLEVST   : LEVEL FROM WHICH PARCEL IS RAISED
! PT       : TEMPERATURE (K)
! PRP      : PRESSURE (PA)
! PQV      : WATER VAPOUR SPECIFIC HUMIDITY (NO DIM)

! --------------------------------------------------------------
! -   OUTPUT ARGUMENTS
!     ---------------
! - VARIABLES
! PCAPE    : CAPE - CONVECTIVE AVAILABLE POTENTIAL ENERGY (J/KG)
!                   (POTENTIALLY AVAILABLE CONVECTIVE KINETIC ENERGY)
! PCIN     : CIN - CONVECTIVE INHIBITION (J/KG)
! KLCL     : CONDENSATION LEVEL
! KFCL     : FREE CONVECTION LEVEL
! KLNB     : LEVEL OF NEUTRAL BUOYANCY

! --------------------------------------------------------------
! -   IMPLICITE ARGUMENTS
!     -------------------
! YOMCAPE 
! YOMCST
! FCTTRM
! FCTAST
! FCTTIM

! --------------------------------------------------------------
! EXTERNALS:

! METHOD:

!      THE PARCEL IS RAISED FROM LEVEL (LO which is equal KLEVST) 
!      TO THE LEVEL OF CONDENSATION (LC),
!      FURTHER TO ITS LEVEL OF FREE CONVECTION (LFC), WHERE THE 
!      PARCEL BECOMES BUOYANT,
!      THEN FURTHER TO THE LEVEL OF NEUTRAL BUOYANCY (LNB), WHERE THE
!      PARCEL BECOMES UNBUOYANT.

!      ALL COMPUTATIONS ARE DONE WITHOUT ENTRAINMENT OF ENVIRONMENTAL AIR.

!      CIN IS MASS SPECIFIC ENERGY TO RAISE THE PARCEL FROM 
!          from LO to LC further to LFC.
!          ONLY THE SUM OF NEGATIVE TERMS.
!      CAPE IS MASS SPECIFIC ENERGY  PROVIDED BY THE RAISE OF THE PARCEL
!          from LFC to LNB.
!          ONLY THE SUM OF POSITIVE TERMS.

! AUTEUR/AUTHOR:   2001-03, J.M. PIRIOU, N. PRISTOV.

! MODIFICATIONS:
!        M.Hamrud      01-Oct-2003 CY28 Cleaning
!    2010-02-04  J.M. Piriou. Bug correction: derivative of qs(T,p) from the Newton loops.
!    2010-02-11  J.M. Piriou. Bug correction: JLON dimension of ZFDERQS0 array.
!    2010-02-17  J.M. Piriou. Protections in case of cold temperature, low pressure, etc.
!    2010-02-17  J.M. Piriou. First Newton loop in a single DO loop.
!    2010-02-17  J.M. Piriou. Compute CAPE only below the convective reference level (NTCVIM).
! --------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMCAPE  , ONLY :  NCAPEITER,NETAPES  ,GCAPERET
USE YOMCST   , ONLY :  RTT      ,RDAY     ,REPSM    ,RETV     ,&
 & RCW      ,REA      ,RD       ,RV       ,RCPD     ,RCPV     ,&
 & RCS      ,RLVTT    ,RLSTT    ,RBETS    ,RALPW    ,RBETW    ,&
 & RGAMW    ,RALPS    ,RGAMS    ,RALPD    ,RBETD    ,RGAMD    ,&
 & RG
USE YOMFPC , ONLY : RENTRA
USE YOMTOPH, ONLY : YRTOPH

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVST 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRP(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQV(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCAPE(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCIN(KLON) 
INTEGER(KIND=JPIM)   ,INTENT(OUT)   :: KLCL(KLON)
INTEGER(KIND=JPIM)   ,INTENT(OUT)   :: KFCL(KLON)
INTEGER(KIND=JPIM)   ,INTENT(OUT)   :: KLNB(KLON)
REAL(KIND=JPRB),   INTENT(OUT)   :: PSTACK (KLON, KPSTSZ)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSTACK (KLON, KKSTSZ)
INTEGER(KIND=JPIM),INTENT(IN)    :: KPSTSZ, KKSTSZ, KPSTPT, KKSTPT


INTEGER(KIND=JPIM) :: JLEV,JLON,JIT,JETAPES
REAL(KIND=JPRB) :: ZBUOY,ZTV1,ZTV2,ZQV2,ZT2,ZST,ZDELARG,ZL,ZCP, &
 & ZFDERQS,ZADD,ZDERL,ZRDLOG,ZZQV
  
#include "abor1.intfb.h"

REAL(KIND=JPRB) :: ZFDERQS0, ZDZ
REAL(KIND=JPRB) :: ZMAXT,ZMINT,ZMINDERI,ZMINQ,ZMAXQ
 

INTEGER(KIND=JPIM) :: IPSTPT_ZQVIN

INTEGER(KIND=JPIM) :: IPSTPT_ZTIN

INTEGER(KIND=JPIM) :: IPSTPT_ZZFOEW

INTEGER(KIND=JPIM) :: IPSTPT_ZCP0

INTEGER(KIND=JPIM) :: IPSTPT_ZL0

INTEGER(KIND=JPIM) :: IPSTPT_ZDELARG0

INTEGER(KIND=JPIM) :: IPSTPT_ZFDERFOLH0

INTEGER(KIND=JPIM) :: IPSTPT_ZZT

INTEGER(KIND=JPIM) :: IPSTPT_ZQVDEPART

INTEGER(KIND=JPIM) :: IPSTPT_ZPDEPART

INTEGER(KIND=JPIM) :: IPSTPT_ZPARRIVEE

INTEGER(KIND=JPIM) :: IPSTPT_ZLOG

INTEGER(KIND=JPIM) :: IPSTPT_ZTDEPART

INTEGER(KIND=JPIM) :: IPSTPT_ZSQI

INTEGER(KIND=JPIM) :: IPSTPT_ZSQL

INTEGER(KIND=JPIM) :: IPSTPT_ZSQV

INTEGER(KIND=JPIM) :: IPSTPT_ZQI

INTEGER(KIND=JPIM) :: IPSTPT_ZQL

INTEGER(KIND=JPIM) :: IPSTPT_ZT1

INTEGER(KIND=JPIM) :: IPSTPT_ZT

INTEGER(KIND=JPIM) :: IPSTPT_ZQV1

INTEGER(KIND=JPIM) :: IPSTPT_ZQV

INTEGER(KIND=JPIM) :: IPSTPT_ZQS

INTEGER(KIND=JPIM) :: IPSTPT_ZBUOYPREC

INTEGER(KIND=JPIM) :: IPSTPT_ZDT

INTEGER(KIND=JPIM) :: IPSTPT_ZRT

INTEGER(KIND=JPIM) :: IPSTPT_ZDLOG

INTEGER(KIND=JPIM) :: IKSTPT_IPREVIOUS_NULL_ZRT

INTEGER(KIND=JPIM) :: IPSTPT, IKSTPT
 

!---------

!  FUNCTIONS
#include "fctast.func.h"
#include "fcttrm.func.h"
#include "fcttim.func.h"



!-------------------------------------------------
! INITIALIZE DEFAULT VALUES.
!-------------------------------------------------


IPSTPT = KPSTPT

IKSTPT = KKSTPT

IKSTPT_IPREVIOUS_NULL_ZRT = IKSTPT

IKSTPT = IKSTPT + 1

IPSTPT_ZDLOG = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZRT = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDT = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZBUOYPREC = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQS = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQV = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQV1 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZT = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZT1 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQL = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQI = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZSQV = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZSQL = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZSQI = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTDEPART = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZLOG = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZPARRIVEE = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZPDEPART = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZQVDEPART = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZZT = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZFDERFOLH0 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZDELARG0 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZL0 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZCP0 = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZZFOEW = IPSTPT

IPSTPT = IPSTPT + 1

IPSTPT_ZTIN = IPSTPT

IPSTPT = IPSTPT + KLEV

IPSTPT_ZQVIN = IPSTPT

IPSTPT = IPSTPT + KLEV

IF (IPSTPT > KPSTSZ) CALL ABOR1 

IF (IKSTPT > KKSTSZ) CALL ABOR1 
DO JLON = KIDIA, KFDIA
PCIN(JLON)=0.0_JPRB
ENDDO
DO JLON = KIDIA, KFDIA
PCAPE(JLON)=0.0_JPRB
ENDDO
DO JLON = KIDIA, KFDIA
KLCL(JLON)=-1
ENDDO
DO JLON = KIDIA, KFDIA
KFCL(JLON)=-1
ENDDO
DO JLON = KIDIA, KFDIA
KLNB(JLON)=-1
ENDDO

ZMINT=150._JPRB
ZMAXT=400._JPRB
ZMINDERI=1000._JPRB
ZMINQ=1.E-07_JPRB
ZMAXQ=1.0_JPRB-ZMINQ

DO JLEV=1,KLEV
  DO JLON=KIDIA,KFDIA
    PSTACK (JLON, IPSTPT_ZTIN+JLEV-(1))=MAX(ZMINT,MIN(ZMAXT,PT(JLON,JLEV)))
    PSTACK (JLON, IPSTPT_ZQVIN+JLEV-(1))=MAX(ZMINQ,MIN(ZMAXQ,PQV(JLON,JLEV)))
  ENDDO
ENDDO

DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZBUOYPREC)=0.0_JPRB
ENDDO
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZT)=PSTACK (JLON, IPSTPT_ZTIN+KLEVST-(1))
ENDDO
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZQV)=PSTACK (JLON, IPSTPT_ZQVIN+KLEVST-(1))
ENDDO
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZQL)=0.0_JPRB
ENDDO
DO JLON = KIDIA, KFDIA
PSTACK (JLON, IPSTPT_ZQI)=0.0_JPRB
ENDDO

DO JLON = KIDIA, KFDIA
KSTACK (JLON, IKSTPT_IPREVIOUS_NULL_ZRT)=999999
ENDDO

DO JLEV=KLEVST,YRTOPH%NTCVIM+1,-1
  DO JLON=KIDIA,KFDIA
    !
    !-------------------------------------------------
    ! SATURATION SPECIFIC HUMIDITY.
    !-------------------------------------------------
    !
    PSTACK (JLON, IPSTPT_ZT)=MAX(ZMINT,MIN(ZMAXT,PSTACK (JLON, IPSTPT_ZT)))
    PSTACK (JLON, IPSTPT_ZQS)=FOQS(FOEW(PSTACK (JLON, IPSTPT_ZT),MAX(0.0_JPRB, &
    & SIGN(1.0_JPRB,RTT-PSTACK (JLON, IPSTPT_ZT))))/PRP(JLON,JLEV))  
    PSTACK (JLON, IPSTPT_ZDLOG)=LOG(PRP(JLON,MIN(KLEVST,JLEV+1))/PRP(JLON,JLEV))&
    &  * MAX(0,-SIGN(1,JLEV-KLEVST))  
    !
  ENDDO
  DO JLON=KIDIA,KFDIA
    !
    !-------------------------------------------------
    ! PRESSURE AND BUOYANCY.
    !-------------------------------------------------
    !
    PSTACK (JLON, IPSTPT_ZQV)=MAX(ZMINQ,MIN(ZMAXQ,PSTACK (JLON, IPSTPT_ZQV)))
    ZTV1=PSTACK (JLON, IPSTPT_ZT)*(1.0_JPRB+PSTACK (JLON, IPSTPT_ZQV)/(1.0_JPRB-        &
    &  PSTACK (JLON, IPSTPT_ZQV))*RV/RD)/ (1.0_JPRB+PSTACK (JLON, IPSTPT_ZQV)/ (1.0_JPRB&
    &  -PSTACK (JLON, IPSTPT_ZQV))+PSTACK (JLON, IPSTPT_ZQL)/(1.0_JPRB-                 &
    &  PSTACK (JLON, IPSTPT_ZQL))+PSTACK (JLON, IPSTPT_ZQI)/(1.0_JPRB-                  &
    &  PSTACK (JLON, IPSTPT_ZQI)))  
    ZTV2=PSTACK (JLON, IPSTPT_ZTIN+JLEV-(1))*(1.0_JPRB+        &
    &  PSTACK (JLON, IPSTPT_ZQVIN+JLEV-(1))/(1.0_JPRB-         &
    &  PSTACK (JLON, IPSTPT_ZQVIN+JLEV-(1)))*RV/RD)/ (1.0_JPRB+&
    &  PSTACK (JLON, IPSTPT_ZQVIN+JLEV-(1))/(1.0_JPRB-         &
    &  PSTACK (JLON, IPSTPT_ZQVIN+JLEV-(1))) )  
    ZBUOY=(ZTV1/ZTV2-1.0_JPRB)*(RD+(RV-RD)*PSTACK (JLON, IPSTPT_ZQVIN+JLEV-(1)))&
    &  *PSTACK (JLON, IPSTPT_ZTIN+JLEV-(1))
    !
    !-------------------------------------------------
    ! CIN AND CAPE INTEGRALS.
    !-------------------------------------------------
    !
    PSTACK (JLON, IPSTPT_ZRT)=0.5_JPRB*(ZBUOY+PSTACK (JLON, IPSTPT_ZBUOYPREC))*&
    &  PSTACK (JLON, IPSTPT_ZDLOG)
    !------------------------------------------
    ! CUMULATE CAPE IF POSITIVE CONTRIBUTION.
    !------------------------------------------
    PCAPE(JLON)=PCAPE(JLON)+MAX(0.0_JPRB,PSTACK (JLON, IPSTPT_ZRT))
    !------------------------------------------
    ! CUMULATE CIN IF NEGATIVE CONTRIBUTION AND BELOW LFC.
    !------------------------------------------
    IF(PCAPE(JLON) == 0.0_JPRB) PCIN(JLON)=PCIN(JLON)+MIN(0.0_JPRB,&
                                & PSTACK (JLON, IPSTPT_ZRT))
    PSTACK (JLON, IPSTPT_ZBUOYPREC)=ZBUOY
    !
    !-------------------------------------------------
    ! IF THE PARCEL IS SUPERSATURATED, SUPERSATURATION IS REMOVED.
    ! THIS IS DONE THROUGH AN ISOBARIC TRANSFORMATION FROM (ZT,ZQV)
    ! TO (ZT1,ZQV1).
    !       Solution for T
    !            f(T)=cp*(T-T0)+L*(q-q0)=0
    !            with constraint q=qs(T,p0),
    !       it is solved by the method of Newton, iteration
    !       T --> T-f(T)/f'(T), with starting point ZT.
    !-------------------------------------------------
    !
    PSTACK (JLON, IPSTPT_ZT1)=PSTACK (JLON, IPSTPT_ZT)
  ENDDO
  DO JLON=KIDIA,KFDIA
    PSTACK (JLON, IPSTPT_ZQV1)=FOQS(FOEW(PSTACK (JLON, IPSTPT_ZT1),MAX(0.0_JPRB,&
    &  SIGN(1.0_JPRB,RTT-PSTACK (JLON, IPSTPT_ZT1))))/PRP(JLON,JLEV))  
    IF ((PSTACK (JLON, IPSTPT_ZQV1)<=PSTACK (JLON, IPSTPT_ZQV)).AND.(KLCL(JLON) &
    & ==-1)) THEN
      KLCL(JLON)=JLEV
    ENDIF
    IF ((PCAPE(JLON) > 0.0_JPRB).AND.(KFCL(JLON)==-1)) THEN
      KFCL(JLON)=JLEV
    ENDIF
    IF ((PSTACK (JLON, IPSTPT_ZRT) <= 0.0_JPRB).AND.(JLEV<KFCL(JLON)).AND.(JLEV<&
    &  KSTACK (JLON, IKSTPT_IPREVIOUS_NULL_ZRT)-1)) THEN
      KLNB(JLON)=JLEV
    ENDIF
    IF (PSTACK (JLON, IPSTPT_ZRT) <= 0.0_JPRB) THEN
      KSTACK (JLON, IKSTPT_IPREVIOUS_NULL_ZRT)=JLEV
    ENDIF
  ENDDO

  DO JIT=1,NCAPEITER
    DO JLON=KIDIA,KFDIA
      !
      !-------------------------------------------------
      ! LATENT HEAT
      !-------------------------------------------------
      !
      PSTACK (JLON, IPSTPT_ZDELARG0)=MAX(0.0_JPRB,SIGN(1.0_JPRB,RTT-&
      &  PSTACK (JLON, IPSTPT_ZT1)))
      PSTACK (JLON, IPSTPT_ZL0)=FOLH(PSTACK (JLON, IPSTPT_ZT1), &
      & PSTACK (JLON, IPSTPT_ZDELARG0))
      PSTACK (JLON, IPSTPT_ZFDERFOLH0)=-RV*(RGAMW+&
      & PSTACK (JLON, IPSTPT_ZDELARG0) *RGAMD)
      PSTACK (JLON, IPSTPT_ZCP0)=RCPD*(1.0_JPRB-PSTACK (JLON, IPSTPT_ZQV1))+RCPV&
      &  *PSTACK (JLON, IPSTPT_ZQV1)
      !
      !-------------------------------------------------
      ! Newton's loop to solve the supersaturation.
      !-------------------------------------------------
      !
    ENDDO
    DO JLON=KIDIA,KFDIA
      PSTACK (JLON, IPSTPT_ZZFOEW)=FOEW(PSTACK (JLON, IPSTPT_ZT1), &
      & PSTACK (JLON, IPSTPT_ZDELARG0))
    ENDDO
    DO JLON=KIDIA,KFDIA
      ZFDERQS0=FODQS(PSTACK (JLON, IPSTPT_ZQV1),PSTACK (JLON, IPSTPT_ZZFOEW)/PRP&
      &  (JLON,JLEV),FODLEW(PSTACK (JLON, IPSTPT_ZT1),                          &
      & PSTACK (JLON, IPSTPT_ZDELARG0)))
      PSTACK (JLON, IPSTPT_ZT1)=MAX(ZMINT,MIN(ZMAXT,PSTACK (JLON, IPSTPT_ZT1)-(&
      &  PSTACK (JLON, IPSTPT_ZCP0)*(PSTACK (JLON, IPSTPT_ZT1)-                &
      &  PSTACK (JLON, IPSTPT_ZT))+PSTACK (JLON, IPSTPT_ZL0)*(                 &
      &  PSTACK (JLON, IPSTPT_ZQV1)-PSTACK (JLON, IPSTPT_ZQV))) /MAX(ZMINDERI, &
      &  PSTACK (JLON, IPSTPT_ZCP0)+((RCPV-RCPD)*(PSTACK (JLON, IPSTPT_ZT1)-   &
      &  PSTACK (JLON, IPSTPT_ZT))+PSTACK (JLON, IPSTPT_ZL0))* ZFDERQS0 +(     &
      &  PSTACK (JLON, IPSTPT_ZQV1)-PSTACK (JLON, IPSTPT_ZQV))*                &
      &  PSTACK (JLON, IPSTPT_ZFDERFOLH0))))
      PSTACK (JLON, IPSTPT_ZDELARG0)=MAX(0.0_JPRB,SIGN(1.0_JPRB,RTT-&
      &  PSTACK (JLON, IPSTPT_ZT1)))
    ENDDO
    DO JLON=KIDIA,KFDIA
      PSTACK (JLON, IPSTPT_ZZFOEW)=FOEW(PSTACK (JLON, IPSTPT_ZT1), &
      & PSTACK (JLON, IPSTPT_ZDELARG0))
    ENDDO
    DO JLON=KIDIA,KFDIA
      !
      !-------------------------------------------------
      ! SATURATION SPECIFIC HUMIDITY
      !-------------------------------------------------
      !
      PSTACK (JLON, IPSTPT_ZQV1)=FOQS(PSTACK (JLON, IPSTPT_ZZFOEW)/PRP(JLON,JLEV&
      &  ))  
    ENDDO
  ENDDO

  DO JLON=KIDIA,KFDIA
    ZADD=GCAPERET*(PSTACK (JLON, IPSTPT_ZQV)-PSTACK (JLON, IPSTPT_ZQV1))
                        
    PSTACK (JLON, IPSTPT_ZSQL)=PSTACK (JLON, IPSTPT_ZQL)+ZADD*MAX(0.0_JPRB,SIGN(1.0_JPRB, &
    & PSTACK (JLON, IPSTPT_ZT1)-RTT))
    PSTACK (JLON, IPSTPT_ZSQI)=PSTACK (JLON, IPSTPT_ZQI)+ZADD*MAX(0.0_JPRB,-SIGN&
    &  (1.0_JPRB,PSTACK (JLON, IPSTPT_ZT1)-RTT))
    !
    !-------------------------------------------------
    ! MOIST ADIABATIC ASCENT.
    ! TRANSFORMATION FROM (ZT1,ZQV1) TO (ZT2,ZQV2).
    !      Solution for T
    !             f(T)=cp*(T-T0)+L*(q-q0)+phi-phi0=0
    !      either f(T)=cp*(T-T0)+L*(q-q0)-R*T*log(p/p0)=0
    !            with constraint q=qs(T,p), knowing that q0=qs(T0,p0)
    !       it is solved by the method of Newton, iteration
    !       T --> T-f(T)/f'(T), with starting point ZT1.
    !-------------------------------------------------
    !
    PSTACK (JLON, IPSTPT_ZZT)=PSTACK (JLON, IPSTPT_ZT1)
  ENDDO
  !-------------------------------------------------
  ! CALCULATION IS DIVIDED IN MORE STEPS IN ORDER
  ! TO GET MORE PRECISE VALUES
  !-------------------------------------------------
  DO JETAPES=1,NETAPES
    DO JLON=KIDIA,KFDIA
      PSTACK (JLON, IPSTPT_ZPDEPART) =PRP(JLON,JLEV)+(PRP(JLON,JLEV-1)-PRP(JLON,&
      & JLEV))*REAL(JETAPES-1)/REAL(NETAPES)  
      PSTACK (JLON, IPSTPT_ZPARRIVEE)=PRP(JLON,JLEV)+(PRP(JLON,JLEV-1)-PRP(JLON,&
      & JLEV))*REAL(JETAPES)/REAL(NETAPES)  
      PSTACK (JLON, IPSTPT_ZTDEPART)=PSTACK (JLON, IPSTPT_ZZT)
    ENDDO
    DO JLON=KIDIA,KFDIA
      PSTACK (JLON, IPSTPT_ZQVDEPART)=FOQS(FOEW(PSTACK (JLON, IPSTPT_ZTDEPART), &
      & MAX(0.0_JPRB,SIGN(1.0_JPRB,RTT-PSTACK (JLON, IPSTPT_ZTDEPART)))) /      &
      &  PSTACK (JLON, IPSTPT_ZPDEPART))
      PSTACK (JLON, IPSTPT_ZLOG)=LOG(PSTACK (JLON, IPSTPT_ZPARRIVEE)/&
      &  PSTACK (JLON, IPSTPT_ZPDEPART))
    ENDDO
    DO JIT=1,NCAPEITER
      DO JLON=KIDIA,KFDIA
        PSTACK (JLON, IPSTPT_ZZFOEW)=FOEW(PSTACK (JLON, IPSTPT_ZZT),MAX(0.0_JPRB, &
        & SIGN(1.0_JPRB,RTT-PSTACK (JLON, IPSTPT_ZZT))))
      ENDDO
      DO JLON=KIDIA,KFDIA
        !
        !-------------------------------------------------
        ! SATURATION SPECIFIC HUMIDITY
        !-------------------------------------------------
        !
        ZZQV=FOQS(PSTACK (JLON, IPSTPT_ZZFOEW)/PSTACK (JLON, IPSTPT_ZPARRIVEE))  
        !
        !-------------------------------------------------
        ! LATENT HEAT
        !-------------------------------------------------
        !
        ZDELARG=MAX(0.0_JPRB,SIGN(1.0_JPRB,RTT-PSTACK (JLON, IPSTPT_ZTDEPART)))
        !
        ! CALCULATION WHERE IT IS CONSIDERED THAT LATENT HEAT RELEASE
        ! FROM CONDENSATION IS ABSORBTED ONLY BY THE GASEOUS PORTION 
        ! OF THE PARCEL, AND NOT BY THE CONDENSATE
        !
        ZL=FOLH(PSTACK (JLON, IPSTPT_ZZT),ZDELARG)  
        ZDERL=-RV*(RGAMW+ZDELARG*RGAMD)
        !
        !-------------------------------------------------
        ! Newton's loop to solve the moist adiabatic ascent.
        !-------------------------------------------------
        !
        ZRDLOG=(RD+(RV-RD)*ZZQV)*PSTACK (JLON, IPSTPT_ZLOG)
        ZCP=RCPD*(1.0_JPRB-ZZQV)+RCPV*ZZQV 
        ZFDERQS=FODQS(ZZQV,PSTACK (JLON, IPSTPT_ZZFOEW)/                        &
        &  PSTACK (JLON, IPSTPT_ZPARRIVEE) ,FODLEW(PSTACK (JLON, IPSTPT_ZZT),MAX&
        &  (0.0_JPRB, SIGN(1.0_JPRB,RTT-PSTACK (JLON, IPSTPT_ZZT)))))
        PSTACK (JLON, IPSTPT_ZZT)=MAX(ZMINT,MIN(ZMAXT,PSTACK (JLON, IPSTPT_ZZT)-&
        &  (ZCP*(PSTACK (JLON, IPSTPT_ZZT)-PSTACK (JLON, IPSTPT_ZTDEPART)) +ZL*(&
        &  ZZQV-PSTACK (JLON, IPSTPT_ZQVDEPART))-PSTACK (JLON, IPSTPT_ZZT) *    &
        & ZRDLOG)/MAX(ZMINDERI,ZCP+((RCPV-RCPD)*(PSTACK (JLON, IPSTPT_ZZT)-     &
        &  PSTACK (JLON, IPSTPT_ZTDEPART)) +ZL-PSTACK (JLON, IPSTPT_ZLOG)*      &
        &  PSTACK (JLON, IPSTPT_ZZT)*(RV-RD))*ZFDERQS +(ZZQV-                   &
        &  PSTACK (JLON, IPSTPT_ZQVDEPART))*ZDERL-ZRDLOG)))
      ENDDO      ! JLON
    ENDDO     ! JIT
  ENDDO   !JETAPES
  
  DO JLON=KIDIA,KFDIA
    PSTACK (JLON, IPSTPT_ZZFOEW)=FOEW(PSTACK (JLON, IPSTPT_ZZT),MAX(0.0_JPRB, &
    & SIGN(1.0_JPRB,RTT-PSTACK (JLON, IPSTPT_ZZT))))
    !
    !-------------------------------------------------
    ! DRY ADIABATIC ASCENT.
    !-------------------------------------------------
    !
    PSTACK (JLON, IPSTPT_ZDT)=PSTACK (JLON, IPSTPT_ZT)*(PRP(JLON,JLEV-1)/PRP( &
    & JLON,JLEV))**((RD+(RV-RD) *PSTACK (JLON, IPSTPT_ZQV))/(RCPD*(1.0_JPRB-  &
    &  PSTACK (JLON, IPSTPT_ZQV))+RCPV*PSTACK (JLON, IPSTPT_ZQV)))  
    !
  ENDDO
  DO JLON=KIDIA,KFDIA
    ZT2=PSTACK (JLON, IPSTPT_ZZT)

    ZQV2=FOQS(PSTACK (JLON, IPSTPT_ZZFOEW)/PRP(JLON,JLEV-1))

    ZADD=GCAPERET*(PSTACK (JLON, IPSTPT_ZQV1)-ZQV2)*MAX(0.0_JPRB,SIGN(1.0_JPRB,&
    &  PSTACK (JLON, IPSTPT_ZQV1)-ZQV2))
    PSTACK (JLON, IPSTPT_ZSQL)=PSTACK (JLON, IPSTPT_ZSQL)+ZADD*MAX(0.0_JPRB,SIGN&
    &  (1.0_JPRB,ZT2-RTT))
    PSTACK (JLON, IPSTPT_ZSQI)=PSTACK (JLON, IPSTPT_ZSQI)+ZADD*MAX(0.0_JPRB,- &
    & SIGN(1.0_JPRB,ZT2-RTT))
    !
    !-------------------------------------------------
    ! UPDATE PARCEL STATE. The result of moist adiabatic ascent.
    !-------------------------------------------------
    !
    ZST=ZT2
    PSTACK (JLON, IPSTPT_ZSQV)=ZQV2
    !-------------------------------------------------
    !  VALUES FROM DRY ADIABATIC OR MOIST ADIABATIC ASCENT ARE CHOSEN 
    !-------------------------------------------------
    !
    ZADD=MAX(0.0_JPRB,SIGN(1.0_JPRB,PSTACK (JLON, IPSTPT_ZQV)-&
    &  PSTACK (JLON, IPSTPT_ZQS)))
    PSTACK (JLON, IPSTPT_ZT)=ZST*ZADD + PSTACK (JLON, IPSTPT_ZDT)*(1.0_JPRB-ZADD&
    &  )
    PSTACK (JLON, IPSTPT_ZQV)=PSTACK (JLON, IPSTPT_ZSQV)*ZADD + &
    &  PSTACK (JLON, IPSTPT_ZQV)*(1.0_JPRB-ZADD)
    PSTACK (JLON, IPSTPT_ZQL)=PSTACK (JLON, IPSTPT_ZSQL)*ZADD
    PSTACK (JLON, IPSTPT_ZQI)=PSTACK (JLON, IPSTPT_ZSQI)*ZADD
    !-----------------------------------------------------
    ! Entrainement
    !-----------------------------------------------------
    IF (RENTRA > 0.0_JPRB) THEN
      ZDZ=(PRP(JLON,JLEV)-PRP(JLON,JLEV-1))/(0.5*(PRP(JLON,JLEV)+ PRP(JLON,JLEV-&
      &  1)))*(RD+(RV-RD)*(0.5*(PSTACK (JLON, IPSTPT_ZQVIN+JLEV-(1))+           &
      & (PSTACK (JLON, IPSTPT_ZQVIN+JLEV-1-(1))))))*0.5*(                       &
      &  PSTACK (JLON, IPSTPT_ZTIN+JLEV-(1))+                                   &
      & (PSTACK (JLON, IPSTPT_ZTIN+JLEV-1-(1))))/RG
      IF(PSTACK (JLON, IPSTPT_ZT) > PSTACK (JLON, IPSTPT_ZTIN+JLEV-1-(1))) THEN
        PSTACK (JLON, IPSTPT_ZT)=MAX(PSTACK (JLON, IPSTPT_ZTIN+JLEV-1-(1)),&
        &  PSTACK (JLON, IPSTPT_ZT)+RENTRA*ZDZ*(                           &
        &  PSTACK (JLON, IPSTPT_ZTIN+JLEV-1-(1))-PSTACK (JLON, IPSTPT_ZT)))
      ELSE
        PSTACK (JLON, IPSTPT_ZT)=MIN(PSTACK (JLON, IPSTPT_ZTIN+JLEV-1-(1)),&
        &  PSTACK (JLON, IPSTPT_ZT)+RENTRA*ZDZ*(                           &
        &  PSTACK (JLON, IPSTPT_ZTIN+JLEV-1-(1))-PSTACK (JLON, IPSTPT_ZT)))
      ENDIF
      IF(PSTACK (JLON, IPSTPT_ZQV) > PSTACK (JLON, IPSTPT_ZQVIN+JLEV-1-(1))&
      &  ) THEN
        PSTACK (JLON, IPSTPT_ZQV)=MAX(PSTACK (JLON, IPSTPT_ZQVIN+JLEV-1-(1)),&
        &  PSTACK (JLON, IPSTPT_ZQV)+RENTRA*ZDZ*(                            &
        &  PSTACK (JLON, IPSTPT_ZQVIN+JLEV-1-(1))-PSTACK (JLON, IPSTPT_ZQV)))
      ELSE
        PSTACK (JLON, IPSTPT_ZQV)=MIN(PSTACK (JLON, IPSTPT_ZQVIN+JLEV-1-(1)),&
        &  PSTACK (JLON, IPSTPT_ZQV)+RENTRA*ZDZ*(                            &
        &  PSTACK (JLON, IPSTPT_ZQVIN+JLEV-1-(1))-PSTACK (JLON, IPSTPT_ZQV)))
      ENDIF
    ENDIF
  ENDDO                     ! JLON
ENDDO                     !JLEV


END SUBROUTINE FPCINCAPE
