#ifdef GPU
ATTRIBUTES (GLOBAL) &
#endif
SUBROUTINE RUN_ACPCMT ( KIDIA,KFDIA,KLON,KTDIA,KLEV,KTRA,&
  & PALPH,PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PLH,PR,&
  & PDELP,PLNPR,&
  & PQ,PQI,PQL,PRR,PS,PQLIS,PQSAT,PQW,&
  & PRDELP,PCVGQ,PT,PTW,PU,PV,PTKE,PTRA,&
  & PQLCONV, PQICONV , PQRCONV, PQSCONV, &
  & PGM, PTS, PQS, PNEIJ, PLSM, PVETAF, &
  & PDIFCQ,PDIFCQL,PDIFCQI,PDIFCQLC,PDIFCQIC,PDIFCS,PDIFCTH,&
  & PFCCQL,PFCCQN,PSTRCU,PSTRCV,PSTRCTRA,&
  & PFIMCC,PFPEVPCL,PFPEVPCN,&
  & PFPLCL,PFPLCN,PMF_UP,&
  & PFPFPCL,PFPFPCN,&
  & PFEDQLC, PFEDQIC, PFEDQRC, PFEDQSC,&
  & PFCNEGQLC,PFCNEGQIC,PFCNEGQRC,PFCNEGQSC, &
  & KNLAB,&
  & PNEBC,PQLIC,PTU,PQU,PQC_DET_PCMT,PCSGC, &
  & KNND, PCAPE,PAIPCMT,PALF_CAPE,PALF_CVGQ,&
  & PUDAL,PUDOM,PDDAL,PDDOM, KSTACK, PSTACK, KPSTSZ, KKSTSZ, KPSTPT, KKSTPT, NGPBLKS)

USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTRA

REAL(KIND=JPRB), INTENT(IN)    :: PALPH(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHI(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PAPHIF(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRS(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PAPRSF(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PCP(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PLH(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PR(KLON,KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PDELP(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PLNPR(KLON,KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PQ(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQI(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQL(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PS(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PRR(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQLIS(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQSAT(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQW(KLON,KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PRDELP(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PCVGQ(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PT(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PTW(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PU(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PV(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PTKE(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PTRA(KLON, KLEV, KTRA,NGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PQLCONV(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQICONV(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQRCONV(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQSCONV(KLON,KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(IN)    :: PGM(KLON,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PTS(KLON,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PQS(KLON,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PNEIJ(KLON,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PLSM(KLON,NGPBLKS)
REAL(KIND=JPRB), INTENT(IN)    :: PVETAF(KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQ(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQL(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQI(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQLC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCQIC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCS(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PDIFCTH(KLON,0:KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQL(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFCCQN(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCU(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCV(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)     :: PMF_UP(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PSTRCTRA(KLON, 0:KLEV, KTRA,NGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFIMCC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCL(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPEVPCN(KLON,0:KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCL(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPLCN(KLON,0:KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT)   :: PFPFPCL(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT)   :: PFPFPCN(KLON,0:KLEV,NGPBLKS)

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQLC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQIC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQRC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFEDQSC(KLON,0:KLEV,NGPBLKS)

REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQLC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQIC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQRC(KLON,0:KLEV,NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFCNEGQSC(KLON,0:KLEV,NGPBLKS)

INTEGER(KIND=JPIM), INTENT(INOUT) :: KNLAB(KLON,KLEV,NGPBLKS)
INTEGER(KIND=JPIM), INTENT(INOUT) :: KNND(KLON,NGPBLKS)

REAL(KIND=JPRB), INTENT(OUT)   :: PNEBC(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PQLIC(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PTU(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PQU(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PQC_DET_PCMT(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PCSGC(KLON,KLEV,NGPBLKS)

REAL(KIND=JPRB), INTENT(OUT)   :: PCAPE(KLON,NGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PAIPCMT(KLON,NGPBLKS)

REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CAPE(KLON,NGPBLKS)
REAL(KIND=JPRB), INTENT(OUT)   :: PALF_CVGQ(KLON,NGPBLKS)

REAL(KIND=JPRB), INTENT(INOUT) :: PUDAL(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT) :: PUDOM(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDAL(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDOM(KLON,KLEV,NGPBLKS)
REAL(KIND=JPRB),   INTENT(OUT)   :: PSTACK (KLON, KPSTSZ,NGPBLKS)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSTACK (KLON, KKSTSZ,NGPBLKS)
INTEGER(KIND=JPIM),INTENT(IN)    :: KPSTSZ, KKSTSZ, KPSTPT, KKSTPT
INTEGER(KIND=JPIM),INTENT(IN)    :: NGPBLKS

#include "acpcmt.intfb.h"

INTEGER (KIND=JPIM) :: IBL, JIDIA, JFDIA, JJ


#ifdef GPU
  IBL    = BLOCKIDX%X
  JIDIA  = THREADIDX%X
  JFDIA  = THREADIDX%X

#else

!$OMP PARALLEL DO PRIVATE (IBL, JIDIA, JFDIA, JJ)

DO IBL = 1, NGPBLKS

  DO JJ = 1, KLON
  
  JIDIA = JJ
  JFDIA = JJ

#endif

  CALL ACPCMT (JIDIA, JFDIA,KLON,KTDIA,KLEV,KTRA,&
    & PALPH (:,:,IBL),PAPHI (:,:,IBL),PAPHIF (:,:,IBL),PAPRS (:,:,IBL),&
    & PAPRSF (:,:,IBL),PCP (:,:,IBL),PLH (:,:,IBL),PR (:,:,IBL),&
    & PDELP (:,:,IBL),PLNPR (:,:,IBL),PQ (:,:,IBL),PQI (:,:,IBL),PQL (:,:,IBL),PRR (:,:,IBL),&
    & PS (:,:,IBL),PQLIS (:,:,IBL),PQSAT (:,:,IBL),PQW (:,:,IBL),&
    & PRDELP (:,:,IBL),PCVGQ (:,:,IBL),PT (:,:,IBL),PTW (:,:,IBL),&
    & PU (:,:,IBL),PV (:,:,IBL),PTKE (:,:,IBL),PTRA (:,:,:,IBL),&
    & PQLCONV (:,:,IBL), PQICONV (:,:,IBL) , PQRCONV (:,:,IBL), PQSCONV (:,:,IBL), &
    & PGM (:,IBL), PTS (:,IBL), PQS (:,IBL), PNEIJ (:,IBL), &
    & PLSM (:,IBL), PVETAF (:,IBL),PDIFCQ (:,:,IBL),PDIFCQL (:,:,IBL),PDIFCQI (:,:,IBL),PDIFCQLC (:,:,IBL),&
    & PDIFCQIC (:,:,IBL),PDIFCS (:,:,IBL),PDIFCTH (:,:,IBL),&
    & PFCCQL (:,:,IBL),PFCCQN (:,:,IBL),PSTRCU (:,:,IBL),PSTRCV (:,:,IBL),&
    & PSTRCTRA (:,:,:,IBL),PFIMCC (:,:,IBL),PFPEVPCL (:,:,IBL),PFPEVPCN (:,:,IBL),&
    & PFPLCL (:,:,IBL),PFPLCN (:,:,IBL),PMF_UP (:,:,IBL),PFPFPCL (:,:,IBL),PFPFPCN (:,:,IBL),&
    & PFEDQLC (:,:,IBL), PFEDQIC (:,:,IBL), PFEDQRC (:,:,IBL), PFEDQSC (:,:,IBL),&
    & PFCNEGQLC (:,:,IBL),PFCNEGQIC (:,:,IBL),PFCNEGQRC (:,:,IBL),PFCNEGQSC (:,:,IBL), &
    & KNLAB (:,:,IBL),PNEBC (:,:,IBL),PQLIC (:,:,IBL),PTU (:,:,IBL),PQU (:,:,IBL),&
    & PQC_DET_PCMT (:,:,IBL),PCSGC (:,:,IBL),KNND (:,IBL), PCAPE (:,IBL),PAIPCMT (:,IBL),&
    & PALF_CAPE (:,IBL),PALF_CVGQ (:,IBL),&
    & PUDAL (:,:,IBL),PUDOM (:,:,IBL),PDDAL (:,:,IBL),PDDOM (:,:,IBL),&
    & KSTACK (:,:,IBL), PSTACK (:,:,IBL), KPSTSZ, KKSTSZ, KPSTPT, KKSTPT)


#ifdef GPU

#else

  ENDDO

ENDDO
!$OMP END PARALLEL DO
#endif


END SUBROUTINE
