SUBROUTINE TOTO

DO JLEV = 1, KLEV
  DO JLON = 1, KLON
    IF (LLCOND (JLON, JLEV)) THEN
    IN (JLON) = KN (JLON, JLEV)
    ENDIF
    JN (JLON, JLEV) = KN (JLON, JLEV)
    LLCOND (JLON, JLEV) = ZA (JLON, JLEV+1)
  ENDDO
ENDDO

END SUBROUTINE TOTO
