
USE PARKIND1, ONLY : JPIM, JPRB
USE XRD_GETOPTIONS

USE LOAD_MOD

IMPLICIT NONE

INTERFACE SETALL
  PROCEDURE SETALLI1
  PROCEDURE SETALLI2
  PROCEDURE SETALLX1
  PROCEDURE SETALLX2
  PROCEDURE SETALLX3
END INTERFACE

INTERFACE DDIFF
  PROCEDURE DDIFFX1
  PROCEDURE DDIFFX2
  PROCEDURE DDIFFX3
END INTERFACE

INTEGER(KIND=JPIM) :: KFDIA
INTEGER(KIND=JPIM) :: KIDIA
INTEGER(KIND=JPIM) :: KLEV
INTEGER(KIND=JPIM) :: KLON
INTEGER(KIND=JPIM) :: KTDIA
INTEGER(KIND=JPIM) :: KTRA

INTEGER(KIND=JPIM), ALLOCATABLE :: IFDIA (:)

REAL(KIND=JPRB), POINTER :: PALPH_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PAPHI_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PAPHIF_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PAPRS_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PAPRSF_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PCP_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PLH_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PR_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PDELP_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PLNPR_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PQ_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQI_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PS_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PRR_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQLIS_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQSAT_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQW_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PRDELP_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PCVGQ_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PT_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PTW_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PU_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PTKE_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PTRA_ALL (:, :, :,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PQLCONV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQICONV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQRCONV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQSCONV_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PGM_ALL (:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PTS_ALL (:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQS_ALL (:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PNEIJ_ALL (:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PLSM_ALL (:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PVETAF_ALL(:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PDIFCQ_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PDIFCQL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PDIFCQI_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PDIFCQLC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PDIFCQIC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PDIFCS_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PDIFCTH_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PFCCQL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFCCQN_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PSTRCU_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PSTRCV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PMF_UP_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PSTRCTRA_ALL (:, :, :,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PFIMCC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFPEVPCL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFPEVPCN_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PFPLCL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFPLCN_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PFPFPCL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFPFPCN_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PFEDQLC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFEDQIC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFEDQRC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFEDQSC_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PFCNEGQLC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFCNEGQIC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFCNEGQRC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PFCNEGQSC_ALL (:,:,:) => NULL ()

INTEGER(KIND=JPIM), POINTER :: KNLAB_ALL (:,:,:) => NULL ()
INTEGER(KIND=JPIM), POINTER :: KNND_ALL (:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PNEBC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQLIC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PTU_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQU_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PQC_DET_PCMT_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PCSGC_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PCAPE_ALL (:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PAIPCMT_ALL (:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PALF_CAPE_ALL (:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PALF_CVGQ_ALL (:,:) => NULL ()

REAL(KIND=JPRB), POINTER :: PUDAL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PUDOM_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PDDAL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB), POINTER :: PDDOM_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB),    POINTER    :: PSTACK_ALL (:,:,:) => NULL ()
INTEGER(KIND=JPIM), POINTER    :: KSTACK_ALL (:,:,:) => NULL ()
INTEGER(KIND=JPIM) :: KKSTSZ, KPSTSZ, KKSTPT, KPSTPT

INTEGER :: ICOUNT, IBL, JJ, JIDIA, JFDIA
INTEGER :: ICOUNT1, KLON1
INTEGER :: ICOUNT0, KLON0
LOGICAL :: LLDIFF
CHARACTER (LEN=32) :: CLCASE

#include "acpcmt.intfb.h"

CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
ICOUNT1 = 0
CALL GETOPTION ("--count", ICOUNT1)
KLON1 = 0
CALL GETOPTION ("--nproma", KLON1)
CALL CHECKOPTIONS ()

OPEN (77, FORM='FORMATTED', FILE=TRIM (CLCASE)//'/ACPCMT.COUNT')
READ (77, *) ICOUNT
CLOSE (77)

ALLOCATE (IFDIA (ICOUNT))

CALL ACPCMT_LOAD_ALL (TRIM (CLCASE)//'/ACPCMT.CONST')

CALL OPEN_LOAD (TRIM (CLCASE)//"/ACPCMT")

IF (ICOUNT1 == 0) ICOUNT1 = ICOUNT

PRINT *, "-- READ"

DO IBL = 1, ICOUNT

  PRINT *, IBL

  CALL LOAD (ILUN_IN, IFDIA (IBL))
  CALL LOAD (ILUN_IN, KIDIA)
  CALL LOAD (ILUN_IN, KLEV)
  CALL LOAD (ILUN_IN, KLON)
  IF (KLON1 == 0) KLON1 = KLON
  CALL LOAD (ILUN_IN, KTDIA)
  CALL LOAD (ILUN_IN, KTRA)
#define SET(x) CALL SETALL (x##_ALL)
  SET (PALPH)
  SET (PAPHI)
  SET (PAPHIF)
  SET (PAPRS)
  SET (PAPRSF)
  SET (PCP)
  SET (PLH)
  SET (PR)
  SET (PDELP)
  SET (PLNPR)
  SET (PQ)
  SET (PQI)
  SET (PQL)
  SET (PS)
  SET (PRR)
  SET (PQLIS)
  SET (PQSAT)
  SET (PQW)
  SET (PRDELP)
  SET (PCVGQ)
  SET (PT)
  SET (PTW)
  SET (PU)
  SET (PV)
  SET (PTKE)
  SET (PTRA)
  SET (PQLCONV)
  SET (PQICONV)
  SET (PQRCONV)
  SET (PQSCONV)
  SET (PGM)
  SET (PTS)
  SET (PQS)
  SET (PNEIJ)
  SET (PLSM)
  CALL SETALL (PVETAF_ALL, .FALSE.)
  SET (PDIFCQ)
  SET (PDIFCQL)
  SET (PDIFCQI)
  SET (PDIFCQLC)
  SET (PDIFCQIC)
  SET (PDIFCS)
  SET (PDIFCTH)
  SET (PFCCQL)
  SET (PFCCQN)
  SET (PSTRCU)
  SET (PSTRCV)
  SET (PMF_UP) 
  SET (PSTRCTRA)
  SET (PFIMCC)
  SET (PFPEVPCL)
  SET (PFPEVPCN)
  SET (PFPLCL)
  SET (PFPLCN)
  SET (PFPFPCL)
  SET (PFPFPCN)
  SET (PFEDQLC)
  SET (PFEDQIC)
  SET (PFEDQRC)
  SET (PFEDQSC)
  SET (PFCNEGQLC)
  SET (PFCNEGQIC)
  SET (PFCNEGQRC)
  SET (PFCNEGQSC)
  SET (KNLAB)
  SET (KNND)
  SET (PNEBC)
  SET (PQLIC)
  SET (PTU)
  SET (PQU) 
  SET (PQC_DET_PCMT)
  SET (PCSGC) 
  SET (PCAPE)
  SET (PAIPCMT)
  SET (PALF_CAPE)
  SET (PALF_CVGQ)
  SET (PUDAL)
  SET (PUDOM)
  SET (PDDAL)
  SET (PDDOM)
#undef SET
ENDDO


KLON0 = KLON; ICOUNT0 = ICOUNT
KLON = KLON1; ICOUNT = ICOUNT1

KFDIA = KLON

KPSTPT = 1
KKSTPT = 1

KPSTSZ =   200 * KLEV
KKSTSZ =   20 * KLEV

ALLOCATE (KSTACK_ALL (KLON, KKSTSZ, ICOUNT))
ALLOCATE (PSTACK_ALL (KLON, KPSTSZ, ICOUNT))

KSTACK_ALL = 1234_JPIM
PSTACK_ALL = 1234._JPRB

PRINT *, "-- RUN"

!$OMP PARALLEL DO PRIVATE (IBL,JJ,JIDIA,JFDIA)
DO IBL = 1, ICOUNT

  PRINT *, IBL

  JIDIA = KIDIA
  JFDIA = KFDIA

  DO JJ = KIDIA, KFDIA

  JIDIA = JJ
  JFDIA = JJ

  CALL ACPCMT (JIDIA, JFDIA,KLON,KTDIA,KLEV,KTRA,&
    & PALPH_ALL (:,:,IBL),PAPHI_ALL (:,:,IBL),PAPHIF_ALL (:,:,IBL),PAPRS_ALL (:,:,IBL),&
    & PAPRSF_ALL (:,:,IBL),PCP_ALL (:,:,IBL),PLH_ALL (:,:,IBL),PR_ALL (:,:,IBL),&
    & PDELP_ALL (:,:,IBL),PLNPR_ALL (:,:,IBL),&
    & PQ_ALL (:,:,IBL),PQI_ALL (:,:,IBL),PQL_ALL (:,:,IBL),PRR_ALL (:,:,IBL),&
    & PS_ALL (:,:,IBL),PQLIS_ALL (:,:,IBL),PQSAT_ALL (:,:,IBL),PQW_ALL (:,:,IBL),&
    & PRDELP_ALL (:,:,IBL),PCVGQ_ALL (:,:,IBL),PT_ALL (:,:,IBL),PTW_ALL (:,:,IBL),&
    & PU_ALL (:,:,IBL),PV_ALL (:,:,IBL),PTKE_ALL (:,:,IBL),PTRA_ALL (:,:,:,IBL),&
    & PQLCONV_ALL (:,:,IBL), PQICONV_ALL (:,:,IBL) , PQRCONV_ALL (:,:,IBL), PQSCONV_ALL (:,:,IBL), &
    & PGM_ALL (:,IBL), PTS_ALL (:,IBL), PQS_ALL (:,IBL), PNEIJ_ALL (:,IBL), &
    & PLSM_ALL (:,IBL), PVETAF_ALL (:,IBL), &
    & PDIFCQ_ALL (:,:,IBL),PDIFCQL_ALL (:,:,IBL),PDIFCQI_ALL (:,:,IBL),PDIFCQLC_ALL (:,:,IBL),&
    & PDIFCQIC_ALL (:,:,IBL),PDIFCS_ALL (:,:,IBL),PDIFCTH_ALL (:,:,IBL),&
    & PFCCQL_ALL (:,:,IBL),PFCCQN_ALL (:,:,IBL),PSTRCU_ALL (:,:,IBL),PSTRCV_ALL (:,:,IBL),&
    & PSTRCTRA_ALL (:,:,:,IBL),&
    & PFIMCC_ALL (:,:,IBL),PFPEVPCL_ALL (:,:,IBL),PFPEVPCN_ALL (:,:,IBL),&
    & PFPLCL_ALL (:,:,IBL),PFPLCN_ALL (:,:,IBL),PMF_UP_ALL (:,:,IBL),&
    & PFPFPCL_ALL (:,:,IBL),PFPFPCN_ALL (:,:,IBL),&
    & PFEDQLC_ALL (:,:,IBL), PFEDQIC_ALL (:,:,IBL), PFEDQRC_ALL (:,:,IBL), PFEDQSC_ALL (:,:,IBL),&
    & PFCNEGQLC_ALL (:,:,IBL),PFCNEGQIC_ALL (:,:,IBL),PFCNEGQRC_ALL (:,:,IBL),PFCNEGQSC_ALL (:,:,IBL), &
    & KNLAB_ALL (:,:,IBL),&
    & PNEBC_ALL (:,:,IBL),PQLIC_ALL (:,:,IBL),PTU_ALL (:,:,IBL),PQU_ALL (:,:,IBL),&
    & PQC_DET_PCMT_ALL (:,:,IBL),PCSGC_ALL (:,:,IBL), &
    & KNND_ALL (:,IBL), PCAPE_ALL (:,IBL),PAIPCMT_ALL (:,IBL),&
    & PALF_CAPE_ALL (:,IBL),PALF_CVGQ_ALL (:,IBL),&
    & PUDAL_ALL (:,:,IBL),PUDOM_ALL (:,:,IBL),PDDAL_ALL (:,:,IBL),PDDOM_ALL (:,:,IBL),&
    & KSTACK_ALL (:,:,IBL), PSTACK_ALL (:,:,IBL), KPSTSZ, KKSTSZ, KPSTPT, KKSTPT)

  ENDDO

ENDDO
!$OMP END PARALLEL DO

IF (LLDIFF .AND. ICOUNT0 == ICOUNT1 .AND. KLON0 == KLON1) THEN

PRINT *, "-- DIFF"

DO IBL = 1, ICOUNT0

  PRINT *, IBL

#define DIFF(x) CALL DDIFF (#x, x##_ALL)

  DIFF (PDIFCQ)
  DIFF (PDIFCQL)
  DIFF (PDIFCQI)
  DIFF (PDIFCQLC)
  DIFF (PDIFCQIC)
  DIFF (PDIFCS)
  DIFF (PDIFCTH)
  DIFF (PFCCQL)
  DIFF (PFCCQN)
  DIFF (PSTRCU)
  DIFF (PSTRCV)
  DIFF (PMF_UP)
  DIFF (PSTRCTRA)
  DIFF (PFIMCC)
  DIFF (PFPEVPCL)
  DIFF (PFPEVPCN)
  DIFF (PFPLCL)
  DIFF (PFPLCN)
  DIFF (PFPFPCL)
  DIFF (PFPFPCN)
  DIFF (PFEDQLC)
  DIFF (PFEDQIC)
  DIFF (PFEDQRC)
  DIFF (PFEDQSC)
  DIFF (PFCNEGQLC)
  DIFF (PFCNEGQIC)
  DIFF (PFCNEGQRC)
  DIFF (PFCNEGQSC)
  DIFF (PNEBC)
  DIFF (PQLIC)
  DIFF (PTU)
  DIFF (PQU)
  DIFF (PQC_DET_PCMT)
  DIFF (PCSGC)
  DIFF (PCAPE)
  DIFF (PAIPCMT)
  DIFF (PALF_CAPE)
  DIFF (PALF_CVGQ)
  DIFF (PUDAL)
  DIFF (PUDOM)
  DIFF (PDDAL)
  DIFF (PDDOM)

#undef DIFF

ENDDO

ENDIF

CALL CLOSE_LOAD

#undef SAVEA

CONTAINS

SUBROUTINE SETALLI1 (KALL)

INTEGER (KIND=JPIM), POINTER :: KALL (:,:)
INTEGER (KIND=JPIM), POINTER :: K (:)
INTEGER :: JLON, JLON1, IBL1, IBL1R, IGP

CALL LOAD (ILUN_IN, K)

IF (IBL == 1) THEN
  ALLOCATE (KALL (KLON1, ICOUNT1))
ENDIF

DO JLON = 1, IFDIA (IBL)
  IGP = JLON + (IBL - 1) * KLON
  IBL1 = 1 + (IGP - 1) / KLON1
  JLON1 = 1 + MODULO (IGP - 1, KLON1)
  IF (IBL1 <= ICOUNT1) THEN
    KALL (JLON1, IBL1) = K (JLON)
  ENDIF
ENDDO
DO JLON = IFDIA (IBL)+1, KLON
  IGP = JLON + (IBL - 1) * KLON
  IBL1 = 1 + (IGP - 1) / KLON1
  JLON1 = 1 + MODULO (IGP - 1, KLON1)
  IF (IBL1 <= ICOUNT1) THEN
    KALL (JLON1, IBL1) = K (IFDIA (IBL))
  ENDIF
ENDDO

IF (IBL == ICOUNT) THEN
  IGP = IBL * KLON
  IBL1R = (IGP - 1) / KLON1
  DO IBL1 = IBL1R + 1, ICOUNT1
    KALL (:, IBL1) = KALL (:, 1 + MODULO (IBL1, IBL1R))
  ENDDO
ENDIF

DEALLOCATE (K)
NULLIFY (K)

END SUBROUTINE

SUBROUTINE SETALLI2 (KALL)

INTEGER (KIND=JPIM), POINTER :: KALL (:,:,:)
INTEGER (KIND=JPIM), POINTER :: K (:,:)
INTEGER :: KLB (2), KUB (2), JLON, JLON1, IBL1R, IBL1, IGP

CALL LOAD (ILUN_IN, K)

KLB = LBOUND (K)
KUB = UBOUND (K)

IF (IBL == 1) THEN
  ALLOCATE (KALL (KLON1, KLB (2):KUB (2), ICOUNT1))
ENDIF

DO JLON = 1, IFDIA (IBL)
  IGP = JLON + (IBL - 1) * KLON
  IBL1 = 1 + (IGP - 1) / KLON1
  JLON1 = 1 + MODULO (IGP - 1, KLON1)
  IF (IBL1 <= ICOUNT1) THEN
    KALL (JLON1, :, IBL1) = K (JLON, :)
  ENDIF
ENDDO
DO JLON = IFDIA (IBL)+1, KLON
  IGP = JLON + (IBL - 1) * KLON
  IBL1 = 1 + (IGP - 1) / KLON1
  JLON1 = 1 + MODULO (IGP - 1, KLON1)
  IF (IBL1 <= ICOUNT1) THEN
    KALL (JLON1, :, IBL1) = K (IFDIA (IBL), :)
  ENDIF
ENDDO

IF (IBL == ICOUNT) THEN
  IGP = IBL * KLON
  IBL1R = (IGP - 1) / KLON1
  DO IBL1 = IBL1R + 1, ICOUNT1
    KALL (:, :, IBL1) = KALL (:, :, 1 + MODULO (IBL1, IBL1R))
  ENDDO
ENDIF


DEALLOCATE (K)
NULLIFY (K)

END SUBROUTINE

SUBROUTINE SETALLX1 (PALL, LDPROMA)

REAL (KIND=JPRB), POINTER :: PALL (:,:)
REAL (KIND=JPRB), POINTER :: P (:)
LOGICAL, OPTIONAL :: LDPROMA
INTEGER :: KLB (1), KUB (1), JLON, JLON1, IBL1, IBL1R, IGP
LOGICAL :: LLPROMA

LLPROMA = .TRUE.
IF (PRESENT (LDPROMA)) LLPROMA = LDPROMA

CALL LOAD (ILUN_IN, P)

IF (LLPROMA) THEN

  IF (IBL == 1) THEN
    ALLOCATE (PALL (KLON1, ICOUNT1))
  ENDIF

  DO JLON = 1, IFDIA (IBL)
    IGP = JLON + (IBL - 1) * KLON
    IBL1 = 1 + (IGP - 1) / KLON1
    JLON1 = 1 + MODULO (IGP - 1, KLON1)
    IF (IBL1 <= ICOUNT1) THEN
      PALL (JLON1, IBL1) = P (JLON)
    ENDIF
  ENDDO
  DO JLON = IFDIA (IBL)+1, KLON
    IGP = JLON + (IBL - 1) * KLON
    IBL1 = 1 + (IGP - 1) / KLON1
    JLON1 = 1 + MODULO (IGP - 1, KLON1)
    IF (IBL1 <= ICOUNT1) THEN
      PALL (JLON1, IBL1) = P (IFDIA (IBL))
    ENDIF
  ENDDO

  IF (IBL == ICOUNT) THEN
    IGP = IBL * KLON
    IBL1R = (IGP - 1) / KLON1
    DO IBL1 = IBL1R + 1, ICOUNT1
      PALL (:, IBL1) = PALL (:, 1 + MODULO (IBL1, IBL1R))
    ENDDO
  ENDIF

ELSE

  KLB = LBOUND (P)
  KUB = UBOUND (P)

  IF (IBL == 1) THEN
    ALLOCATE (PALL (KLB (1):KUB (1), ICOUNT1))
  ENDIF

  PALL (:,1) = P

  IF (IBL == ICOUNT) THEN
    DO IBL1 = 2, ICOUNT1
      PALL (:,IBL1) = PALL (:,1)
    ENDDO
  ENDIF

ENDIF

DEALLOCATE (P)
NULLIFY (P)

END SUBROUTINE

SUBROUTINE SETALLX2 (PALL)

REAL (KIND=JPRB), POINTER :: PALL (:,:,:)
REAL (KIND=JPRB), POINTER :: P (:,:)
INTEGER :: KLB (2), KUB (2), JLON, JLON1, IBL1R, IBL1, IGP

CALL LOAD (ILUN_IN, P)

KLB = LBOUND (P)
KUB = UBOUND (P)

IF (IBL == 1) THEN
  ALLOCATE (PALL (KLON1, KLB (2):KUB (2), ICOUNT1))
ENDIF

DO JLON = 1, IFDIA (IBL)
  IGP = JLON + (IBL - 1) * KLON
  IBL1 = 1 + (IGP - 1) / KLON1
  JLON1 = 1 + MODULO (IGP - 1, KLON1)
  IF (IBL1 <= ICOUNT1) THEN
    PALL (JLON1, :, IBL1) = P (JLON, :)
  ENDIF
ENDDO
DO JLON = IFDIA (IBL)+1, KLON
  IGP = JLON + (IBL - 1) * KLON
  IBL1 = 1 + (IGP - 1) / KLON1
  JLON1 = 1 + MODULO (IGP - 1, KLON1)
  IF (IBL1 <= ICOUNT1) THEN
    PALL (JLON1, :, IBL1) = P (IFDIA (IBL), :)
  ENDIF
ENDDO

IF (IBL == ICOUNT) THEN
  IGP = IBL * KLON
  IBL1R = (IGP - 1) / KLON1
  DO IBL1 = IBL1R + 1, ICOUNT1
    PALL (:, :, IBL1) = PALL (:, :, 1 + MODULO (IBL1, IBL1R))
  ENDDO
ENDIF

DEALLOCATE (P)
NULLIFY (P)

END SUBROUTINE

SUBROUTINE SETALLX3 (PALL)

REAL (KIND=JPRB), POINTER :: PALL (:,:,:,:)
REAL (KIND=JPRB), POINTER :: P (:,:,:)
INTEGER :: KLB (3), KUB (3), JLON, JLON1, IBL1R, IBL1, IGP

CALL LOAD (ILUN_IN, P)

KLB = LBOUND (P)
KUB = UBOUND (P)

IF (IBL == 1) THEN
  ALLOCATE (PALL (KLON1, KLB (2):KUB (2), KLB (3):KUB (3), ICOUNT1))
ENDIF

DO JLON = 1, IFDIA (IBL)
  IGP = JLON + (IBL - 1) * KLON
  IBL1 = 1 + (IGP - 1) / KLON1
  JLON1 = 1 + MODULO (IGP - 1, KLON1)
  IF (IBL1 <= ICOUNT1) THEN
    PALL (JLON1, :, :, IBL1) = P (JLON, :, :)
  ENDIF
ENDDO
DO JLON = IFDIA (IBL)+1, KLON
  IGP = JLON + (IBL - 1) * KLON
  IBL1 = 1 + (IGP - 1) / KLON1
  JLON1 = 1 + MODULO (IGP - 1, KLON1)
  IF (IBL1 <= ICOUNT1) THEN
    PALL (JLON1, :, :, IBL1) = P (IFDIA (IBL), :, :)
  ENDIF
ENDDO

IF (IBL == ICOUNT) THEN
  IGP = IBL * KLON
  IBL1R = (IGP - 1) / KLON1
  DO IBL1 = IBL1R + 1, ICOUNT1
    PALL (:, :, :, IBL1) = PALL (:, :, :, 1 + MODULO (IBL1, IBL1R))
  ENDDO
ENDIF

DEALLOCATE (P)
NULLIFY (P)

END SUBROUTINE

SUBROUTINE DDIFFX1 (CDNAME, PALL)

CHARACTER(LEN=*) :: CDNAME
REAL (KIND=JPRB) :: PALL (:,:)
REAL (KIND=JPRB), POINTER :: P (:)
INTEGER :: IGP, IBL1, IBL1A, IBL1B, IIDIA1, IFDIA1

CALL LOAD (ILUN_OUT, P)

IF (KFDIA == IFDIA (IBL)) &
CALL DIFF (CDNAME, PALL (:, IBL), P)

DEALLOCATE (P)

END SUBROUTINE

SUBROUTINE DDIFFX2 (CDNAME, PALL)

CHARACTER(LEN=*) :: CDNAME
REAL (KIND=JPRB) :: PALL (:,:,:)
REAL (KIND=JPRB), POINTER :: P (:,:)

CALL LOAD (ILUN_OUT, P)

IF (KFDIA == IFDIA (IBL)) &
CALL DIFF (CDNAME, PALL (:, :, IBL), P)

DEALLOCATE (P)

END SUBROUTINE

SUBROUTINE DDIFFX3 (CDNAME, PALL)

CHARACTER(LEN=*) :: CDNAME
REAL (KIND=JPRB) :: PALL (:,:,:,:)
REAL (KIND=JPRB), POINTER :: P (:,:,:)

CALL LOAD (ILUN_OUT, P)

IF (KFDIA == IFDIA (IBL)) &
CALL DIFF (CDNAME, PALL (:, :, :, IBL), P)

DEALLOCATE (P)

END SUBROUTINE



END 
