

#ifdef GPU
#define ATTR_ARG , DEVICE
USE CUDAFOR
#else
#define ATTR_ARG
#endif

USE PARKIND1, ONLY : JPIM, JPRB
USE XRD_GETOPTIONS

USE LOAD_MOD

IMPLICIT NONE

INTERFACE SETALL
  PROCEDURE SETALLI1
  PROCEDURE SETALLI2
  PROCEDURE SETALLX1
  PROCEDURE SETALLX2
  PROCEDURE SETALLX3
END INTERFACE

INTERFACE DDIFF
  PROCEDURE DDIFFX1
  PROCEDURE DDIFFX2
  PROCEDURE DDIFFX3
END INTERFACE

INTEGER(KIND=JPIM) :: KFDIA
INTEGER(KIND=JPIM) :: KIDIA
INTEGER(KIND=JPIM) :: KLEV
INTEGER(KIND=JPIM) :: KLON
INTEGER(KIND=JPIM) :: KTDIA
INTEGER(KIND=JPIM) :: KTRA

INTEGER(KIND=JPIM) ATTR_ARG :: KFDIA_ALL
INTEGER(KIND=JPIM) ATTR_ARG :: KIDIA_ALL
INTEGER(KIND=JPIM) ATTR_ARG :: KLEV_ALL
INTEGER(KIND=JPIM) ATTR_ARG :: KLON_ALL
INTEGER(KIND=JPIM) ATTR_ARG :: KTDIA_ALL
INTEGER(KIND=JPIM) ATTR_ARG :: KTRA_ALL

INTEGER(KIND=JPIM), ALLOCATABLE :: IFDIA (:)

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PALPH_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PAPHI_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PAPHIF_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PAPRS_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PAPRSF_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PCP_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PLH_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PR_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDELP_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PLNPR_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQ_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQI_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PS_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PRR_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQLIS_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQSAT_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQW_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PRDELP_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PCVGQ_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PT_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PTW_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PU_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PTKE_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PTRA_ALL (:, :, :,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQLCONV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQICONV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQRCONV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQSCONV_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PGM_ALL (:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PTS_ALL (:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQS_ALL (:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PNEIJ_ALL (:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PLSM_ALL (:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PVETAF_ALL(:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDIFCQ_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDIFCQL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDIFCQI_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDIFCQLC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDIFCQIC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDIFCS_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDIFCTH_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFCCQL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFCCQN_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PSTRCU_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PSTRCV_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PMF_UP_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PSTRCTRA_ALL (:, :, :,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFIMCC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFPEVPCL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFPEVPCN_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFPLCL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFPLCN_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFPFPCL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFPFPCN_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFEDQLC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFEDQIC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFEDQRC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFEDQSC_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFCNEGQLC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFCNEGQIC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFCNEGQRC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PFCNEGQSC_ALL (:,:,:) => NULL ()

INTEGER(KIND=JPIM) ATTR_ARG, POINTER :: KNLAB_ALL (:,:,:) => NULL ()
INTEGER(KIND=JPIM) ATTR_ARG, POINTER :: KNND_ALL (:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PNEBC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQLIC_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PTU_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQU_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PQC_DET_PCMT_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PCSGC_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PCAPE_ALL (:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PAIPCMT_ALL (:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PALF_CAPE_ALL (:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PALF_CVGQ_ALL (:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PUDAL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PUDOM_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDDAL_ALL (:,:,:) => NULL ()
REAL(KIND=JPRB) ATTR_ARG,  POINTER :: PDDOM_ALL (:,:,:) => NULL ()

REAL(KIND=JPRB) ATTR_ARG,     POINTER    :: PSTACK_ALL (:,:,:) => NULL ()
INTEGER(KIND=JPIM) ATTR_ARG, POINTER    :: KSTACK_ALL (:,:,:) => NULL ()
INTEGER(KIND=JPIM) :: KKSTSZ, KPSTSZ, KKSTPT, KPSTPT
INTEGER(KIND=JPIM) ATTR_ARG :: KKSTSZ_ALL, KPSTSZ_ALL, KKSTPT_ALL, KPSTPT_ALL
INTEGER(KIND=JPIM) ATTR_ARG :: ICOUNT_ALL

INTEGER :: ICOUNT, IBL, JJ, JIDIA, JFDIA
INTEGER :: ICOUNT1, KLON1
INTEGER :: ICOUNT0, KLON0
LOGICAL :: LLDIFF, LLPRINT, LLLPRINT
CHARACTER (LEN=32) :: CLCASE
INTEGER, POINTER :: IDIFFBLOCK (:) => NULL ()
#ifdef GPU
TYPE (CUDAEVENT) :: STARTEVENT, STOPEVENT
#endif
REAL :: TIME
INTEGER :: ZV1 (8), ZV0 (8)
INTEGER :: ISTAT

#include "run_acpcmt.intfb.h"

CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--print", LLLPRINT)
CALL GETOPTION ("--diff-block-list", IDIFFBLOCK)
ICOUNT1 = 0
CALL GETOPTION ("--count", ICOUNT1)
KLON1 = 0
CALL GETOPTION ("--nproma", KLON1)
CALL CHECKOPTIONS ()

OPEN (77, FORM='FORMATTED', FILE=TRIM (CLCASE)//'/ACPCMT.COUNT')
READ (77, *) ICOUNT
CLOSE (77)

ALLOCATE (IFDIA (ICOUNT))

CALL ACPCMT_LOAD_ALL (TRIM (CLCASE)//'/ACPCMT.CONST')

CALL OPEN_LOAD (TRIM (CLCASE)//"/ACPCMT")

IF (ICOUNT1 == 0) ICOUNT1 = ICOUNT

PRINT *, "-- READ"

DO IBL = 1, ICOUNT

  PRINT *, IBL

  CALL LOAD (ILUN_IN, IFDIA (IBL))
  CALL LOAD (ILUN_IN, KIDIA)
  CALL LOAD (ILUN_IN, KLEV)
  CALL LOAD (ILUN_IN, KLON)
  IF (KLON1 == 0) KLON1 = KLON
  CALL LOAD (ILUN_IN, KTDIA)
  CALL LOAD (ILUN_IN, KTRA)
#define SET(x) CALL SETALL (x##_ALL)
  SET (PALPH)
  SET (PAPHI)
  SET (PAPHIF)
  SET (PAPRS)
  SET (PAPRSF)
  SET (PCP)
  SET (PLH)
  SET (PR)
  SET (PDELP)
  SET (PLNPR)
  SET (PQ)
  SET (PQI)
  SET (PQL)
  SET (PS)
  SET (PRR)
  SET (PQLIS)
  SET (PQSAT)
  SET (PQW)
  SET (PRDELP)
  SET (PCVGQ)
  SET (PT)
  SET (PTW)
  SET (PU)
  SET (PV)
  SET (PTKE)
  SET (PTRA)
  SET (PQLCONV)
  SET (PQICONV)
  SET (PQRCONV)
  SET (PQSCONV)
  SET (PGM)
  SET (PTS)
  SET (PQS)
  SET (PNEIJ)
  SET (PLSM)
  CALL SETALL (PVETAF_ALL, .FALSE.)
  SET (PDIFCQ)
  SET (PDIFCQL)
  SET (PDIFCQI)
  SET (PDIFCQLC)
  SET (PDIFCQIC)
  SET (PDIFCS)
  SET (PDIFCTH)
  SET (PFCCQL)
  SET (PFCCQN)
  SET (PSTRCU)
  SET (PSTRCV)
  SET (PMF_UP) 
  SET (PSTRCTRA)
  SET (PFIMCC)
  SET (PFPEVPCL)
  SET (PFPEVPCN)
  SET (PFPLCL)
  SET (PFPLCN)
  SET (PFPFPCL)
  SET (PFPFPCN)
  SET (PFEDQLC)
  SET (PFEDQIC)
  SET (PFEDQRC)
  SET (PFEDQSC)
  SET (PFCNEGQLC)
  SET (PFCNEGQIC)
  SET (PFCNEGQRC)
  SET (PFCNEGQSC)
  SET (KNLAB)
  SET (KNND)
  SET (PNEBC)
  SET (PQLIC)
  SET (PTU)
  SET (PQU) 
  SET (PQC_DET_PCMT)
  SET (PCSGC) 
  SET (PCAPE)
  SET (PAIPCMT)
  SET (PALF_CAPE)
  SET (PALF_CVGQ)
  SET (PUDAL)
  SET (PUDOM)
  SET (PDDAL)
  SET (PDDOM)
#undef SET
ENDDO


KLON0 = KLON; ICOUNT0 = ICOUNT
KLON = KLON1; ICOUNT = ICOUNT1

KFDIA = KLON

KPSTPT = 1
KKSTPT = 1

KPSTSZ =   200 * KLEV
KKSTSZ =   20 * KLEV

ALLOCATE (KSTACK_ALL (KLON, KKSTSZ, ICOUNT))
ALLOCATE (PSTACK_ALL (KLON, KPSTSZ, ICOUNT))

KSTACK_ALL = 0_JPIM
PSTACK_ALL = 0._JPRB

PRINT *, "-- RUN"

KFDIA_ALL  = KFDIA
KIDIA_ALL  = KIDIA
KLEV_ALL   = KLEV
KLON_ALL   = KLON
KTDIA_ALL  = KTDIA
KTRA_ALL   = KTRA
ICOUNT_ALL = ICOUNT
KPSTSZ_ALL = KPSTSZ
KKSTSZ_ALL = KKSTSZ
KPSTPT_ALL = KPSTPT
KKSTPT_ALL = KKSTPT

CALL DATE_AND_TIME (VALUES=ZV0)

#ifdef GPU

ISTAT = CUDAEVENTCREATE (STARTEVENT)
ISTAT = CUDAEVENTCREATE (STOPEVENT)
ISTAT = CUDAEVENTRECORD (STARTEVENT, 0)

CALL RUN_ACPCMT <<<ICOUNT,KLON>>> &
#endif
#ifdef CPU
CALL RUN_ACPCMT &
#endif
  & (KIDIA_ALL,KFDIA_ALL,KLON_ALL,KTDIA_ALL,KLEV_ALL,KTRA_ALL,&
  & PALPH_ALL,PAPHI_ALL,PAPHIF_ALL,PAPRS_ALL,&
  & PAPRSF_ALL,PCP_ALL,PLH_ALL,PR_ALL,PDELP_ALL,PLNPR_ALL,&
  & PQ_ALL,PQI_ALL,PQL_ALL,PRR_ALL,PS_ALL,PQLIS_ALL,PQSAT_ALL,PQW_ALL,&
  & PRDELP_ALL,PCVGQ_ALL,PT_ALL,PTW_ALL,PU_ALL,PV_ALL,PTKE_ALL,PTRA_ALL,&
  & PQLCONV_ALL,PQICONV_ALL,PQRCONV_ALL,PQSCONV_ALL,PGM_ALL,PTS_ALL,PQS_ALL,PNEIJ_ALL, &
  & PLSM_ALL,PVETAF_ALL,PDIFCQ_ALL,PDIFCQL_ALL,PDIFCQI_ALL,PDIFCQLC_ALL,&
  & PDIFCQIC_ALL,PDIFCS_ALL,PDIFCTH_ALL,PFCCQL_ALL,PFCCQN_ALL,PSTRCU_ALL,PSTRCV_ALL,&
  & PSTRCTRA_ALL,PFIMCC_ALL,PFPEVPCL_ALL,PFPEVPCN_ALL,&
  & PFPLCL_ALL,PFPLCN_ALL,PMF_UP_ALL,PFPFPCL_ALL,PFPFPCN_ALL,&
  & PFEDQLC_ALL, PFEDQIC_ALL, PFEDQRC_ALL, PFEDQSC_ALL,&
  & PFCNEGQLC_ALL,PFCNEGQIC_ALL,PFCNEGQRC_ALL,PFCNEGQSC_ALL, &
  & KNLAB_ALL,PNEBC_ALL,PQLIC_ALL,PTU_ALL,PQU_ALL,&
  & PQC_DET_PCMT_ALL,PCSGC_ALL,KNND_ALL, PCAPE_ALL,PAIPCMT_ALL,&
  & PALF_CAPE_ALL,PALF_CVGQ_ALL, PUDAL_ALL,PUDOM_ALL,PDDAL_ALL,PDDOM_ALL,&
  & KSTACK_ALL,PSTACK_ALL,KPSTSZ_ALL,KKSTSZ_ALL,KPSTPT_ALL,KKSTPT_ALL,ICOUNT_ALL)


#ifdef GPU
ISTAT = CUDADEVICESYNCHRONIZE ()
PRINT *, " ISTAT = ", ISTAT
ISTAT = CUDAEVENTRECORD (STOPEVENT, 0)
ISTAT = CUDAEVENTSYNCHRONIZE (STOPEVENT)
ISTAT = CUDAEVENTELAPSEDTIME (TIME, STARTEVENT, STOPEVENT)

#ifdef UNDEF
PRINT *, " CUDAEVENTELAPSEDTIME = ", TIME, " milliseconds"
#endif

#else
ISTAT = 0
PRINT *, " ISTAT = ", ISTAT


#endif

#ifdef UNDEF
CALL DATE_AND_TIME (VALUES=ZV1)
PRINT *, " DATE_AND_TIME = ", REAL (ZV1 (5) - ZV0 (5), 8) * 3600._8 + REAL (ZV1 (6) - ZV0 (6), 8) * 60._8 + &
& REAL (ZV1 (7) - ZV0 (7), 8) + REAL (ZV1 (8) - ZV0 (8), 8) / 1000._8, " seconds"
#endif




IF (LLDIFF .AND. ICOUNT0 >= ICOUNT1 .AND. KLON0 == KLON1) THEN

PRINT *, "-- DIFF"

DO IBL = 1, 2

  LLPRINT = .TRUE.
  IF (ASSOCIATED (IDIFFBLOCK)) THEN
    IF (.NOT. ANY (IDIFFBLOCK == IBL)) LLPRINT = .FALSE.
  ENDIF

  IF (LLPRINT) PRINT *, IBL

#define DIFF(x) CALL DDIFF (#x, x##_ALL, LLPRINT)

  DIFF (PDIFCQ)
  DIFF (PDIFCQL)
  DIFF (PDIFCQI)
  DIFF (PDIFCQLC)
  DIFF (PDIFCQIC)
  DIFF (PDIFCS)
  DIFF (PDIFCTH)
  DIFF (PFCCQL)
  DIFF (PFCCQN)
  DIFF (PSTRCU)
  DIFF (PSTRCV)
  DIFF (PMF_UP)
  DIFF (PSTRCTRA)
  DIFF (PFIMCC)
  DIFF (PFPEVPCL)
  DIFF (PFPEVPCN)
  DIFF (PFPLCL)
  DIFF (PFPLCN)
  DIFF (PFPFPCL)
  DIFF (PFPFPCN)
  DIFF (PFEDQLC)
  DIFF (PFEDQIC)
  DIFF (PFEDQRC)
  DIFF (PFEDQSC)
  DIFF (PFCNEGQLC)
  DIFF (PFCNEGQIC)
  DIFF (PFCNEGQRC)
  DIFF (PFCNEGQSC)
  DIFF (PNEBC)
  DIFF (PQLIC)
  DIFF (PTU)
  DIFF (PQU)
  DIFF (PQC_DET_PCMT)
  DIFF (PCSGC)
  DIFF (PCAPE)
  DIFF (PAIPCMT)
  DIFF (PALF_CAPE)
  DIFF (PALF_CVGQ)
  DIFF (PUDAL)
  DIFF (PUDOM)
  DIFF (PDDAL)
  DIFF (PDDOM)

#undef DIFF

ENDDO

ENDIF

CALL CLOSE_LOAD

#undef SAVEA

CONTAINS

#include "contains.h"

END 
