#include "attr_mod.h"
MODULE YOMADVPRCS

USE PARKIND1

LOGICAL ATTR_MOD :: LLMELTS,LLFREEZ
LOGICAL ATTR_MOD :: LLEVAPX
REAL (KIND=JPRB) ATTR_MOD :: ZPREF, ZEPS,  &
 & ZFVELR,ZFVELS,ZTMELT,ZRHOW,ZNRHOW,                        &
 & ZNU1,ZNU2,ZTAU1,ZTAU2,ZSIGMA1,ZSIGMA2,                    &
 & ZDVISC,ZSQTVIS,ZCDARV,ZRHOREF,ZEXP1,ZEXP4,ZEXP6,          &
 & ZCOEFF1,ZCOEFF2,ZCOEFF2B,ZCOEFF3,ZCOEFF4,ZCOEFF5,ZCOEFF6, &
 & ZFVENTR1,ZFVENTR2,ZFVENTS1,ZFVENTS2                    

END MODULE
