MODULE YOMCST

USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

SAVE


REAL (KIND=JPRB)::  RA
REAL (KIND=JPRB)::  RALPD
REAL (KIND=JPRB)::  RALPS
REAL (KIND=JPRB)::  RALPW
REAL (KIND=JPRB)::  RATM
REAL (KIND=JPRB)::  RBETD
REAL (KIND=JPRB)::  RBETS
REAL (KIND=JPRB)::  RBETW
REAL (KIND=JPRB)::  RCPD
REAL (KIND=JPRB)::  RCPV
REAL (KIND=JPRB)::  RCS
REAL (KIND=JPRB)::  RCW
REAL (KIND=JPRB)::  RD
REAL (KIND=JPRB)::  RDAY
REAL (KIND=JPRB)::  RDT
REAL (KIND=JPRB)::  REA
REAL (KIND=JPRB)::  REPSM
REAL (KIND=JPRB)::  RETV
REAL (KIND=JPRB)::  RG
REAL (KIND=JPRB)::  RGAMD
REAL (KIND=JPRB)::  RGAMS
REAL (KIND=JPRB)::  RGAMW
REAL (KIND=JPRB)::  RKAPPA
REAL (KIND=JPRB)::  RLSTT
REAL (KIND=JPRB)::  RLVTT
REAL (KIND=JPRB)::  RPI
REAL (KIND=JPRB)::  RTT
REAL (KIND=JPRB)::  RV

END
