#include "attr_mod.h"
MODULE YOMCST

USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

SAVE


REAL (KIND=JPRB) ATTR_MOD ::  RA
REAL (KIND=JPRB) ATTR_MOD ::  RALPD
REAL (KIND=JPRB) ATTR_MOD ::  RALPS
REAL (KIND=JPRB) ATTR_MOD ::  RALPW
REAL (KIND=JPRB) ATTR_MOD ::  RATM
REAL (KIND=JPRB) ATTR_MOD ::  RBETD
REAL (KIND=JPRB) ATTR_MOD ::  RBETS
REAL (KIND=JPRB) ATTR_MOD ::  RBETW
REAL (KIND=JPRB) ATTR_MOD ::  RCPD
REAL (KIND=JPRB) ATTR_MOD ::  RCPV
REAL (KIND=JPRB) ATTR_MOD ::  RCS
REAL (KIND=JPRB) ATTR_MOD ::  RCW
REAL (KIND=JPRB) ATTR_MOD ::  RD
REAL (KIND=JPRB) ATTR_MOD ::  RDAY
REAL (KIND=JPRB) ATTR_MOD ::  RDT
REAL (KIND=JPRB) ATTR_MOD ::  REA
REAL (KIND=JPRB) ATTR_MOD ::  REPSM
REAL (KIND=JPRB) ATTR_MOD ::  RETV
REAL (KIND=JPRB) ATTR_MOD ::  RG
REAL (KIND=JPRB) ATTR_MOD ::  RGAMD
REAL (KIND=JPRB) ATTR_MOD ::  RGAMS
REAL (KIND=JPRB) ATTR_MOD ::  RGAMW
REAL (KIND=JPRB) ATTR_MOD ::  RKAPPA
REAL (KIND=JPRB) ATTR_MOD ::  RLSTT
REAL (KIND=JPRB) ATTR_MOD ::  RLVTT
REAL (KIND=JPRB) ATTR_MOD ::  RPI
REAL (KIND=JPRB) ATTR_MOD ::  RTT
REAL (KIND=JPRB) ATTR_MOD ::  RV

END
